// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Opt;

using Specodec;
using System;
using System.Collections.Generic;

public record OptSingleString(
    string? V = null
);

public static class OptSingleStringMethods {
public static void WriteOptSingleString(SpecWriter w, OptSingleString obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteString(obj.V); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleString> OptSingleStringCodec = new(
    Encode: (w, obj) => WriteOptSingleString(w, obj),
    Decode: r => {
        string? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleString(V: _V);
    }
);
} // OptSingleStringMethods

public record OptSingleBoolean(
    bool? V = null
);

public static class OptSingleBooleanMethods {
public static void WriteOptSingleBoolean(SpecWriter w, OptSingleBoolean obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteBool(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleBoolean> OptSingleBooleanCodec = new(
    Encode: (w, obj) => WriteOptSingleBoolean(w, obj),
    Decode: r => {
        bool? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleBoolean(V: _V);
    }
);
} // OptSingleBooleanMethods

public record OptSingleInt8(
    byte? V = null
);

public static class OptSingleInt8Methods {
public static void WriteOptSingleInt8(SpecWriter w, OptSingleInt8 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteInt32((sbyte)obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleInt8> OptSingleInt8Codec = new(
    Encode: (w, obj) => WriteOptSingleInt8(w, obj),
    Decode: r => {
        byte? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = (byte)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleInt8(V: _V);
    }
);
} // OptSingleInt8Methods

public record OptSingleInt16(
    short? V = null
);

public static class OptSingleInt16Methods {
public static void WriteOptSingleInt16(SpecWriter w, OptSingleInt16 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteInt32(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleInt16> OptSingleInt16Codec = new(
    Encode: (w, obj) => WriteOptSingleInt16(w, obj),
    Decode: r => {
        short? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = (short)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleInt16(V: _V);
    }
);
} // OptSingleInt16Methods

public record OptSingleInt32(
    int? V = null
);

public static class OptSingleInt32Methods {
public static void WriteOptSingleInt32(SpecWriter w, OptSingleInt32 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteInt32(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleInt32> OptSingleInt32Codec = new(
    Encode: (w, obj) => WriteOptSingleInt32(w, obj),
    Decode: r => {
        int? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleInt32(V: _V);
    }
);
} // OptSingleInt32Methods

public record OptSingleInt64(
    long? V = null
);

public static class OptSingleInt64Methods {
public static void WriteOptSingleInt64(SpecWriter w, OptSingleInt64 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteInt64(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleInt64> OptSingleInt64Codec = new(
    Encode: (w, obj) => WriteOptSingleInt64(w, obj),
    Decode: r => {
        long? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleInt64(V: _V);
    }
);
} // OptSingleInt64Methods

public record OptSingleUint8(
    byte? V = null
);

public static class OptSingleUint8Methods {
public static void WriteOptSingleUint8(SpecWriter w, OptSingleUint8 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteUint32(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleUint8> OptSingleUint8Codec = new(
    Encode: (w, obj) => WriteOptSingleUint8(w, obj),
    Decode: r => {
        byte? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = (byte)r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleUint8(V: _V);
    }
);
} // OptSingleUint8Methods

public record OptSingleUint16(
    ushort? V = null
);

public static class OptSingleUint16Methods {
public static void WriteOptSingleUint16(SpecWriter w, OptSingleUint16 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteUint32(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleUint16> OptSingleUint16Codec = new(
    Encode: (w, obj) => WriteOptSingleUint16(w, obj),
    Decode: r => {
        ushort? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = (ushort)r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleUint16(V: _V);
    }
);
} // OptSingleUint16Methods

public record OptSingleUint32(
    uint? V = null
);

public static class OptSingleUint32Methods {
public static void WriteOptSingleUint32(SpecWriter w, OptSingleUint32 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteUint32(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleUint32> OptSingleUint32Codec = new(
    Encode: (w, obj) => WriteOptSingleUint32(w, obj),
    Decode: r => {
        uint? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleUint32(V: _V);
    }
);
} // OptSingleUint32Methods

public record OptSingleUint64(
    ulong? V = null
);

public static class OptSingleUint64Methods {
public static void WriteOptSingleUint64(SpecWriter w, OptSingleUint64 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteUint64(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleUint64> OptSingleUint64Codec = new(
    Encode: (w, obj) => WriteOptSingleUint64(w, obj),
    Decode: r => {
        ulong? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadUint64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleUint64(V: _V);
    }
);
} // OptSingleUint64Methods

public record OptSingleFloat32(
    float? V = null
);

public static class OptSingleFloat32Methods {
public static void WriteOptSingleFloat32(SpecWriter w, OptSingleFloat32 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteFloat32(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleFloat32> OptSingleFloat32Codec = new(
    Encode: (w, obj) => WriteOptSingleFloat32(w, obj),
    Decode: r => {
        float? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadFloat32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleFloat32(V: _V);
    }
);
} // OptSingleFloat32Methods

public record OptSingleFloat64(
    double? V = null
);

public static class OptSingleFloat64Methods {
public static void WriteOptSingleFloat64(SpecWriter w, OptSingleFloat64 obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteFloat64(obj.V.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleFloat64> OptSingleFloat64Codec = new(
    Encode: (w, obj) => WriteOptSingleFloat64(w, obj),
    Decode: r => {
        double? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleFloat64(V: _V);
    }
);
} // OptSingleFloat64Methods

public record OptSingleBytes(
    byte[]? V = null
);

public static class OptSingleBytesMethods {
public static void WriteOptSingleBytes(SpecWriter w, OptSingleBytes obj) {
    var fieldCount = 0;
    if (obj.V != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.V != null) { w.WriteField("v"); w.WriteBytes(obj.V); }
    w.EndObject();
}

public static readonly SpecCodec<OptSingleBytes> OptSingleBytesCodec = new(
    Encode: (w, obj) => WriteOptSingleBytes(w, obj),
    Decode: r => {
        byte[]? _V = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptSingleBytes(V: _V);
    }
);
} // OptSingleBytesMethods
