// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Extra;

using Specodec;
using System;
using System.Collections.Generic;

public record OptArr1(
    string Req,
    List<int>? Items = null
);

public static class OptArr1Methods {
public static void WriteOptArr1(SpecWriter w, OptArr1 obj) {
    var fieldCount = 1;
    if (obj.Items != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("req"); w.WriteString(obj.Req);
    if (obj.Items != null) { w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteInt32(item); }
        w.EndArray(); }
    w.EndObject();
}

public static readonly SpecCodec<OptArr1> OptArr1Codec = new(
    Encode: (w, obj) => WriteOptArr1(w, obj),
    Decode: r => {
        string _Req = "";
        List<int>? _Items = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "req": _Req = r.ReadString(); break;
                case "items": _Items = ((Func<List<int>>)(() => { var list = new List<int>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadInt32()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptArr1(Req: _Req, Items: _Items);
    }
);
} // OptArr1Methods

public record OptArr2(
    int Id,
    List<string>? Names = null,
    List<bool>? Flags = null
);

public static class OptArr2Methods {
public static void WriteOptArr2(SpecWriter w, OptArr2 obj) {
    var fieldCount = 1;
    if (obj.Names != null) fieldCount++;
    if (obj.Flags != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("id"); w.WriteInt32(obj.Id);
    if (obj.Names != null) { w.WriteField("names"); w.BeginArray(obj.Names.Count);
        foreach (var item in obj.Names) { w.NextElement(); w.WriteString(item); }
        w.EndArray(); }
    if (obj.Flags != null) { w.WriteField("flags"); w.BeginArray(obj.Flags.Count);
        foreach (var item in obj.Flags) { w.NextElement(); w.WriteBool(item); }
        w.EndArray(); }
    w.EndObject();
}

public static readonly SpecCodec<OptArr2> OptArr2Codec = new(
    Encode: (w, obj) => WriteOptArr2(w, obj),
    Decode: r => {
        int _Id = 0;
        List<string>? _Names = null;
        List<bool>? _Flags = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "id": _Id = r.ReadInt32(); break;
                case "names": _Names = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                case "flags": _Flags = ((Func<List<bool>>)(() => { var list = new List<bool>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadBool()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptArr2(Id: _Id, Names: _Names, Flags: _Flags);
    }
);
} // OptArr2Methods

public record OptArr3(
    List<string>? A = null,
    List<double>? B = null
);

public static class OptArr3Methods {
public static void WriteOptArr3(SpecWriter w, OptArr3 obj) {
    var fieldCount = 0;
    if (obj.A != null) fieldCount++;
    if (obj.B != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.A != null) { w.WriteField("a"); w.BeginArray(obj.A.Count);
        foreach (var item in obj.A) { w.NextElement(); w.WriteString(item); }
        w.EndArray(); }
    if (obj.B != null) { w.WriteField("b"); w.BeginArray(obj.B.Count);
        foreach (var item in obj.B) { w.NextElement(); w.WriteFloat64(item); }
        w.EndArray(); }
    w.EndObject();
}

public static readonly SpecCodec<OptArr3> OptArr3Codec = new(
    Encode: (w, obj) => WriteOptArr3(w, obj),
    Decode: r => {
        List<string>? _A = null;
        List<double>? _B = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                case "b": _B = ((Func<List<double>>)(() => { var list = new List<double>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadFloat64()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptArr3(A: _A, B: _B);
    }
);
} // OptArr3Methods

public record OptArr4(
    byte[] Payload,
    List<byte[]>? Chunks = null
);

public static class OptArr4Methods {
public static void WriteOptArr4(SpecWriter w, OptArr4 obj) {
    var fieldCount = 1;
    if (obj.Chunks != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("payload"); w.WriteBytes(obj.Payload);
    if (obj.Chunks != null) { w.WriteField("chunks"); w.BeginArray(obj.Chunks.Count);
        foreach (var item in obj.Chunks) { w.NextElement(); w.WriteBytes(item); }
        w.EndArray(); }
    w.EndObject();
}

public static readonly SpecCodec<OptArr4> OptArr4Codec = new(
    Encode: (w, obj) => WriteOptArr4(w, obj),
    Decode: r => {
        byte[] _Payload = Array.Empty<byte>();
        List<byte[]>? _Chunks = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "payload": _Payload = r.ReadBytes(); break;
                case "chunks": _Chunks = ((Func<List<byte[]>>)(() => { var list = new List<byte[]>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadBytes()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptArr4(Payload: _Payload, Chunks: _Chunks);
    }
);
} // OptArr4Methods

public record OptArr5(
    string Name,
    List<Inner>? Models = null
);

public static class OptArr5Methods {
public static void WriteOptArr5(SpecWriter w, OptArr5 obj) {
    var fieldCount = 1;
    if (obj.Models != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.Models != null) { w.WriteField("models"); w.BeginArray(obj.Models.Count);
        foreach (var item in obj.Models) { w.NextElement(); InnerMethods.WriteInner(w, item); }
        w.EndArray(); }
    w.WriteField("name"); w.WriteString(obj.Name);
    w.EndObject();
}

public static readonly SpecCodec<OptArr5> OptArr5Codec = new(
    Encode: (w, obj) => WriteOptArr5(w, obj),
    Decode: r => {
        List<Inner>? _Models = null;
        string _Name = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "models": _Models = ((Func<List<Inner>>)(() => { var list = new List<Inner>(); r.BeginArray(); while (r.HasNextElement()) list.Add(InnerMethods.InnerCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                case "name": _Name = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptArr5(Name: _Name, Models: _Models);
    }
);
} // OptArr5Methods

public record NestOpt1(
    Label Outer,
    string Name
);

public static class NestOpt1Methods {
public static void WriteNestOpt1(SpecWriter w, NestOpt1 obj) {
    w.BeginObject(2);
    w.WriteField("outer"); LabelMethods.WriteLabel(w, obj.Outer);
    w.WriteField("name"); w.WriteString(obj.Name);
    w.EndObject();
}

public static readonly SpecCodec<NestOpt1> NestOpt1Codec = new(
    Encode: (w, obj) => WriteNestOpt1(w, obj),
    Decode: r => {
        Label? _Outer = null;
        string _Name = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "outer": _Outer = LabelMethods.LabelCodec.Decode(r); break;
                case "name": _Name = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestOpt1(Outer: _Outer!, Name: _Name);
    }
);
} // NestOpt1Methods

public record NestOpt2(
    IdVal? A = null,
    IdVal? B = null,
    IdVal? C = null
);

public static class NestOpt2Methods {
public static void WriteNestOpt2(SpecWriter w, NestOpt2 obj) {
    var fieldCount = 0;
    if (obj.A != null) fieldCount++;
    if (obj.B != null) fieldCount++;
    if (obj.C != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.A != null) { w.WriteField("a"); IdValMethods.WriteIdVal(w, obj.A); }
    if (obj.B != null) { w.WriteField("b"); IdValMethods.WriteIdVal(w, obj.B); }
    if (obj.C != null) { w.WriteField("c"); IdValMethods.WriteIdVal(w, obj.C); }
    w.EndObject();
}

public static readonly SpecCodec<NestOpt2> NestOpt2Codec = new(
    Encode: (w, obj) => WriteNestOpt2(w, obj),
    Decode: r => {
        IdVal? _A = null;
        IdVal? _B = null;
        IdVal? _C = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.IsNull() ? ((Func<IdVal?>)(() => { r.ReadNull(); return null; }))() : IdValMethods.IdValCodec.Decode(r); break;
                case "b": _B = r.IsNull() ? ((Func<IdVal?>)(() => { r.ReadNull(); return null; }))() : IdValMethods.IdValCodec.Decode(r); break;
                case "c": _C = r.IsNull() ? ((Func<IdVal?>)(() => { r.ReadNull(); return null; }))() : IdValMethods.IdValCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestOpt2(A: _A, B: _B, C: _C);
    }
);
} // NestOpt2Methods

public record NestOpt3(
    Money Money,
    Range32? ValueRange = null
);

public static class NestOpt3Methods {
public static void WriteNestOpt3(SpecWriter w, NestOpt3 obj) {
    var fieldCount = 1;
    if (obj.ValueRange != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("money"); MoneyMethods.WriteMoney(w, obj.Money);
    if (obj.ValueRange != null) { w.WriteField("value_range"); Range32Methods.WriteRange32(w, obj.ValueRange); }
    w.EndObject();
}

public static readonly SpecCodec<NestOpt3> NestOpt3Codec = new(
    Encode: (w, obj) => WriteNestOpt3(w, obj),
    Decode: r => {
        Money? _Money = null;
        Range32? _ValueRange = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "money": _Money = MoneyMethods.MoneyCodec.Decode(r); break;
                case "value_range": _ValueRange = r.IsNull() ? ((Func<Range32?>)(() => { r.ReadNull(); return null; }))() : Range32Methods.Range32Codec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestOpt3(Money: _Money!, ValueRange: _ValueRange);
    }
);
} // NestOpt3Methods

public record NestOpt4(
    string Name,
    Addr? Addr = null,
    Coord? Coord = null
);

public static class NestOpt4Methods {
public static void WriteNestOpt4(SpecWriter w, NestOpt4 obj) {
    var fieldCount = 1;
    if (obj.Addr != null) fieldCount++;
    if (obj.Coord != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.Addr != null) { w.WriteField("addr"); AddrMethods.WriteAddr(w, obj.Addr); }
    if (obj.Coord != null) { w.WriteField("coord"); CoordMethods.WriteCoord(w, obj.Coord); }
    w.WriteField("name"); w.WriteString(obj.Name);
    w.EndObject();
}

public static readonly SpecCodec<NestOpt4> NestOpt4Codec = new(
    Encode: (w, obj) => WriteNestOpt4(w, obj),
    Decode: r => {
        Addr? _Addr = null;
        Coord? _Coord = null;
        string _Name = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "addr": _Addr = r.IsNull() ? ((Func<Addr?>)(() => { r.ReadNull(); return null; }))() : AddrMethods.AddrCodec.Decode(r); break;
                case "coord": _Coord = r.IsNull() ? ((Func<Coord?>)(() => { r.ReadNull(); return null; }))() : CoordMethods.CoordCodec.Decode(r); break;
                case "name": _Name = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestOpt4(Name: _Name, Addr: _Addr, Coord: _Coord);
    }
);
} // NestOpt4Methods

public record NestOpt5(
    Point3 Point,
    Addr Addr,
    Label? Label = null
);

public static class NestOpt5Methods {
public static void WriteNestOpt5(SpecWriter w, NestOpt5 obj) {
    var fieldCount = 2;
    if (obj.Label != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("point"); Point3Methods.WritePoint3(w, obj.Point);
    w.WriteField("addr"); AddrMethods.WriteAddr(w, obj.Addr);
    if (obj.Label != null) { w.WriteField("label"); LabelMethods.WriteLabel(w, obj.Label); }
    w.EndObject();
}

public static readonly SpecCodec<NestOpt5> NestOpt5Codec = new(
    Encode: (w, obj) => WriteNestOpt5(w, obj),
    Decode: r => {
        Point3? _Point = null;
        Addr? _Addr = null;
        Label? _Label = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "point": _Point = Point3Methods.Point3Codec.Decode(r); break;
                case "addr": _Addr = AddrMethods.AddrCodec.Decode(r); break;
                case "label": _Label = r.IsNull() ? ((Func<Label?>)(() => { r.ReadNull(); return null; }))() : LabelMethods.LabelCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestOpt5(Point: _Point!, Addr: _Addr!, Label: _Label);
    }
);
} // NestOpt5Methods

public record NestOptInner1(
    string Tag,
    OptInner? Nested = null
);

public static class NestOptInner1Methods {
public static void WriteNestOptInner1(SpecWriter w, NestOptInner1 obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("tag"); w.WriteString(obj.Tag);
    if (obj.Nested != null) { w.WriteField("nested"); OptInnerMethods.WriteOptInner(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<NestOptInner1> NestOptInner1Codec = new(
    Encode: (w, obj) => WriteNestOptInner1(w, obj),
    Decode: r => {
        string _Tag = "";
        OptInner? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "tag": _Tag = r.ReadString(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<OptInner?>)(() => { r.ReadNull(); return null; }))() : OptInnerMethods.OptInnerCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestOptInner1(Tag: _Tag, Nested: _Nested);
    }
);
} // NestOptInner1Methods

public record NestOptInner2(
    string Tag,
    OptInner Nested
);

public static class NestOptInner2Methods {
public static void WriteNestOptInner2(SpecWriter w, NestOptInner2 obj) {
    w.BeginObject(2);
    w.WriteField("tag"); w.WriteString(obj.Tag);
    w.WriteField("nested"); OptInnerMethods.WriteOptInner(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<NestOptInner2> NestOptInner2Codec = new(
    Encode: (w, obj) => WriteNestOptInner2(w, obj),
    Decode: r => {
        string _Tag = "";
        OptInner? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "tag": _Tag = r.ReadString(); break;
                case "nested": _Nested = OptInnerMethods.OptInnerCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestOptInner2(Tag: _Tag, Nested: _Nested!);
    }
);
} // NestOptInner2Methods

public record NestOptInner3(
    OptInner? Outer = null,
    OptInner? Nested = null
);

public static class NestOptInner3Methods {
public static void WriteNestOptInner3(SpecWriter w, NestOptInner3 obj) {
    var fieldCount = 0;
    if (obj.Outer != null) fieldCount++;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.Outer != null) { w.WriteField("outer"); OptInnerMethods.WriteOptInner(w, obj.Outer); }
    if (obj.Nested != null) { w.WriteField("nested"); OptInnerMethods.WriteOptInner(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<NestOptInner3> NestOptInner3Codec = new(
    Encode: (w, obj) => WriteNestOptInner3(w, obj),
    Decode: r => {
        OptInner? _Outer = null;
        OptInner? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "outer": _Outer = r.IsNull() ? ((Func<OptInner?>)(() => { r.ReadNull(); return null; }))() : OptInnerMethods.OptInnerCodec.Decode(r); break;
                case "nested": _Nested = r.IsNull() ? ((Func<OptInner?>)(() => { r.ReadNull(); return null; }))() : OptInnerMethods.OptInnerCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestOptInner3(Outer: _Outer, Nested: _Nested);
    }
);
} // NestOptInner3Methods

public record DeepNest1(
    string Label,
    Addr Nested
);

public static class DeepNest1Methods {
public static void WriteDeepNest1(SpecWriter w, DeepNest1 obj) {
    w.BeginObject(2);
    w.WriteField("label"); w.WriteString(obj.Label);
    w.WriteField("nested"); AddrMethods.WriteAddr(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<DeepNest1> DeepNest1Codec = new(
    Encode: (w, obj) => WriteDeepNest1(w, obj),
    Decode: r => {
        string _Label = "";
        Addr? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "nested": _Nested = AddrMethods.AddrCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DeepNest1(Label: _Label, Nested: _Nested!);
    }
);
} // DeepNest1Methods

public record DeepNest2(
    string Name,
    Money Money,
    Addr Addr
);

public static class DeepNest2Methods {
public static void WriteDeepNest2(SpecWriter w, DeepNest2 obj) {
    w.BeginObject(3);
    w.WriteField("name"); w.WriteString(obj.Name);
    w.WriteField("money"); MoneyMethods.WriteMoney(w, obj.Money);
    w.WriteField("addr"); AddrMethods.WriteAddr(w, obj.Addr);
    w.EndObject();
}

public static readonly SpecCodec<DeepNest2> DeepNest2Codec = new(
    Encode: (w, obj) => WriteDeepNest2(w, obj),
    Decode: r => {
        string _Name = "";
        Money? _Money = null;
        Addr? _Addr = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "name": _Name = r.ReadString(); break;
                case "money": _Money = MoneyMethods.MoneyCodec.Decode(r); break;
                case "addr": _Addr = AddrMethods.AddrCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DeepNest2(Name: _Name, Money: _Money!, Addr: _Addr!);
    }
);
} // DeepNest2Methods

public record DeepNest3(
    string Title,
    Point3 Point,
    Range32 ValueRange,
    Money Money
);

public static class DeepNest3Methods {
public static void WriteDeepNest3(SpecWriter w, DeepNest3 obj) {
    w.BeginObject(4);
    w.WriteField("title"); w.WriteString(obj.Title);
    w.WriteField("point"); Point3Methods.WritePoint3(w, obj.Point);
    w.WriteField("value_range"); Range32Methods.WriteRange32(w, obj.ValueRange);
    w.WriteField("money"); MoneyMethods.WriteMoney(w, obj.Money);
    w.EndObject();
}

public static readonly SpecCodec<DeepNest3> DeepNest3Codec = new(
    Encode: (w, obj) => WriteDeepNest3(w, obj),
    Decode: r => {
        string _Title = "";
        Point3? _Point = null;
        Range32? _ValueRange = null;
        Money? _Money = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "title": _Title = r.ReadString(); break;
                case "point": _Point = Point3Methods.Point3Codec.Decode(r); break;
                case "value_range": _ValueRange = Range32Methods.Range32Codec.Decode(r); break;
                case "money": _Money = MoneyMethods.MoneyCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DeepNest3(Title: _Title, Point: _Point!, ValueRange: _ValueRange!, Money: _Money!);
    }
);
} // DeepNest3Methods

public record DeepNest4(
    List<Coord> Coords,
    Inner Nested,
    string Tag
);

public static class DeepNest4Methods {
public static void WriteDeepNest4(SpecWriter w, DeepNest4 obj) {
    w.BeginObject(3);
    w.WriteField("coords"); w.BeginArray(obj.Coords.Count);
        foreach (var item in obj.Coords) { w.NextElement(); CoordMethods.WriteCoord(w, item); }
        w.EndArray();
    w.WriteField("nested"); InnerMethods.WriteInner(w, obj.Nested);
    w.WriteField("tag"); w.WriteString(obj.Tag);
    w.EndObject();
}

public static readonly SpecCodec<DeepNest4> DeepNest4Codec = new(
    Encode: (w, obj) => WriteDeepNest4(w, obj),
    Decode: r => {
        List<Coord> _Coords = new List<Coord>();
        Inner? _Nested = null;
        string _Tag = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "coords": _Coords = ((Func<List<Coord>>)(() => { var list = new List<Coord>(); r.BeginArray(); while (r.HasNextElement()) list.Add(CoordMethods.CoordCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                case "nested": _Nested = InnerMethods.InnerCodec.Decode(r); break;
                case "tag": _Tag = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DeepNest4(Coords: _Coords, Nested: _Nested!, Tag: _Tag);
    }
);
} // DeepNest4Methods

public record DeepNest5(
    List<Label> Labels,
    Money Money,
    string Name
);

public static class DeepNest5Methods {
public static void WriteDeepNest5(SpecWriter w, DeepNest5 obj) {
    w.BeginObject(3);
    w.WriteField("labels"); w.BeginArray(obj.Labels.Count);
        foreach (var item in obj.Labels) { w.NextElement(); LabelMethods.WriteLabel(w, item); }
        w.EndArray();
    w.WriteField("money"); MoneyMethods.WriteMoney(w, obj.Money);
    w.WriteField("name"); w.WriteString(obj.Name);
    w.EndObject();
}

public static readonly SpecCodec<DeepNest5> DeepNest5Codec = new(
    Encode: (w, obj) => WriteDeepNest5(w, obj),
    Decode: r => {
        List<Label> _Labels = new List<Label>();
        Money? _Money = null;
        string _Name = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "labels": _Labels = ((Func<List<Label>>)(() => { var list = new List<Label>(); r.BeginArray(); while (r.HasNextElement()) list.Add(LabelMethods.LabelCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                case "money": _Money = MoneyMethods.MoneyCodec.Decode(r); break;
                case "name": _Name = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DeepNest5(Labels: _Labels, Money: _Money!, Name: _Name);
    }
);
} // DeepNest5Methods

public record DeepNest6(
    List<IdVal> Items,
    Coord Coord,
    Addr? Addr = null
);

public static class DeepNest6Methods {
public static void WriteDeepNest6(SpecWriter w, DeepNest6 obj) {
    var fieldCount = 2;
    if (obj.Addr != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); IdValMethods.WriteIdVal(w, item); }
        w.EndArray();
    if (obj.Addr != null) { w.WriteField("addr"); AddrMethods.WriteAddr(w, obj.Addr); }
    w.WriteField("coord"); CoordMethods.WriteCoord(w, obj.Coord);
    w.EndObject();
}

public static readonly SpecCodec<DeepNest6> DeepNest6Codec = new(
    Encode: (w, obj) => WriteDeepNest6(w, obj),
    Decode: r => {
        List<IdVal> _Items = new List<IdVal>();
        Addr? _Addr = null;
        Coord? _Coord = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<IdVal>>)(() => { var list = new List<IdVal>(); r.BeginArray(); while (r.HasNextElement()) list.Add(IdValMethods.IdValCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                case "addr": _Addr = r.IsNull() ? ((Func<Addr?>)(() => { r.ReadNull(); return null; }))() : AddrMethods.AddrCodec.Decode(r); break;
                case "coord": _Coord = CoordMethods.CoordCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DeepNest6(Items: _Items, Coord: _Coord!, Addr: _Addr);
    }
);
} // DeepNest6Methods

public record DeepNest7(
    Addr A,
    Addr B,
    Addr C
);

public static class DeepNest7Methods {
public static void WriteDeepNest7(SpecWriter w, DeepNest7 obj) {
    w.BeginObject(3);
    w.WriteField("a"); AddrMethods.WriteAddr(w, obj.A);
    w.WriteField("b"); AddrMethods.WriteAddr(w, obj.B);
    w.WriteField("c"); AddrMethods.WriteAddr(w, obj.C);
    w.EndObject();
}

public static readonly SpecCodec<DeepNest7> DeepNest7Codec = new(
    Encode: (w, obj) => WriteDeepNest7(w, obj),
    Decode: r => {
        Addr? _A = null;
        Addr? _B = null;
        Addr? _C = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = AddrMethods.AddrCodec.Decode(r); break;
                case "b": _B = AddrMethods.AddrCodec.Decode(r); break;
                case "c": _C = AddrMethods.AddrCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DeepNest7(A: _A!, B: _B!, C: _C!);
    }
);
} // DeepNest7Methods

public record TimestampEntry(
    long Ts,
    string Event,
    byte[]? Payload = null
);

public static class TimestampEntryMethods {
public static void WriteTimestampEntry(SpecWriter w, TimestampEntry obj) {
    var fieldCount = 2;
    if (obj.Payload != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("ts"); w.WriteInt64(obj.Ts);
    w.WriteField("event"); w.WriteString(obj.Event);
    if (obj.Payload != null) { w.WriteField("payload"); w.WriteBytes(obj.Payload); }
    w.EndObject();
}

public static readonly SpecCodec<TimestampEntry> TimestampEntryCodec = new(
    Encode: (w, obj) => WriteTimestampEntry(w, obj),
    Decode: r => {
        long _Ts = 0L;
        string _Event = "";
        byte[]? _Payload = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "ts": _Ts = r.ReadInt64(); break;
                case "event": _Event = r.ReadString(); break;
                case "payload": _Payload = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new TimestampEntry(Ts: _Ts, Event: _Event, Payload: _Payload);
    }
);
} // TimestampEntryMethods

public record ConfigEntry(
    string Key,
    int? IntValue = null,
    string? StrValue = null,
    bool? BoolValue = null,
    double? FloatValue = null
);

public static class ConfigEntryMethods {
public static void WriteConfigEntry(SpecWriter w, ConfigEntry obj) {
    var fieldCount = 1;
    if (obj.IntValue != null) fieldCount++;
    if (obj.StrValue != null) fieldCount++;
    if (obj.BoolValue != null) fieldCount++;
    if (obj.FloatValue != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("key"); w.WriteString(obj.Key);
    if (obj.IntValue != null) { w.WriteField("intValue"); w.WriteInt32(obj.IntValue.Value); }
    if (obj.StrValue != null) { w.WriteField("strValue"); w.WriteString(obj.StrValue); }
    if (obj.BoolValue != null) { w.WriteField("boolValue"); w.WriteBool(obj.BoolValue.Value); }
    if (obj.FloatValue != null) { w.WriteField("floatValue"); w.WriteFloat64(obj.FloatValue.Value); }
    w.EndObject();
}

public static readonly SpecCodec<ConfigEntry> ConfigEntryCodec = new(
    Encode: (w, obj) => WriteConfigEntry(w, obj),
    Decode: r => {
        string _Key = "";
        int? _IntValue = null;
        string? _StrValue = null;
        bool? _BoolValue = null;
        double? _FloatValue = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "key": _Key = r.ReadString(); break;
                case "intValue": _IntValue = r.ReadInt32(); break;
                case "strValue": _StrValue = r.ReadString(); break;
                case "boolValue": _BoolValue = r.ReadBool(); break;
                case "floatValue": _FloatValue = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ConfigEntry(Key: _Key, IntValue: _IntValue, StrValue: _StrValue, BoolValue: _BoolValue, FloatValue: _FloatValue);
    }
);
} // ConfigEntryMethods
