// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.nested.deep;

using Specodec;
using System;
using System.Collections.Generic;

public record DeepModel(
    byte[] Payload,
    long Count
);

public static class DeepModelMethods {
public static void WriteDeepModel(SpecWriter w, DeepModel obj) {
    w.BeginObject(2);
    w.WriteField("payload"); w.WriteBytes(obj.Payload);
    w.WriteField("count"); w.WriteInt64(obj.Count);
    w.EndObject();
}

public static readonly SpecCodec<DeepModel> DeepModelCodec = new(
    Encode: (w, obj) => WriteDeepModel(w, obj),
    Decode: r => {
        byte[] _Payload = Array.Empty<byte>();
        long _Count = 0L;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "payload": _Payload = r.ReadBytes(); break;
                case "count": _Count = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DeepModel(Payload: _Payload, Count: _Count);
    }
);
} // DeepModelMethods
