// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Unions;

using Specodec;
using System;
using System.Collections.Generic;

public record UnionFieldHolder(
    Shape Shape,
    Ident Id
);

public static class UnionFieldHolderMethods {
public static void WriteUnionFieldHolder(SpecWriter w, UnionFieldHolder obj) {
    w.BeginObject(2);
    w.WriteField("shape"); ShapeMethods.WriteShape(w, obj.Shape);
    w.WriteField("id"); IdentMethods.WriteIdent(w, obj.Id);
    w.EndObject();
}

public static readonly SpecCodec<UnionFieldHolder> UnionFieldHolderCodec = new(
    Encode: (w, obj) => WriteUnionFieldHolder(w, obj),
    Decode: r => {
        Shape _Shape = new ShapeUndefined();
        Ident _Id = new IdentUndefined();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "shape": _Shape = ShapeMethods.ShapeCodec.Decode(r); break;
                case "id": _Id = IdentMethods.IdentCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new UnionFieldHolder(Shape: _Shape, Id: _Id);
    }
);
} // UnionFieldHolderMethods

public record OptUnionFieldHolder(
    string Name,
    Shape? Shape = null
);

public static class OptUnionFieldHolderMethods {
public static void WriteOptUnionFieldHolder(SpecWriter w, OptUnionFieldHolder obj) {
    var fieldCount = 1;
    if (obj.Shape != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.Shape != null) { w.WriteField("shape"); ShapeMethods.WriteShape(w, obj.Shape); }
    w.WriteField("name"); w.WriteString(obj.Name);
    w.EndObject();
}

public static readonly SpecCodec<OptUnionFieldHolder> OptUnionFieldHolderCodec = new(
    Encode: (w, obj) => WriteOptUnionFieldHolder(w, obj),
    Decode: r => {
        Shape? _Shape = null;
        string _Name = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "shape": _Shape = ShapeMethods.ShapeCodec.Decode(r); break;
                case "name": _Name = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptUnionFieldHolder(Name: _Name, Shape: _Shape);
    }
);
} // OptUnionFieldHolderMethods

public record UnionArrayHolder(
    List<Shape> Shapes
);

public static class UnionArrayHolderMethods {
public static void WriteUnionArrayHolder(SpecWriter w, UnionArrayHolder obj) {
    w.BeginObject(1);
    w.WriteField("shapes"); w.BeginArray(obj.Shapes.Count);
        foreach (var item in obj.Shapes) { w.NextElement(); ShapeMethods.WriteShape(w, item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<UnionArrayHolder> UnionArrayHolderCodec = new(
    Encode: (w, obj) => WriteUnionArrayHolder(w, obj),
    Decode: r => {
        List<Shape> _Shapes = new List<Shape>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "shapes": _Shapes = ((Func<List<Shape>>)(() => { var list = new List<Shape>(); r.BeginArray(); while (r.HasNextElement()) list.Add(ShapeMethods.ShapeCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new UnionArrayHolder(Shapes: _Shapes);
    }
);
} // UnionArrayHolderMethods

public record UnionMixedHolder(
    ResultMsg Result,
    Tagged Tag,
    int Count
);

public static class UnionMixedHolderMethods {
public static void WriteUnionMixedHolder(SpecWriter w, UnionMixedHolder obj) {
    w.BeginObject(3);
    w.WriteField("result"); ResultMsgMethods.WriteResultMsg(w, obj.Result);
    w.WriteField("tag"); TaggedMethods.WriteTagged(w, obj.Tag);
    w.WriteField("count"); w.WriteInt32(obj.Count);
    w.EndObject();
}

public static readonly SpecCodec<UnionMixedHolder> UnionMixedHolderCodec = new(
    Encode: (w, obj) => WriteUnionMixedHolder(w, obj),
    Decode: r => {
        ResultMsg _Result = new ResultMsgUndefined();
        Tagged _Tag = new TaggedUndefined();
        int _Count = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "result": _Result = ResultMsgMethods.ResultMsgCodec.Decode(r); break;
                case "tag": _Tag = TaggedMethods.TaggedCodec.Decode(r); break;
                case "count": _Count = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new UnionMixedHolder(Result: _Result, Tag: _Tag, Count: _Count);
    }
);
} // UnionMixedHolderMethods

public record UnionScalarHolder(
    Ident Id,
    ScalarUnion Sc,
    string Label
);

public static class UnionScalarHolderMethods {
public static void WriteUnionScalarHolder(SpecWriter w, UnionScalarHolder obj) {
    w.BeginObject(3);
    w.WriteField("id"); IdentMethods.WriteIdent(w, obj.Id);
    w.WriteField("sc"); ScalarUnionMethods.WriteScalarUnion(w, obj.Sc);
    w.WriteField("label"); w.WriteString(obj.Label);
    w.EndObject();
}

public static readonly SpecCodec<UnionScalarHolder> UnionScalarHolderCodec = new(
    Encode: (w, obj) => WriteUnionScalarHolder(w, obj),
    Decode: r => {
        Ident _Id = new IdentUndefined();
        ScalarUnion _Sc = new ScalarUnionUndefined();
        string _Label = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "id": _Id = IdentMethods.IdentCodec.Decode(r); break;
                case "sc": _Sc = ScalarUnionMethods.ScalarUnionCodec.Decode(r); break;
                case "label": _Label = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new UnionScalarHolder(Id: _Id, Sc: _Sc, Label: _Label);
    }
);
} // UnionScalarHolderMethods

public abstract record Shape;

public record ShapeCircle(Coord Value) : Shape;
public record ShapeRect(Range32 Value) : Shape;
public record ShapeUndefined() : Shape;

public static class ShapeMethods {
public static void WriteShape(SpecWriter w, Shape obj) {
    w.BeginObject(1);
    switch (obj) {
        case ShapeCircle v: w.WriteField("circle"); CoordMethods.WriteCoord(w, v.Value); break;
        case ShapeRect v: w.WriteField("rect"); Range32Methods.WriteRange32(w, v.Value); break;
        default: throw new Exception("cannot encode Undefined for Shape");
    }
    w.EndObject();
}

public static Shape DecodeShape(SpecReader r) {
    r.BeginObject();
    if (!r.HasNextField()) { r.EndObject(); throw new Exception("empty union"); }
    var field = r.ReadFieldName();
    Shape result = field switch {
        "circle" => new ShapeCircle(CoordMethods.CoordCodec.Decode(r)),
        "rect" => new ShapeRect(Range32Methods.Range32Codec.Decode(r)),
        _ => throw new Exception($"unknown variant {field}")
    };
    while (r.HasNextField()) { r.ReadFieldName(); r.Skip(); }
    r.EndObject();
    return result;
}

public static readonly SpecCodec<Shape> ShapeCodec = new(WriteShape, DecodeShape);
} // ShapeMethods

public abstract record Ident;

public record IdentName(string Value) : Ident;
public record IdentNumber(int Value) : Ident;
public record IdentUndefined() : Ident;

public static class IdentMethods {
public static void WriteIdent(SpecWriter w, Ident obj) {
    w.BeginObject(1);
    switch (obj) {
        case IdentName v: w.WriteField("name"); w.WriteString(v.Value); break;
        case IdentNumber v: w.WriteField("number"); w.WriteInt32(v.Value); break;
        default: throw new Exception("cannot encode Undefined for Ident");
    }
    w.EndObject();
}

public static Ident DecodeIdent(SpecReader r) {
    r.BeginObject();
    if (!r.HasNextField()) { r.EndObject(); throw new Exception("empty union"); }
    var field = r.ReadFieldName();
    Ident result = field switch {
        "name" => new IdentName(r.ReadString()),
        "number" => new IdentNumber(r.ReadInt32()),
        _ => throw new Exception($"unknown variant {field}")
    };
    while (r.HasNextField()) { r.ReadFieldName(); r.Skip(); }
    r.EndObject();
    return result;
}

public static readonly SpecCodec<Ident> IdentCodec = new(WriteIdent, DecodeIdent);
} // IdentMethods

public abstract record ResultMsg;

public record ResultMsgOk(string Value) : ResultMsg;
public record ResultMsgErr(Label Value) : ResultMsg;
public record ResultMsgUndefined() : ResultMsg;

public static class ResultMsgMethods {
public static void WriteResultMsg(SpecWriter w, ResultMsg obj) {
    w.BeginObject(1);
    switch (obj) {
        case ResultMsgOk v: w.WriteField("ok"); w.WriteString(v.Value); break;
        case ResultMsgErr v: w.WriteField("err"); LabelMethods.WriteLabel(w, v.Value); break;
        default: throw new Exception("cannot encode Undefined for ResultMsg");
    }
    w.EndObject();
}

public static ResultMsg DecodeResultMsg(SpecReader r) {
    r.BeginObject();
    if (!r.HasNextField()) { r.EndObject(); throw new Exception("empty union"); }
    var field = r.ReadFieldName();
    ResultMsg result = field switch {
        "ok" => new ResultMsgOk(r.ReadString()),
        "err" => new ResultMsgErr(LabelMethods.LabelCodec.Decode(r)),
        _ => throw new Exception($"unknown variant {field}")
    };
    while (r.HasNextField()) { r.ReadFieldName(); r.Skip(); }
    r.EndObject();
    return result;
}

public static readonly SpecCodec<ResultMsg> ResultMsgCodec = new(WriteResultMsg, DecodeResultMsg);
} // ResultMsgMethods

public abstract record Tagged;

public record TaggedTag(string Value) : Tagged;
public record TaggedScore(double Value) : Tagged;
public record TaggedActive(bool Value) : Tagged;
public record TaggedUndefined() : Tagged;

public static class TaggedMethods {
public static void WriteTagged(SpecWriter w, Tagged obj) {
    w.BeginObject(1);
    switch (obj) {
        case TaggedTag v: w.WriteField("tag"); w.WriteString(v.Value); break;
        case TaggedScore v: w.WriteField("score"); w.WriteFloat64(v.Value); break;
        case TaggedActive v: w.WriteField("active"); w.WriteBool(v.Value); break;
        default: throw new Exception("cannot encode Undefined for Tagged");
    }
    w.EndObject();
}

public static Tagged DecodeTagged(SpecReader r) {
    r.BeginObject();
    if (!r.HasNextField()) { r.EndObject(); throw new Exception("empty union"); }
    var field = r.ReadFieldName();
    Tagged result = field switch {
        "tag" => new TaggedTag(r.ReadString()),
        "score" => new TaggedScore(r.ReadFloat64()),
        "active" => new TaggedActive(r.ReadBool()),
        _ => throw new Exception($"unknown variant {field}")
    };
    while (r.HasNextField()) { r.ReadFieldName(); r.Skip(); }
    r.EndObject();
    return result;
}

public static readonly SpecCodec<Tagged> TaggedCodec = new(WriteTagged, DecodeTagged);
} // TaggedMethods

public abstract record ScalarUnion;

public record ScalarUnionS(string Value) : ScalarUnion;
public record ScalarUnionI(int Value) : ScalarUnion;
public record ScalarUnionF(double Value) : ScalarUnion;
public record ScalarUnionB(bool Value) : ScalarUnion;
public record ScalarUnionUndefined() : ScalarUnion;

public static class ScalarUnionMethods {
public static void WriteScalarUnion(SpecWriter w, ScalarUnion obj) {
    w.BeginObject(1);
    switch (obj) {
        case ScalarUnionS v: w.WriteField("s"); w.WriteString(v.Value); break;
        case ScalarUnionI v: w.WriteField("i"); w.WriteInt32(v.Value); break;
        case ScalarUnionF v: w.WriteField("f"); w.WriteFloat64(v.Value); break;
        case ScalarUnionB v: w.WriteField("b"); w.WriteBool(v.Value); break;
        default: throw new Exception("cannot encode Undefined for ScalarUnion");
    }
    w.EndObject();
}

public static ScalarUnion DecodeScalarUnion(SpecReader r) {
    r.BeginObject();
    if (!r.HasNextField()) { r.EndObject(); throw new Exception("empty union"); }
    var field = r.ReadFieldName();
    ScalarUnion result = field switch {
        "s" => new ScalarUnionS(r.ReadString()),
        "i" => new ScalarUnionI(r.ReadInt32()),
        "f" => new ScalarUnionF(r.ReadFloat64()),
        "b" => new ScalarUnionB(r.ReadBool()),
        _ => throw new Exception($"unknown variant {field}")
    };
    while (r.HasNextField()) { r.ReadFieldName(); r.Skip(); }
    r.EndObject();
    return result;
}

public static readonly SpecCodec<ScalarUnion> ScalarUnionCodec = new(WriteScalarUnion, DecodeScalarUnion);
} // ScalarUnionMethods

public abstract record OptUnionHolder;

public record OptUnionHolderShape(Shape Value) : OptUnionHolder;
public record OptUnionHolderId(Ident Value) : OptUnionHolder;
public record OptUnionHolderUndefined() : OptUnionHolder;

public static class OptUnionHolderMethods {
public static void WriteOptUnionHolder(SpecWriter w, OptUnionHolder obj) {
    w.BeginObject(1);
    switch (obj) {
        case OptUnionHolderShape v: w.WriteField("shape"); ShapeMethods.WriteShape(w, v.Value); break;
        case OptUnionHolderId v: w.WriteField("id"); IdentMethods.WriteIdent(w, v.Value); break;
        default: throw new Exception("cannot encode Undefined for OptUnionHolder");
    }
    w.EndObject();
}

public static OptUnionHolder DecodeOptUnionHolder(SpecReader r) {
    r.BeginObject();
    if (!r.HasNextField()) { r.EndObject(); throw new Exception("empty union"); }
    var field = r.ReadFieldName();
    OptUnionHolder result = field switch {
        "shape" => new OptUnionHolderShape(ShapeMethods.ShapeCodec.Decode(r)),
        "id" => new OptUnionHolderId(IdentMethods.IdentCodec.Decode(r)),
        _ => throw new Exception($"unknown variant {field}")
    };
    while (r.HasNextField()) { r.ReadFieldName(); r.Skip(); }
    r.EndObject();
    return result;
}

public static readonly SpecCodec<OptUnionHolder> OptUnionHolderCodec = new(WriteOptUnionHolder, DecodeOptUnionHolder);
} // OptUnionHolderMethods

public abstract record MixedUnion;

public record MixedUnionPoint(Coord Value) : MixedUnion;
public record MixedUnionLabel(string Value) : MixedUnion;
public record MixedUnionCount(int Value) : MixedUnion;
public record MixedUnionUndefined() : MixedUnion;

public static class MixedUnionMethods {
public static void WriteMixedUnion(SpecWriter w, MixedUnion obj) {
    w.BeginObject(1);
    switch (obj) {
        case MixedUnionPoint v: w.WriteField("point"); CoordMethods.WriteCoord(w, v.Value); break;
        case MixedUnionLabel v: w.WriteField("label"); w.WriteString(v.Value); break;
        case MixedUnionCount v: w.WriteField("count"); w.WriteInt32(v.Value); break;
        default: throw new Exception("cannot encode Undefined for MixedUnion");
    }
    w.EndObject();
}

public static MixedUnion DecodeMixedUnion(SpecReader r) {
    r.BeginObject();
    if (!r.HasNextField()) { r.EndObject(); throw new Exception("empty union"); }
    var field = r.ReadFieldName();
    MixedUnion result = field switch {
        "point" => new MixedUnionPoint(CoordMethods.CoordCodec.Decode(r)),
        "label" => new MixedUnionLabel(r.ReadString()),
        "count" => new MixedUnionCount(r.ReadInt32()),
        _ => throw new Exception($"unknown variant {field}")
    };
    while (r.HasNextField()) { r.ReadFieldName(); r.Skip(); }
    r.EndObject();
    return result;
}

public static readonly SpecCodec<MixedUnion> MixedUnionCodec = new(WriteMixedUnion, DecodeMixedUnion);
} // MixedUnionMethods

public abstract record NestedUnion;

public record NestedUnionResult(ResultMsg Value) : NestedUnion;
public record NestedUnionShape(Shape Value) : NestedUnion;
public record NestedUnionUndefined() : NestedUnion;

public static class NestedUnionMethods {
public static void WriteNestedUnion(SpecWriter w, NestedUnion obj) {
    w.BeginObject(1);
    switch (obj) {
        case NestedUnionResult v: w.WriteField("result"); ResultMsgMethods.WriteResultMsg(w, v.Value); break;
        case NestedUnionShape v: w.WriteField("shape"); ShapeMethods.WriteShape(w, v.Value); break;
        default: throw new Exception("cannot encode Undefined for NestedUnion");
    }
    w.EndObject();
}

public static NestedUnion DecodeNestedUnion(SpecReader r) {
    r.BeginObject();
    if (!r.HasNextField()) { r.EndObject(); throw new Exception("empty union"); }
    var field = r.ReadFieldName();
    NestedUnion result = field switch {
        "result" => new NestedUnionResult(ResultMsgMethods.ResultMsgCodec.Decode(r)),
        "shape" => new NestedUnionShape(ShapeMethods.ShapeCodec.Decode(r)),
        _ => throw new Exception($"unknown variant {field}")
    };
    while (r.HasNextField()) { r.ReadFieldName(); r.Skip(); }
    r.EndObject();
    return result;
}

public static readonly SpecCodec<NestedUnion> NestedUnionCodec = new(WriteNestedUnion, DecodeNestedUnion);
} // NestedUnionMethods
