// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Arrays;

using Specodec;
using System;
using System.Collections.Generic;

public record ArrString(
    List<string> Items
);

public static class ArrStringMethods {
public static void WriteArrString(SpecWriter w, ArrString obj) {
    w.BeginObject(1);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteString(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ArrString> ArrStringCodec = new(
    Encode: (w, obj) => WriteArrString(w, obj),
    Decode: r => {
        List<string> _Items = new List<string>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ArrString(Items: _Items);
    }
);
} // ArrStringMethods

public record ArrInt32(
    List<int> Items
);

public static class ArrInt32Methods {
public static void WriteArrInt32(SpecWriter w, ArrInt32 obj) {
    w.BeginObject(1);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteInt32(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ArrInt32> ArrInt32Codec = new(
    Encode: (w, obj) => WriteArrInt32(w, obj),
    Decode: r => {
        List<int> _Items = new List<int>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<int>>)(() => { var list = new List<int>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadInt32()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ArrInt32(Items: _Items);
    }
);
} // ArrInt32Methods

public record ArrBoolean(
    List<bool> Items
);

public static class ArrBooleanMethods {
public static void WriteArrBoolean(SpecWriter w, ArrBoolean obj) {
    w.BeginObject(1);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteBool(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ArrBoolean> ArrBooleanCodec = new(
    Encode: (w, obj) => WriteArrBoolean(w, obj),
    Decode: r => {
        List<bool> _Items = new List<bool>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<bool>>)(() => { var list = new List<bool>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadBool()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ArrBoolean(Items: _Items);
    }
);
} // ArrBooleanMethods

public record ArrFloat64(
    List<double> Items
);

public static class ArrFloat64Methods {
public static void WriteArrFloat64(SpecWriter w, ArrFloat64 obj) {
    w.BeginObject(1);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteFloat64(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ArrFloat64> ArrFloat64Codec = new(
    Encode: (w, obj) => WriteArrFloat64(w, obj),
    Decode: r => {
        List<double> _Items = new List<double>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<double>>)(() => { var list = new List<double>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadFloat64()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ArrFloat64(Items: _Items);
    }
);
} // ArrFloat64Methods

public record ArrBytes(
    List<byte[]> Items
);

public static class ArrBytesMethods {
public static void WriteArrBytes(SpecWriter w, ArrBytes obj) {
    w.BeginObject(1);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteBytes(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ArrBytes> ArrBytesCodec = new(
    Encode: (w, obj) => WriteArrBytes(w, obj),
    Decode: r => {
        List<byte[]> _Items = new List<byte[]>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<byte[]>>)(() => { var list = new List<byte[]>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadBytes()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ArrBytes(Items: _Items);
    }
);
} // ArrBytesMethods

public record ArrInt64(
    List<long> Items
);

public static class ArrInt64Methods {
public static void WriteArrInt64(SpecWriter w, ArrInt64 obj) {
    w.BeginObject(1);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteInt64(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ArrInt64> ArrInt64Codec = new(
    Encode: (w, obj) => WriteArrInt64(w, obj),
    Decode: r => {
        List<long> _Items = new List<long>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<long>>)(() => { var list = new List<long>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadInt64()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ArrInt64(Items: _Items);
    }
);
} // ArrInt64Methods

public record ArrUint64(
    List<ulong> Items
);

public static class ArrUint64Methods {
public static void WriteArrUint64(SpecWriter w, ArrUint64 obj) {
    w.BeginObject(1);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteUint64(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ArrUint64> ArrUint64Codec = new(
    Encode: (w, obj) => WriteArrUint64(w, obj),
    Decode: r => {
        List<ulong> _Items = new List<ulong>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<ulong>>)(() => { var list = new List<ulong>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadUint64()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ArrUint64(Items: _Items);
    }
);
} // ArrUint64Methods

public record MultiArr1(
    List<string> Names,
    List<int> Scores
);

public static class MultiArr1Methods {
public static void WriteMultiArr1(SpecWriter w, MultiArr1 obj) {
    w.BeginObject(2);
    w.WriteField("names"); w.BeginArray(obj.Names.Count);
        foreach (var item in obj.Names) { w.NextElement(); w.WriteString(item); }
        w.EndArray();
    w.WriteField("scores"); w.BeginArray(obj.Scores.Count);
        foreach (var item in obj.Scores) { w.NextElement(); w.WriteInt32(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<MultiArr1> MultiArr1Codec = new(
    Encode: (w, obj) => WriteMultiArr1(w, obj),
    Decode: r => {
        List<string> _Names = new List<string>();
        List<int> _Scores = new List<int>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "names": _Names = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                case "scores": _Scores = ((Func<List<int>>)(() => { var list = new List<int>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadInt32()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new MultiArr1(Names: _Names, Scores: _Scores);
    }
);
} // MultiArr1Methods

public record MultiArr2(
    List<bool> Flags,
    List<double> Values,
    List<byte[]> Payload
);

public static class MultiArr2Methods {
public static void WriteMultiArr2(SpecWriter w, MultiArr2 obj) {
    w.BeginObject(3);
    w.WriteField("flags"); w.BeginArray(obj.Flags.Count);
        foreach (var item in obj.Flags) { w.NextElement(); w.WriteBool(item); }
        w.EndArray();
    w.WriteField("values"); w.BeginArray(obj.Values.Count);
        foreach (var item in obj.Values) { w.NextElement(); w.WriteFloat64(item); }
        w.EndArray();
    w.WriteField("payload"); w.BeginArray(obj.Payload.Count);
        foreach (var item in obj.Payload) { w.NextElement(); w.WriteBytes(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<MultiArr2> MultiArr2Codec = new(
    Encode: (w, obj) => WriteMultiArr2(w, obj),
    Decode: r => {
        List<bool> _Flags = new List<bool>();
        List<double> _Values = new List<double>();
        List<byte[]> _Payload = new List<byte[]>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "flags": _Flags = ((Func<List<bool>>)(() => { var list = new List<bool>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadBool()); r.EndArray(); return list; }))(); break;
                case "values": _Values = ((Func<List<double>>)(() => { var list = new List<double>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadFloat64()); r.EndArray(); return list; }))(); break;
                case "payload": _Payload = ((Func<List<byte[]>>)(() => { var list = new List<byte[]>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadBytes()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new MultiArr2(Flags: _Flags, Values: _Values, Payload: _Payload);
    }
);
} // MultiArr2Methods

public record MultiArr3(
    List<string> A,
    List<int> B,
    List<double> C
);

public static class MultiArr3Methods {
public static void WriteMultiArr3(SpecWriter w, MultiArr3 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.BeginArray(obj.A.Count);
        foreach (var item in obj.A) { w.NextElement(); w.WriteString(item); }
        w.EndArray();
    w.WriteField("b"); w.BeginArray(obj.B.Count);
        foreach (var item in obj.B) { w.NextElement(); w.WriteInt32(item); }
        w.EndArray();
    w.WriteField("c"); w.BeginArray(obj.C.Count);
        foreach (var item in obj.C) { w.NextElement(); w.WriteFloat64(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<MultiArr3> MultiArr3Codec = new(
    Encode: (w, obj) => WriteMultiArr3(w, obj),
    Decode: r => {
        List<string> _A = new List<string>();
        List<int> _B = new List<int>();
        List<double> _C = new List<double>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                case "b": _B = ((Func<List<int>>)(() => { var list = new List<int>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadInt32()); r.EndArray(); return list; }))(); break;
                case "c": _C = ((Func<List<double>>)(() => { var list = new List<double>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadFloat64()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new MultiArr3(A: _A, B: _B, C: _C);
    }
);
} // MultiArr3Methods

public record MultiArr4(
    List<long> Ids,
    List<string> Tags
);

public static class MultiArr4Methods {
public static void WriteMultiArr4(SpecWriter w, MultiArr4 obj) {
    w.BeginObject(2);
    w.WriteField("ids"); w.BeginArray(obj.Ids.Count);
        foreach (var item in obj.Ids) { w.NextElement(); w.WriteInt64(item); }
        w.EndArray();
    w.WriteField("tags"); w.BeginArray(obj.Tags.Count);
        foreach (var item in obj.Tags) { w.NextElement(); w.WriteString(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<MultiArr4> MultiArr4Codec = new(
    Encode: (w, obj) => WriteMultiArr4(w, obj),
    Decode: r => {
        List<long> _Ids = new List<long>();
        List<string> _Tags = new List<string>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "ids": _Ids = ((Func<List<long>>)(() => { var list = new List<long>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadInt64()); r.EndArray(); return list; }))(); break;
                case "tags": _Tags = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new MultiArr4(Ids: _Ids, Tags: _Tags);
    }
);
} // MultiArr4Methods

public record MultiArr5(
    List<ulong> Xs,
    List<float> Ys,
    List<bool> Zs
);

public static class MultiArr5Methods {
public static void WriteMultiArr5(SpecWriter w, MultiArr5 obj) {
    w.BeginObject(3);
    w.WriteField("xs"); w.BeginArray(obj.Xs.Count);
        foreach (var item in obj.Xs) { w.NextElement(); w.WriteUint64(item); }
        w.EndArray();
    w.WriteField("ys"); w.BeginArray(obj.Ys.Count);
        foreach (var item in obj.Ys) { w.NextElement(); w.WriteFloat32(item); }
        w.EndArray();
    w.WriteField("zs"); w.BeginArray(obj.Zs.Count);
        foreach (var item in obj.Zs) { w.NextElement(); w.WriteBool(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<MultiArr5> MultiArr5Codec = new(
    Encode: (w, obj) => WriteMultiArr5(w, obj),
    Decode: r => {
        List<ulong> _Xs = new List<ulong>();
        List<float> _Ys = new List<float>();
        List<bool> _Zs = new List<bool>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "xs": _Xs = ((Func<List<ulong>>)(() => { var list = new List<ulong>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadUint64()); r.EndArray(); return list; }))(); break;
                case "ys": _Ys = ((Func<List<float>>)(() => { var list = new List<float>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadFloat32()); r.EndArray(); return list; }))(); break;
                case "zs": _Zs = ((Func<List<bool>>)(() => { var list = new List<bool>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadBool()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new MultiArr5(Xs: _Xs, Ys: _Ys, Zs: _Zs);
    }
);
} // MultiArr5Methods

public record OptCombo1(
    string Req,
    int? OptA = null
);

public static class OptCombo1Methods {
public static void WriteOptCombo1(SpecWriter w, OptCombo1 obj) {
    var fieldCount = 1;
    if (obj.OptA != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("req"); w.WriteString(obj.Req);
    if (obj.OptA != null) { w.WriteField("opt_a"); w.WriteInt32(obj.OptA.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo1> OptCombo1Codec = new(
    Encode: (w, obj) => WriteOptCombo1(w, obj),
    Decode: r => {
        string _Req = "";
        int? _OptA = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "req": _Req = r.ReadString(); break;
                case "opt_a": _OptA = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo1(Req: _Req, OptA: _OptA);
    }
);
} // OptCombo1Methods

public record OptCombo2(
    string Req,
    int? OptA = null,
    bool? OptB = null
);

public static class OptCombo2Methods {
public static void WriteOptCombo2(SpecWriter w, OptCombo2 obj) {
    var fieldCount = 1;
    if (obj.OptA != null) fieldCount++;
    if (obj.OptB != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("req"); w.WriteString(obj.Req);
    if (obj.OptA != null) { w.WriteField("opt_a"); w.WriteInt32(obj.OptA.Value); }
    if (obj.OptB != null) { w.WriteField("opt_b"); w.WriteBool(obj.OptB.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo2> OptCombo2Codec = new(
    Encode: (w, obj) => WriteOptCombo2(w, obj),
    Decode: r => {
        string _Req = "";
        int? _OptA = null;
        bool? _OptB = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "req": _Req = r.ReadString(); break;
                case "opt_a": _OptA = r.ReadInt32(); break;
                case "opt_b": _OptB = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo2(Req: _Req, OptA: _OptA, OptB: _OptB);
    }
);
} // OptCombo2Methods

public record OptCombo3(
    string Req,
    int? OptA = null,
    bool? OptB = null,
    double? OptC = null
);

public static class OptCombo3Methods {
public static void WriteOptCombo3(SpecWriter w, OptCombo3 obj) {
    var fieldCount = 1;
    if (obj.OptA != null) fieldCount++;
    if (obj.OptB != null) fieldCount++;
    if (obj.OptC != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("req"); w.WriteString(obj.Req);
    if (obj.OptA != null) { w.WriteField("opt_a"); w.WriteInt32(obj.OptA.Value); }
    if (obj.OptB != null) { w.WriteField("opt_b"); w.WriteBool(obj.OptB.Value); }
    if (obj.OptC != null) { w.WriteField("opt_c"); w.WriteFloat64(obj.OptC.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo3> OptCombo3Codec = new(
    Encode: (w, obj) => WriteOptCombo3(w, obj),
    Decode: r => {
        string _Req = "";
        int? _OptA = null;
        bool? _OptB = null;
        double? _OptC = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "req": _Req = r.ReadString(); break;
                case "opt_a": _OptA = r.ReadInt32(); break;
                case "opt_b": _OptB = r.ReadBool(); break;
                case "opt_c": _OptC = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo3(Req: _Req, OptA: _OptA, OptB: _OptB, OptC: _OptC);
    }
);
} // OptCombo3Methods

public record OptCombo4(
    int Req,
    string? OptA = null,
    byte[]? OptB = null
);

public static class OptCombo4Methods {
public static void WriteOptCombo4(SpecWriter w, OptCombo4 obj) {
    var fieldCount = 1;
    if (obj.OptA != null) fieldCount++;
    if (obj.OptB != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("req"); w.WriteInt32(obj.Req);
    if (obj.OptA != null) { w.WriteField("opt_a"); w.WriteString(obj.OptA); }
    if (obj.OptB != null) { w.WriteField("opt_b"); w.WriteBytes(obj.OptB); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo4> OptCombo4Codec = new(
    Encode: (w, obj) => WriteOptCombo4(w, obj),
    Decode: r => {
        int _Req = 0;
        string? _OptA = null;
        byte[]? _OptB = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "req": _Req = r.ReadInt32(); break;
                case "opt_a": _OptA = r.ReadString(); break;
                case "opt_b": _OptB = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo4(Req: _Req, OptA: _OptA, OptB: _OptB);
    }
);
} // OptCombo4Methods

public record OptCombo5(
    string Req1,
    int Req2,
    bool? OptA = null,
    double? OptB = null
);

public static class OptCombo5Methods {
public static void WriteOptCombo5(SpecWriter w, OptCombo5 obj) {
    var fieldCount = 2;
    if (obj.OptA != null) fieldCount++;
    if (obj.OptB != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("req1"); w.WriteString(obj.Req1);
    w.WriteField("req2"); w.WriteInt32(obj.Req2);
    if (obj.OptA != null) { w.WriteField("opt_a"); w.WriteBool(obj.OptA.Value); }
    if (obj.OptB != null) { w.WriteField("opt_b"); w.WriteFloat64(obj.OptB.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo5> OptCombo5Codec = new(
    Encode: (w, obj) => WriteOptCombo5(w, obj),
    Decode: r => {
        string _Req1 = "";
        int _Req2 = 0;
        bool? _OptA = null;
        double? _OptB = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "req1": _Req1 = r.ReadString(); break;
                case "req2": _Req2 = r.ReadInt32(); break;
                case "opt_a": _OptA = r.ReadBool(); break;
                case "opt_b": _OptB = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo5(Req1: _Req1, Req2: _Req2, OptA: _OptA, OptB: _OptB);
    }
);
} // OptCombo5Methods

public record OptCombo6(
    string Req,
    string? OptS = null,
    int? OptI = null,
    double? OptF = null,
    byte[]? OptB = null
);

public static class OptCombo6Methods {
public static void WriteOptCombo6(SpecWriter w, OptCombo6 obj) {
    var fieldCount = 1;
    if (obj.OptS != null) fieldCount++;
    if (obj.OptI != null) fieldCount++;
    if (obj.OptF != null) fieldCount++;
    if (obj.OptB != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("req"); w.WriteString(obj.Req);
    if (obj.OptS != null) { w.WriteField("opt_s"); w.WriteString(obj.OptS); }
    if (obj.OptI != null) { w.WriteField("opt_i"); w.WriteInt32(obj.OptI.Value); }
    if (obj.OptF != null) { w.WriteField("opt_f"); w.WriteFloat64(obj.OptF.Value); }
    if (obj.OptB != null) { w.WriteField("opt_b"); w.WriteBytes(obj.OptB); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo6> OptCombo6Codec = new(
    Encode: (w, obj) => WriteOptCombo6(w, obj),
    Decode: r => {
        string _Req = "";
        string? _OptS = null;
        int? _OptI = null;
        double? _OptF = null;
        byte[]? _OptB = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "req": _Req = r.ReadString(); break;
                case "opt_s": _OptS = r.ReadString(); break;
                case "opt_i": _OptI = r.ReadInt32(); break;
                case "opt_f": _OptF = r.ReadFloat64(); break;
                case "opt_b": _OptB = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo6(Req: _Req, OptS: _OptS, OptI: _OptI, OptF: _OptF, OptB: _OptB);
    }
);
} // OptCombo6Methods

public record OptCombo7(
    long Req,
    ulong? OptU64 = null,
    string? OptStr = null
);

public static class OptCombo7Methods {
public static void WriteOptCombo7(SpecWriter w, OptCombo7 obj) {
    var fieldCount = 1;
    if (obj.OptU64 != null) fieldCount++;
    if (obj.OptStr != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("req"); w.WriteInt64(obj.Req);
    if (obj.OptU64 != null) { w.WriteField("opt_u64"); w.WriteUint64(obj.OptU64.Value); }
    if (obj.OptStr != null) { w.WriteField("opt_str"); w.WriteString(obj.OptStr); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo7> OptCombo7Codec = new(
    Encode: (w, obj) => WriteOptCombo7(w, obj),
    Decode: r => {
        long _Req = 0L;
        ulong? _OptU64 = null;
        string? _OptStr = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "req": _Req = r.ReadInt64(); break;
                case "opt_u64": _OptU64 = r.ReadUint64(); break;
                case "opt_str": _OptStr = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo7(Req: _Req, OptU64: _OptU64, OptStr: _OptStr);
    }
);
} // OptCombo7Methods

public record OptCombo8(
    string A,
    int? B = null,
    double? C = null,
    bool? D = null,
    byte[]? E = null,
    long? F = null
);

public static class OptCombo8Methods {
public static void WriteOptCombo8(SpecWriter w, OptCombo8 obj) {
    var fieldCount = 1;
    if (obj.B != null) fieldCount++;
    if (obj.C != null) fieldCount++;
    if (obj.D != null) fieldCount++;
    if (obj.E != null) fieldCount++;
    if (obj.F != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("a"); w.WriteString(obj.A);
    if (obj.B != null) { w.WriteField("b"); w.WriteInt32(obj.B.Value); }
    if (obj.C != null) { w.WriteField("c"); w.WriteFloat64(obj.C.Value); }
    if (obj.D != null) { w.WriteField("d"); w.WriteBool(obj.D.Value); }
    if (obj.E != null) { w.WriteField("e"); w.WriteBytes(obj.E); }
    if (obj.F != null) { w.WriteField("f"); w.WriteInt64(obj.F.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo8> OptCombo8Codec = new(
    Encode: (w, obj) => WriteOptCombo8(w, obj),
    Decode: r => {
        string _A = "";
        int? _B = null;
        double? _C = null;
        bool? _D = null;
        byte[]? _E = null;
        long? _F = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadInt32(); break;
                case "c": _C = r.ReadFloat64(); break;
                case "d": _D = r.ReadBool(); break;
                case "e": _E = r.ReadBytes(); break;
                case "f": _F = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo8(A: _A, B: _B, C: _C, D: _D, E: _E, F: _F);
    }
);
} // OptCombo8Methods

public record OptCombo9(
    string Id,
    string? Name = null,
    int? Age = null,
    double? Score = null
);

public static class OptCombo9Methods {
public static void WriteOptCombo9(SpecWriter w, OptCombo9 obj) {
    var fieldCount = 1;
    if (obj.Name != null) fieldCount++;
    if (obj.Age != null) fieldCount++;
    if (obj.Score != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("id"); w.WriteString(obj.Id);
    if (obj.Name != null) { w.WriteField("name"); w.WriteString(obj.Name); }
    if (obj.Age != null) { w.WriteField("age"); w.WriteInt32(obj.Age.Value); }
    if (obj.Score != null) { w.WriteField("score"); w.WriteFloat64(obj.Score.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo9> OptCombo9Codec = new(
    Encode: (w, obj) => WriteOptCombo9(w, obj),
    Decode: r => {
        string _Id = "";
        string? _Name = null;
        int? _Age = null;
        double? _Score = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "id": _Id = r.ReadString(); break;
                case "name": _Name = r.ReadString(); break;
                case "age": _Age = r.ReadInt32(); break;
                case "score": _Score = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo9(Id: _Id, Name: _Name, Age: _Age, Score: _Score);
    }
);
} // OptCombo9Methods

public record OptCombo10(
    int Code,
    string? Msg = null,
    string? Detail = null,
    bool? Retry = null
);

public static class OptCombo10Methods {
public static void WriteOptCombo10(SpecWriter w, OptCombo10 obj) {
    var fieldCount = 1;
    if (obj.Msg != null) fieldCount++;
    if (obj.Detail != null) fieldCount++;
    if (obj.Retry != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("code"); w.WriteInt32(obj.Code);
    if (obj.Msg != null) { w.WriteField("msg"); w.WriteString(obj.Msg); }
    if (obj.Detail != null) { w.WriteField("detail"); w.WriteString(obj.Detail); }
    if (obj.Retry != null) { w.WriteField("retry"); w.WriteBool(obj.Retry.Value); }
    w.EndObject();
}

public static readonly SpecCodec<OptCombo10> OptCombo10Codec = new(
    Encode: (w, obj) => WriteOptCombo10(w, obj),
    Decode: r => {
        int _Code = 0;
        string? _Msg = null;
        string? _Detail = null;
        bool? _Retry = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "code": _Code = r.ReadInt32(); break;
                case "msg": _Msg = r.ReadString(); break;
                case "detail": _Detail = r.ReadString(); break;
                case "retry": _Retry = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptCombo10(Code: _Code, Msg: _Msg, Detail: _Detail, Retry: _Retry);
    }
);
} // OptCombo10Methods
