// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Recursive;

using Specodec;
using System;
using System.Collections.Generic;

public record RecList(
    int Value,
    RecList? Next = null
);

public static class RecListMethods {
public static void WriteRecList(SpecWriter w, RecList obj) {
    var fieldCount = 1;
    if (obj.Next != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("value"); w.WriteInt32(obj.Value);
    if (obj.Next != null) { w.WriteField("next"); RecListMethods.WriteRecList(w, obj.Next); }
    w.EndObject();
}

public static readonly SpecCodec<RecList> RecListCodec = new(
    Encode: (w, obj) => WriteRecList(w, obj),
    Decode: r => {
        int _Value = 0;
        RecList? _Next = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "value": _Value = r.ReadInt32(); break;
                case "next": _Next = r.IsNull() ? ((Func<RecList?>)(() => { r.ReadNull(); return null; }))() : RecListMethods.RecListCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new RecList(Value: _Value, Next: _Next);
    }
);
} // RecListMethods

public record RecTree(
    string Value,
    RecTree? LeftNode = null,
    RecTree? RightNode = null
);

public static class RecTreeMethods {
public static void WriteRecTree(SpecWriter w, RecTree obj) {
    var fieldCount = 1;
    if (obj.LeftNode != null) fieldCount++;
    if (obj.RightNode != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("value"); w.WriteString(obj.Value);
    if (obj.LeftNode != null) { w.WriteField("left_node"); RecTreeMethods.WriteRecTree(w, obj.LeftNode); }
    if (obj.RightNode != null) { w.WriteField("right_node"); RecTreeMethods.WriteRecTree(w, obj.RightNode); }
    w.EndObject();
}

public static readonly SpecCodec<RecTree> RecTreeCodec = new(
    Encode: (w, obj) => WriteRecTree(w, obj),
    Decode: r => {
        string _Value = "";
        RecTree? _LeftNode = null;
        RecTree? _RightNode = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "value": _Value = r.ReadString(); break;
                case "left_node": _LeftNode = r.IsNull() ? ((Func<RecTree?>)(() => { r.ReadNull(); return null; }))() : RecTreeMethods.RecTreeCodec.Decode(r); break;
                case "right_node": _RightNode = r.IsNull() ? ((Func<RecTree?>)(() => { r.ReadNull(); return null; }))() : RecTreeMethods.RecTreeCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new RecTree(Value: _Value, LeftNode: _LeftNode, RightNode: _RightNode);
    }
);
} // RecTreeMethods

public record RecChain(
    int Id,
    string Label,
    RecChain? Next = null
);

public static class RecChainMethods {
public static void WriteRecChain(SpecWriter w, RecChain obj) {
    var fieldCount = 2;
    if (obj.Next != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("id"); w.WriteInt32(obj.Id);
    w.WriteField("label"); w.WriteString(obj.Label);
    if (obj.Next != null) { w.WriteField("next"); RecChainMethods.WriteRecChain(w, obj.Next); }
    w.EndObject();
}

public static readonly SpecCodec<RecChain> RecChainCodec = new(
    Encode: (w, obj) => WriteRecChain(w, obj),
    Decode: r => {
        int _Id = 0;
        string _Label = "";
        RecChain? _Next = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "id": _Id = r.ReadInt32(); break;
                case "label": _Label = r.ReadString(); break;
                case "next": _Next = r.IsNull() ? ((Func<RecChain?>)(() => { r.ReadNull(); return null; }))() : RecChainMethods.RecChainCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new RecChain(Id: _Id, Label: _Label, Next: _Next);
    }
);
} // RecChainMethods

public record RecWrap(
    byte[] Payload,
    RecWrap? Nested = null
);

public static class RecWrapMethods {
public static void WriteRecWrap(SpecWriter w, RecWrap obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("payload"); w.WriteBytes(obj.Payload);
    if (obj.Nested != null) { w.WriteField("nested"); RecWrapMethods.WriteRecWrap(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<RecWrap> RecWrapCodec = new(
    Encode: (w, obj) => WriteRecWrap(w, obj),
    Decode: r => {
        byte[] _Payload = Array.Empty<byte>();
        RecWrap? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "payload": _Payload = r.ReadBytes(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<RecWrap?>)(() => { r.ReadNull(); return null; }))() : RecWrapMethods.RecWrapCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new RecWrap(Payload: _Payload, Nested: _Nested);
    }
);
} // RecWrapMethods

public record RecWide(
    int A,
    string B,
    double C,
    RecWide? Child = null
);

public static class RecWideMethods {
public static void WriteRecWide(SpecWriter w, RecWide obj) {
    var fieldCount = 3;
    if (obj.Child != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteString(obj.B);
    w.WriteField("c"); w.WriteFloat64(obj.C);
    if (obj.Child != null) { w.WriteField("child"); RecWideMethods.WriteRecWide(w, obj.Child); }
    w.EndObject();
}

public static readonly SpecCodec<RecWide> RecWideCodec = new(
    Encode: (w, obj) => WriteRecWide(w, obj),
    Decode: r => {
        int _A = 0;
        string _B = "";
        double _C = 0.0;
        RecWide? _Child = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt32(); break;
                case "b": _B = r.ReadString(); break;
                case "c": _C = r.ReadFloat64(); break;
                case "child": _Child = r.IsNull() ? ((Func<RecWide?>)(() => { r.ReadNull(); return null; }))() : RecWideMethods.RecWideCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new RecWide(A: _A, B: _B, C: _C, Child: _Child);
    }
);
} // RecWideMethods
