// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.nested;

using Specodec;
using System;
using System.Collections.Generic;

public record NestedSimple(
    string Name,
    int Value
);

public static class NestedSimpleMethods {
public static void WriteNestedSimple(SpecWriter w, NestedSimple obj) {
    w.BeginObject(2);
    w.WriteField("name"); w.WriteString(obj.Name);
    w.WriteField("value"); w.WriteInt32(obj.Value);
    w.EndObject();
}

public static readonly SpecCodec<NestedSimple> NestedSimpleCodec = new(
    Encode: (w, obj) => WriteNestedSimple(w, obj),
    Decode: r => {
        string _Name = "";
        int _Value = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "name": _Name = r.ReadString(); break;
                case "value": _Value = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestedSimple(Name: _Name, Value: _Value);
    }
);
} // NestedSimpleMethods
