// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Enums;

using Specodec;
using System;
using System.Collections.Generic;

public record EnumHolder(
    string Color,
    string Priority,
    string Status
);

public static class EnumHolderMethods {
public static void WriteEnumHolder(SpecWriter w, EnumHolder obj) {
    w.BeginObject(3);
    w.WriteField("color"); w.WriteString(obj.Color.ToString());
    w.WriteField("priority"); w.WriteString(obj.Priority.ToString());
    w.WriteField("status"); w.WriteString(obj.Status.ToString());
    w.EndObject();
}

public static readonly SpecCodec<EnumHolder> EnumHolderCodec = new(
    Encode: (w, obj) => WriteEnumHolder(w, obj),
    Decode: r => {
        string _Color = "";;
        string _Priority = "";;
        string _Status = "";;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "color": _Color = r.ReadString(); break;
                case "priority": _Priority = r.ReadString(); break;
                case "status": _Status = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EnumHolder(Color: _Color, Priority: _Priority, Status: _Status);
    }
);
} // EnumHolderMethods

public record OptEnumHolder(
    string? Color = null,
    string? Priority = null
);

public static class OptEnumHolderMethods {
public static void WriteOptEnumHolder(SpecWriter w, OptEnumHolder obj) {
    var fieldCount = 0;
    if (obj.Color != null) fieldCount++;
    if (obj.Priority != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.Color != null) { w.WriteField("color"); w.WriteString(obj.Color.ToString()); }
    if (obj.Priority != null) { w.WriteField("priority"); w.WriteString(obj.Priority.ToString()); }
    w.EndObject();
}

public static readonly SpecCodec<OptEnumHolder> OptEnumHolderCodec = new(
    Encode: (w, obj) => WriteOptEnumHolder(w, obj),
    Decode: r => {
        string? _Color = null;
        string? _Priority = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "color": _Color = r.ReadString(); break;
                case "priority": _Priority = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptEnumHolder(Color: _Color, Priority: _Priority);
    }
);
} // OptEnumHolderMethods

public record EnumArrayHolder(
    List<string> Colors
);

public static class EnumArrayHolderMethods {
public static void WriteEnumArrayHolder(SpecWriter w, EnumArrayHolder obj) {
    w.BeginObject(1);
    w.WriteField("colors"); w.BeginArray(obj.Colors.Count);
        foreach (var item in obj.Colors) { w.NextElement(); w.WriteString(item.ToString()); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<EnumArrayHolder> EnumArrayHolderCodec = new(
    Encode: (w, obj) => WriteEnumArrayHolder(w, obj),
    Decode: r => {
        List<string> _Colors = new List<string>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "colors": _Colors = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EnumArrayHolder(Colors: _Colors);
    }
);
} // EnumArrayHolderMethods

public record EnumMixedHolder(
    string Status,
    string Name,
    int Count,
    bool Active
);

public static class EnumMixedHolderMethods {
public static void WriteEnumMixedHolder(SpecWriter w, EnumMixedHolder obj) {
    w.BeginObject(4);
    w.WriteField("status"); w.WriteString(obj.Status.ToString());
    w.WriteField("name"); w.WriteString(obj.Name);
    w.WriteField("count"); w.WriteInt32(obj.Count);
    w.WriteField("active"); w.WriteBool(obj.Active);
    w.EndObject();
}

public static readonly SpecCodec<EnumMixedHolder> EnumMixedHolderCodec = new(
    Encode: (w, obj) => WriteEnumMixedHolder(w, obj),
    Decode: r => {
        string _Status = "";;
        string _Name = "";
        int _Count = 0;
        bool _Active = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "status": _Status = r.ReadString(); break;
                case "name": _Name = r.ReadString(); break;
                case "count": _Count = r.ReadInt32(); break;
                case "active": _Active = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EnumMixedHolder(Status: _Status, Name: _Name, Count: _Count, Active: _Active);
    }
);
} // EnumMixedHolderMethods
