// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Wide;

using Specodec;
using System;
using System.Collections.Generic;

public record Wide20(
    string F1,
    bool F2,
    byte F3,
    short F4,
    int F5,
    long F6,
    byte F7,
    ushort F8,
    uint F9,
    ulong F10,
    float F11,
    double F12,
    byte[] F13,
    string F14,
    bool F15,
    byte F16,
    short F17,
    int F18,
    long F19,
    byte F20
);

public static class Wide20Methods {
public static void WriteWide20(SpecWriter w, Wide20 obj) {
    w.BeginObject(20);
    w.WriteField("f1"); w.WriteString(obj.F1);
    w.WriteField("f2"); w.WriteBool(obj.F2);
    w.WriteField("f3"); w.WriteInt32((sbyte)obj.F3);
    w.WriteField("f4"); w.WriteInt32(obj.F4);
    w.WriteField("f5"); w.WriteInt32(obj.F5);
    w.WriteField("f6"); w.WriteInt64(obj.F6);
    w.WriteField("f7"); w.WriteUint32(obj.F7);
    w.WriteField("f8"); w.WriteUint32(obj.F8);
    w.WriteField("f9"); w.WriteUint32(obj.F9);
    w.WriteField("f10"); w.WriteUint64(obj.F10);
    w.WriteField("f11"); w.WriteFloat32(obj.F11);
    w.WriteField("f12"); w.WriteFloat64(obj.F12);
    w.WriteField("f13"); w.WriteBytes(obj.F13);
    w.WriteField("f14"); w.WriteString(obj.F14);
    w.WriteField("f15"); w.WriteBool(obj.F15);
    w.WriteField("f16"); w.WriteInt32((sbyte)obj.F16);
    w.WriteField("f17"); w.WriteInt32(obj.F17);
    w.WriteField("f18"); w.WriteInt32(obj.F18);
    w.WriteField("f19"); w.WriteInt64(obj.F19);
    w.WriteField("f20"); w.WriteUint32(obj.F20);
    w.EndObject();
}

public static readonly SpecCodec<Wide20> Wide20Codec = new(
    Encode: (w, obj) => WriteWide20(w, obj),
    Decode: r => {
        string _F1 = "";
        bool _F2 = false;
        byte _F3 = 0;
        short _F4 = 0;
        int _F5 = 0;
        long _F6 = 0L;
        byte _F7 = 0;
        ushort _F8 = 0;
        uint _F9 = 0u;
        ulong _F10 = 0UL;
        float _F11 = 0f;
        double _F12 = 0.0;
        byte[] _F13 = Array.Empty<byte>();
        string _F14 = "";
        bool _F15 = false;
        byte _F16 = 0;
        short _F17 = 0;
        int _F18 = 0;
        long _F19 = 0L;
        byte _F20 = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadString(); break;
                case "f2": _F2 = r.ReadBool(); break;
                case "f3": _F3 = (byte)r.ReadInt32(); break;
                case "f4": _F4 = (short)r.ReadInt32(); break;
                case "f5": _F5 = r.ReadInt32(); break;
                case "f6": _F6 = r.ReadInt64(); break;
                case "f7": _F7 = (byte)r.ReadUint32(); break;
                case "f8": _F8 = (ushort)r.ReadUint32(); break;
                case "f9": _F9 = r.ReadUint32(); break;
                case "f10": _F10 = r.ReadUint64(); break;
                case "f11": _F11 = r.ReadFloat32(); break;
                case "f12": _F12 = r.ReadFloat64(); break;
                case "f13": _F13 = r.ReadBytes(); break;
                case "f14": _F14 = r.ReadString(); break;
                case "f15": _F15 = r.ReadBool(); break;
                case "f16": _F16 = (byte)r.ReadInt32(); break;
                case "f17": _F17 = (short)r.ReadInt32(); break;
                case "f18": _F18 = r.ReadInt32(); break;
                case "f19": _F19 = r.ReadInt64(); break;
                case "f20": _F20 = (byte)r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Wide20(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10, F11: _F11, F12: _F12, F13: _F13, F14: _F14, F15: _F15, F16: _F16, F17: _F17, F18: _F18, F19: _F19, F20: _F20);
    }
);
} // Wide20Methods

public record Wide25(
    ushort F1,
    uint F2,
    ulong F3,
    float F4,
    double F5,
    byte[] F6,
    string F7,
    bool F8,
    byte F9,
    short F10,
    int F11,
    long F12,
    byte F13,
    ushort F14,
    uint F15,
    ulong F16,
    float F17,
    double F18,
    byte[] F19,
    string F20,
    bool F21,
    byte F22,
    short F23,
    int F24,
    long F25
);

public static class Wide25Methods {
public static void WriteWide25(SpecWriter w, Wide25 obj) {
    w.BeginObject(25);
    w.WriteField("f1"); w.WriteUint32(obj.F1);
    w.WriteField("f2"); w.WriteUint32(obj.F2);
    w.WriteField("f3"); w.WriteUint64(obj.F3);
    w.WriteField("f4"); w.WriteFloat32(obj.F4);
    w.WriteField("f5"); w.WriteFloat64(obj.F5);
    w.WriteField("f6"); w.WriteBytes(obj.F6);
    w.WriteField("f7"); w.WriteString(obj.F7);
    w.WriteField("f8"); w.WriteBool(obj.F8);
    w.WriteField("f9"); w.WriteInt32((sbyte)obj.F9);
    w.WriteField("f10"); w.WriteInt32(obj.F10);
    w.WriteField("f11"); w.WriteInt32(obj.F11);
    w.WriteField("f12"); w.WriteInt64(obj.F12);
    w.WriteField("f13"); w.WriteUint32(obj.F13);
    w.WriteField("f14"); w.WriteUint32(obj.F14);
    w.WriteField("f15"); w.WriteUint32(obj.F15);
    w.WriteField("f16"); w.WriteUint64(obj.F16);
    w.WriteField("f17"); w.WriteFloat32(obj.F17);
    w.WriteField("f18"); w.WriteFloat64(obj.F18);
    w.WriteField("f19"); w.WriteBytes(obj.F19);
    w.WriteField("f20"); w.WriteString(obj.F20);
    w.WriteField("f21"); w.WriteBool(obj.F21);
    w.WriteField("f22"); w.WriteInt32((sbyte)obj.F22);
    w.WriteField("f23"); w.WriteInt32(obj.F23);
    w.WriteField("f24"); w.WriteInt32(obj.F24);
    w.WriteField("f25"); w.WriteInt64(obj.F25);
    w.EndObject();
}

public static readonly SpecCodec<Wide25> Wide25Codec = new(
    Encode: (w, obj) => WriteWide25(w, obj),
    Decode: r => {
        ushort _F1 = 0;
        uint _F2 = 0u;
        ulong _F3 = 0UL;
        float _F4 = 0f;
        double _F5 = 0.0;
        byte[] _F6 = Array.Empty<byte>();
        string _F7 = "";
        bool _F8 = false;
        byte _F9 = 0;
        short _F10 = 0;
        int _F11 = 0;
        long _F12 = 0L;
        byte _F13 = 0;
        ushort _F14 = 0;
        uint _F15 = 0u;
        ulong _F16 = 0UL;
        float _F17 = 0f;
        double _F18 = 0.0;
        byte[] _F19 = Array.Empty<byte>();
        string _F20 = "";
        bool _F21 = false;
        byte _F22 = 0;
        short _F23 = 0;
        int _F24 = 0;
        long _F25 = 0L;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = (ushort)r.ReadUint32(); break;
                case "f2": _F2 = r.ReadUint32(); break;
                case "f3": _F3 = r.ReadUint64(); break;
                case "f4": _F4 = r.ReadFloat32(); break;
                case "f5": _F5 = r.ReadFloat64(); break;
                case "f6": _F6 = r.ReadBytes(); break;
                case "f7": _F7 = r.ReadString(); break;
                case "f8": _F8 = r.ReadBool(); break;
                case "f9": _F9 = (byte)r.ReadInt32(); break;
                case "f10": _F10 = (short)r.ReadInt32(); break;
                case "f11": _F11 = r.ReadInt32(); break;
                case "f12": _F12 = r.ReadInt64(); break;
                case "f13": _F13 = (byte)r.ReadUint32(); break;
                case "f14": _F14 = (ushort)r.ReadUint32(); break;
                case "f15": _F15 = r.ReadUint32(); break;
                case "f16": _F16 = r.ReadUint64(); break;
                case "f17": _F17 = r.ReadFloat32(); break;
                case "f18": _F18 = r.ReadFloat64(); break;
                case "f19": _F19 = r.ReadBytes(); break;
                case "f20": _F20 = r.ReadString(); break;
                case "f21": _F21 = r.ReadBool(); break;
                case "f22": _F22 = (byte)r.ReadInt32(); break;
                case "f23": _F23 = (short)r.ReadInt32(); break;
                case "f24": _F24 = r.ReadInt32(); break;
                case "f25": _F25 = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Wide25(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10, F11: _F11, F12: _F12, F13: _F13, F14: _F14, F15: _F15, F16: _F16, F17: _F17, F18: _F18, F19: _F19, F20: _F20, F21: _F21, F22: _F22, F23: _F23, F24: _F24, F25: _F25);
    }
);
} // Wide25Methods

public record Wide30(
    bool F1,
    byte F2,
    short F3,
    int F4,
    long F5,
    byte F6,
    ushort F7,
    uint F8,
    ulong F9,
    float F10,
    double F11,
    byte[] F12,
    string F13,
    bool F14,
    byte F15,
    short F16,
    int F17,
    long F18,
    byte F19,
    ushort F20,
    uint F21,
    ulong F22,
    float F23,
    double F24,
    byte[] F25,
    string F26,
    bool F27,
    byte F28,
    short F29,
    int F30
);

public static class Wide30Methods {
public static void WriteWide30(SpecWriter w, Wide30 obj) {
    w.BeginObject(30);
    w.WriteField("f1"); w.WriteBool(obj.F1);
    w.WriteField("f2"); w.WriteInt32((sbyte)obj.F2);
    w.WriteField("f3"); w.WriteInt32(obj.F3);
    w.WriteField("f4"); w.WriteInt32(obj.F4);
    w.WriteField("f5"); w.WriteInt64(obj.F5);
    w.WriteField("f6"); w.WriteUint32(obj.F6);
    w.WriteField("f7"); w.WriteUint32(obj.F7);
    w.WriteField("f8"); w.WriteUint32(obj.F8);
    w.WriteField("f9"); w.WriteUint64(obj.F9);
    w.WriteField("f10"); w.WriteFloat32(obj.F10);
    w.WriteField("f11"); w.WriteFloat64(obj.F11);
    w.WriteField("f12"); w.WriteBytes(obj.F12);
    w.WriteField("f13"); w.WriteString(obj.F13);
    w.WriteField("f14"); w.WriteBool(obj.F14);
    w.WriteField("f15"); w.WriteInt32((sbyte)obj.F15);
    w.WriteField("f16"); w.WriteInt32(obj.F16);
    w.WriteField("f17"); w.WriteInt32(obj.F17);
    w.WriteField("f18"); w.WriteInt64(obj.F18);
    w.WriteField("f19"); w.WriteUint32(obj.F19);
    w.WriteField("f20"); w.WriteUint32(obj.F20);
    w.WriteField("f21"); w.WriteUint32(obj.F21);
    w.WriteField("f22"); w.WriteUint64(obj.F22);
    w.WriteField("f23"); w.WriteFloat32(obj.F23);
    w.WriteField("f24"); w.WriteFloat64(obj.F24);
    w.WriteField("f25"); w.WriteBytes(obj.F25);
    w.WriteField("f26"); w.WriteString(obj.F26);
    w.WriteField("f27"); w.WriteBool(obj.F27);
    w.WriteField("f28"); w.WriteInt32((sbyte)obj.F28);
    w.WriteField("f29"); w.WriteInt32(obj.F29);
    w.WriteField("f30"); w.WriteInt32(obj.F30);
    w.EndObject();
}

public static readonly SpecCodec<Wide30> Wide30Codec = new(
    Encode: (w, obj) => WriteWide30(w, obj),
    Decode: r => {
        bool _F1 = false;
        byte _F2 = 0;
        short _F3 = 0;
        int _F4 = 0;
        long _F5 = 0L;
        byte _F6 = 0;
        ushort _F7 = 0;
        uint _F8 = 0u;
        ulong _F9 = 0UL;
        float _F10 = 0f;
        double _F11 = 0.0;
        byte[] _F12 = Array.Empty<byte>();
        string _F13 = "";
        bool _F14 = false;
        byte _F15 = 0;
        short _F16 = 0;
        int _F17 = 0;
        long _F18 = 0L;
        byte _F19 = 0;
        ushort _F20 = 0;
        uint _F21 = 0u;
        ulong _F22 = 0UL;
        float _F23 = 0f;
        double _F24 = 0.0;
        byte[] _F25 = Array.Empty<byte>();
        string _F26 = "";
        bool _F27 = false;
        byte _F28 = 0;
        short _F29 = 0;
        int _F30 = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadBool(); break;
                case "f2": _F2 = (byte)r.ReadInt32(); break;
                case "f3": _F3 = (short)r.ReadInt32(); break;
                case "f4": _F4 = r.ReadInt32(); break;
                case "f5": _F5 = r.ReadInt64(); break;
                case "f6": _F6 = (byte)r.ReadUint32(); break;
                case "f7": _F7 = (ushort)r.ReadUint32(); break;
                case "f8": _F8 = r.ReadUint32(); break;
                case "f9": _F9 = r.ReadUint64(); break;
                case "f10": _F10 = r.ReadFloat32(); break;
                case "f11": _F11 = r.ReadFloat64(); break;
                case "f12": _F12 = r.ReadBytes(); break;
                case "f13": _F13 = r.ReadString(); break;
                case "f14": _F14 = r.ReadBool(); break;
                case "f15": _F15 = (byte)r.ReadInt32(); break;
                case "f16": _F16 = (short)r.ReadInt32(); break;
                case "f17": _F17 = r.ReadInt32(); break;
                case "f18": _F18 = r.ReadInt64(); break;
                case "f19": _F19 = (byte)r.ReadUint32(); break;
                case "f20": _F20 = (ushort)r.ReadUint32(); break;
                case "f21": _F21 = r.ReadUint32(); break;
                case "f22": _F22 = r.ReadUint64(); break;
                case "f23": _F23 = r.ReadFloat32(); break;
                case "f24": _F24 = r.ReadFloat64(); break;
                case "f25": _F25 = r.ReadBytes(); break;
                case "f26": _F26 = r.ReadString(); break;
                case "f27": _F27 = r.ReadBool(); break;
                case "f28": _F28 = (byte)r.ReadInt32(); break;
                case "f29": _F29 = (short)r.ReadInt32(); break;
                case "f30": _F30 = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Wide30(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10, F11: _F11, F12: _F12, F13: _F13, F14: _F14, F15: _F15, F16: _F16, F17: _F17, F18: _F18, F19: _F19, F20: _F20, F21: _F21, F22: _F22, F23: _F23, F24: _F24, F25: _F25, F26: _F26, F27: _F27, F28: _F28, F29: _F29, F30: _F30);
    }
);
} // Wide30Methods

public record Wide35(
    uint F1,
    ulong F2,
    float F3,
    double F4,
    byte[] F5,
    string F6,
    bool F7,
    byte F8,
    short F9,
    int F10,
    long F11,
    byte F12,
    ushort F13,
    uint F14,
    ulong F15,
    float F16,
    double F17,
    byte[] F18,
    string F19,
    bool F20,
    byte F21,
    short F22,
    int F23,
    long F24,
    byte F25,
    ushort F26,
    uint F27,
    ulong F28,
    float F29,
    double F30,
    byte[] F31,
    string F32,
    bool F33,
    byte F34,
    short F35
);

public static class Wide35Methods {
public static void WriteWide35(SpecWriter w, Wide35 obj) {
    w.BeginObject(35);
    w.WriteField("f1"); w.WriteUint32(obj.F1);
    w.WriteField("f2"); w.WriteUint64(obj.F2);
    w.WriteField("f3"); w.WriteFloat32(obj.F3);
    w.WriteField("f4"); w.WriteFloat64(obj.F4);
    w.WriteField("f5"); w.WriteBytes(obj.F5);
    w.WriteField("f6"); w.WriteString(obj.F6);
    w.WriteField("f7"); w.WriteBool(obj.F7);
    w.WriteField("f8"); w.WriteInt32((sbyte)obj.F8);
    w.WriteField("f9"); w.WriteInt32(obj.F9);
    w.WriteField("f10"); w.WriteInt32(obj.F10);
    w.WriteField("f11"); w.WriteInt64(obj.F11);
    w.WriteField("f12"); w.WriteUint32(obj.F12);
    w.WriteField("f13"); w.WriteUint32(obj.F13);
    w.WriteField("f14"); w.WriteUint32(obj.F14);
    w.WriteField("f15"); w.WriteUint64(obj.F15);
    w.WriteField("f16"); w.WriteFloat32(obj.F16);
    w.WriteField("f17"); w.WriteFloat64(obj.F17);
    w.WriteField("f18"); w.WriteBytes(obj.F18);
    w.WriteField("f19"); w.WriteString(obj.F19);
    w.WriteField("f20"); w.WriteBool(obj.F20);
    w.WriteField("f21"); w.WriteInt32((sbyte)obj.F21);
    w.WriteField("f22"); w.WriteInt32(obj.F22);
    w.WriteField("f23"); w.WriteInt32(obj.F23);
    w.WriteField("f24"); w.WriteInt64(obj.F24);
    w.WriteField("f25"); w.WriteUint32(obj.F25);
    w.WriteField("f26"); w.WriteUint32(obj.F26);
    w.WriteField("f27"); w.WriteUint32(obj.F27);
    w.WriteField("f28"); w.WriteUint64(obj.F28);
    w.WriteField("f29"); w.WriteFloat32(obj.F29);
    w.WriteField("f30"); w.WriteFloat64(obj.F30);
    w.WriteField("f31"); w.WriteBytes(obj.F31);
    w.WriteField("f32"); w.WriteString(obj.F32);
    w.WriteField("f33"); w.WriteBool(obj.F33);
    w.WriteField("f34"); w.WriteInt32((sbyte)obj.F34);
    w.WriteField("f35"); w.WriteInt32(obj.F35);
    w.EndObject();
}

public static readonly SpecCodec<Wide35> Wide35Codec = new(
    Encode: (w, obj) => WriteWide35(w, obj),
    Decode: r => {
        uint _F1 = 0u;
        ulong _F2 = 0UL;
        float _F3 = 0f;
        double _F4 = 0.0;
        byte[] _F5 = Array.Empty<byte>();
        string _F6 = "";
        bool _F7 = false;
        byte _F8 = 0;
        short _F9 = 0;
        int _F10 = 0;
        long _F11 = 0L;
        byte _F12 = 0;
        ushort _F13 = 0;
        uint _F14 = 0u;
        ulong _F15 = 0UL;
        float _F16 = 0f;
        double _F17 = 0.0;
        byte[] _F18 = Array.Empty<byte>();
        string _F19 = "";
        bool _F20 = false;
        byte _F21 = 0;
        short _F22 = 0;
        int _F23 = 0;
        long _F24 = 0L;
        byte _F25 = 0;
        ushort _F26 = 0;
        uint _F27 = 0u;
        ulong _F28 = 0UL;
        float _F29 = 0f;
        double _F30 = 0.0;
        byte[] _F31 = Array.Empty<byte>();
        string _F32 = "";
        bool _F33 = false;
        byte _F34 = 0;
        short _F35 = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadUint32(); break;
                case "f2": _F2 = r.ReadUint64(); break;
                case "f3": _F3 = r.ReadFloat32(); break;
                case "f4": _F4 = r.ReadFloat64(); break;
                case "f5": _F5 = r.ReadBytes(); break;
                case "f6": _F6 = r.ReadString(); break;
                case "f7": _F7 = r.ReadBool(); break;
                case "f8": _F8 = (byte)r.ReadInt32(); break;
                case "f9": _F9 = (short)r.ReadInt32(); break;
                case "f10": _F10 = r.ReadInt32(); break;
                case "f11": _F11 = r.ReadInt64(); break;
                case "f12": _F12 = (byte)r.ReadUint32(); break;
                case "f13": _F13 = (ushort)r.ReadUint32(); break;
                case "f14": _F14 = r.ReadUint32(); break;
                case "f15": _F15 = r.ReadUint64(); break;
                case "f16": _F16 = r.ReadFloat32(); break;
                case "f17": _F17 = r.ReadFloat64(); break;
                case "f18": _F18 = r.ReadBytes(); break;
                case "f19": _F19 = r.ReadString(); break;
                case "f20": _F20 = r.ReadBool(); break;
                case "f21": _F21 = (byte)r.ReadInt32(); break;
                case "f22": _F22 = (short)r.ReadInt32(); break;
                case "f23": _F23 = r.ReadInt32(); break;
                case "f24": _F24 = r.ReadInt64(); break;
                case "f25": _F25 = (byte)r.ReadUint32(); break;
                case "f26": _F26 = (ushort)r.ReadUint32(); break;
                case "f27": _F27 = r.ReadUint32(); break;
                case "f28": _F28 = r.ReadUint64(); break;
                case "f29": _F29 = r.ReadFloat32(); break;
                case "f30": _F30 = r.ReadFloat64(); break;
                case "f31": _F31 = r.ReadBytes(); break;
                case "f32": _F32 = r.ReadString(); break;
                case "f33": _F33 = r.ReadBool(); break;
                case "f34": _F34 = (byte)r.ReadInt32(); break;
                case "f35": _F35 = (short)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Wide35(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10, F11: _F11, F12: _F12, F13: _F13, F14: _F14, F15: _F15, F16: _F16, F17: _F17, F18: _F18, F19: _F19, F20: _F20, F21: _F21, F22: _F22, F23: _F23, F24: _F24, F25: _F25, F26: _F26, F27: _F27, F28: _F28, F29: _F29, F30: _F30, F31: _F31, F32: _F32, F33: _F33, F34: _F34, F35: _F35);
    }
);
} // Wide35Methods

public record Wide40(
    byte F1,
    short F2,
    int F3,
    long F4,
    byte F5,
    ushort F6,
    uint F7,
    ulong F8,
    float F9,
    double F10,
    byte[] F11,
    string F12,
    bool F13,
    byte F14,
    short F15,
    int F16,
    long F17,
    byte F18,
    ushort F19,
    uint F20,
    ulong F21,
    float F22,
    double F23,
    byte[] F24,
    string F25,
    bool F26,
    byte F27,
    short F28,
    int F29,
    long F30,
    byte F31,
    ushort F32,
    uint F33,
    ulong F34,
    float F35,
    double F36,
    byte[] F37,
    string F38,
    bool F39,
    byte F40
);

public static class Wide40Methods {
public static void WriteWide40(SpecWriter w, Wide40 obj) {
    w.BeginObject(40);
    w.WriteField("f1"); w.WriteInt32((sbyte)obj.F1);
    w.WriteField("f2"); w.WriteInt32(obj.F2);
    w.WriteField("f3"); w.WriteInt32(obj.F3);
    w.WriteField("f4"); w.WriteInt64(obj.F4);
    w.WriteField("f5"); w.WriteUint32(obj.F5);
    w.WriteField("f6"); w.WriteUint32(obj.F6);
    w.WriteField("f7"); w.WriteUint32(obj.F7);
    w.WriteField("f8"); w.WriteUint64(obj.F8);
    w.WriteField("f9"); w.WriteFloat32(obj.F9);
    w.WriteField("f10"); w.WriteFloat64(obj.F10);
    w.WriteField("f11"); w.WriteBytes(obj.F11);
    w.WriteField("f12"); w.WriteString(obj.F12);
    w.WriteField("f13"); w.WriteBool(obj.F13);
    w.WriteField("f14"); w.WriteInt32((sbyte)obj.F14);
    w.WriteField("f15"); w.WriteInt32(obj.F15);
    w.WriteField("f16"); w.WriteInt32(obj.F16);
    w.WriteField("f17"); w.WriteInt64(obj.F17);
    w.WriteField("f18"); w.WriteUint32(obj.F18);
    w.WriteField("f19"); w.WriteUint32(obj.F19);
    w.WriteField("f20"); w.WriteUint32(obj.F20);
    w.WriteField("f21"); w.WriteUint64(obj.F21);
    w.WriteField("f22"); w.WriteFloat32(obj.F22);
    w.WriteField("f23"); w.WriteFloat64(obj.F23);
    w.WriteField("f24"); w.WriteBytes(obj.F24);
    w.WriteField("f25"); w.WriteString(obj.F25);
    w.WriteField("f26"); w.WriteBool(obj.F26);
    w.WriteField("f27"); w.WriteInt32((sbyte)obj.F27);
    w.WriteField("f28"); w.WriteInt32(obj.F28);
    w.WriteField("f29"); w.WriteInt32(obj.F29);
    w.WriteField("f30"); w.WriteInt64(obj.F30);
    w.WriteField("f31"); w.WriteUint32(obj.F31);
    w.WriteField("f32"); w.WriteUint32(obj.F32);
    w.WriteField("f33"); w.WriteUint32(obj.F33);
    w.WriteField("f34"); w.WriteUint64(obj.F34);
    w.WriteField("f35"); w.WriteFloat32(obj.F35);
    w.WriteField("f36"); w.WriteFloat64(obj.F36);
    w.WriteField("f37"); w.WriteBytes(obj.F37);
    w.WriteField("f38"); w.WriteString(obj.F38);
    w.WriteField("f39"); w.WriteBool(obj.F39);
    w.WriteField("f40"); w.WriteInt32((sbyte)obj.F40);
    w.EndObject();
}

public static readonly SpecCodec<Wide40> Wide40Codec = new(
    Encode: (w, obj) => WriteWide40(w, obj),
    Decode: r => {
        byte _F1 = 0;
        short _F2 = 0;
        int _F3 = 0;
        long _F4 = 0L;
        byte _F5 = 0;
        ushort _F6 = 0;
        uint _F7 = 0u;
        ulong _F8 = 0UL;
        float _F9 = 0f;
        double _F10 = 0.0;
        byte[] _F11 = Array.Empty<byte>();
        string _F12 = "";
        bool _F13 = false;
        byte _F14 = 0;
        short _F15 = 0;
        int _F16 = 0;
        long _F17 = 0L;
        byte _F18 = 0;
        ushort _F19 = 0;
        uint _F20 = 0u;
        ulong _F21 = 0UL;
        float _F22 = 0f;
        double _F23 = 0.0;
        byte[] _F24 = Array.Empty<byte>();
        string _F25 = "";
        bool _F26 = false;
        byte _F27 = 0;
        short _F28 = 0;
        int _F29 = 0;
        long _F30 = 0L;
        byte _F31 = 0;
        ushort _F32 = 0;
        uint _F33 = 0u;
        ulong _F34 = 0UL;
        float _F35 = 0f;
        double _F36 = 0.0;
        byte[] _F37 = Array.Empty<byte>();
        string _F38 = "";
        bool _F39 = false;
        byte _F40 = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = (byte)r.ReadInt32(); break;
                case "f2": _F2 = (short)r.ReadInt32(); break;
                case "f3": _F3 = r.ReadInt32(); break;
                case "f4": _F4 = r.ReadInt64(); break;
                case "f5": _F5 = (byte)r.ReadUint32(); break;
                case "f6": _F6 = (ushort)r.ReadUint32(); break;
                case "f7": _F7 = r.ReadUint32(); break;
                case "f8": _F8 = r.ReadUint64(); break;
                case "f9": _F9 = r.ReadFloat32(); break;
                case "f10": _F10 = r.ReadFloat64(); break;
                case "f11": _F11 = r.ReadBytes(); break;
                case "f12": _F12 = r.ReadString(); break;
                case "f13": _F13 = r.ReadBool(); break;
                case "f14": _F14 = (byte)r.ReadInt32(); break;
                case "f15": _F15 = (short)r.ReadInt32(); break;
                case "f16": _F16 = r.ReadInt32(); break;
                case "f17": _F17 = r.ReadInt64(); break;
                case "f18": _F18 = (byte)r.ReadUint32(); break;
                case "f19": _F19 = (ushort)r.ReadUint32(); break;
                case "f20": _F20 = r.ReadUint32(); break;
                case "f21": _F21 = r.ReadUint64(); break;
                case "f22": _F22 = r.ReadFloat32(); break;
                case "f23": _F23 = r.ReadFloat64(); break;
                case "f24": _F24 = r.ReadBytes(); break;
                case "f25": _F25 = r.ReadString(); break;
                case "f26": _F26 = r.ReadBool(); break;
                case "f27": _F27 = (byte)r.ReadInt32(); break;
                case "f28": _F28 = (short)r.ReadInt32(); break;
                case "f29": _F29 = r.ReadInt32(); break;
                case "f30": _F30 = r.ReadInt64(); break;
                case "f31": _F31 = (byte)r.ReadUint32(); break;
                case "f32": _F32 = (ushort)r.ReadUint32(); break;
                case "f33": _F33 = r.ReadUint32(); break;
                case "f34": _F34 = r.ReadUint64(); break;
                case "f35": _F35 = r.ReadFloat32(); break;
                case "f36": _F36 = r.ReadFloat64(); break;
                case "f37": _F37 = r.ReadBytes(); break;
                case "f38": _F38 = r.ReadString(); break;
                case "f39": _F39 = r.ReadBool(); break;
                case "f40": _F40 = (byte)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Wide40(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10, F11: _F11, F12: _F12, F13: _F13, F14: _F14, F15: _F15, F16: _F16, F17: _F17, F18: _F18, F19: _F19, F20: _F20, F21: _F21, F22: _F22, F23: _F23, F24: _F24, F25: _F25, F26: _F26, F27: _F27, F28: _F28, F29: _F29, F30: _F30, F31: _F31, F32: _F32, F33: _F33, F34: _F34, F35: _F35, F36: _F36, F37: _F37, F38: _F38, F39: _F39, F40: _F40);
    }
);
} // Wide40Methods
