// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Pairs;

using Specodec;
using System;
using System.Collections.Generic;

public record PairString(
    string A,
    string B
);

public static class PairStringMethods {
public static void WritePairString(SpecWriter w, PairString obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteString(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairString> PairStringCodec = new(
    Encode: (w, obj) => WritePairString(w, obj),
    Decode: r => {
        string _A = "";
        string _B = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairString(A: _A, B: _B);
    }
);
} // PairStringMethods

public record PairBoolean(
    bool A,
    bool B
);

public static class PairBooleanMethods {
public static void WritePairBoolean(SpecWriter w, PairBoolean obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteBool(obj.A);
    w.WriteField("b"); w.WriteBool(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairBoolean> PairBooleanCodec = new(
    Encode: (w, obj) => WritePairBoolean(w, obj),
    Decode: r => {
        bool _A = false;
        bool _B = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadBool(); break;
                case "b": _B = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairBoolean(A: _A, B: _B);
    }
);
} // PairBooleanMethods

public record PairInt8(
    byte A,
    byte B
);

public static class PairInt8Methods {
public static void WritePairInt8(SpecWriter w, PairInt8 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32((sbyte)obj.A);
    w.WriteField("b"); w.WriteInt32((sbyte)obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairInt8> PairInt8Codec = new(
    Encode: (w, obj) => WritePairInt8(w, obj),
    Decode: r => {
        byte _A = 0;
        byte _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (byte)r.ReadInt32(); break;
                case "b": _B = (byte)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairInt8(A: _A, B: _B);
    }
);
} // PairInt8Methods

public record PairInt16(
    short A,
    short B
);

public static class PairInt16Methods {
public static void WritePairInt16(SpecWriter w, PairInt16 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairInt16> PairInt16Codec = new(
    Encode: (w, obj) => WritePairInt16(w, obj),
    Decode: r => {
        short _A = 0;
        short _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (short)r.ReadInt32(); break;
                case "b": _B = (short)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairInt16(A: _A, B: _B);
    }
);
} // PairInt16Methods

public record PairInt32(
    int A,
    int B
);

public static class PairInt32Methods {
public static void WritePairInt32(SpecWriter w, PairInt32 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairInt32> PairInt32Codec = new(
    Encode: (w, obj) => WritePairInt32(w, obj),
    Decode: r => {
        int _A = 0;
        int _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt32(); break;
                case "b": _B = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairInt32(A: _A, B: _B);
    }
);
} // PairInt32Methods

public record PairInt64(
    long A,
    long B
);

public static class PairInt64Methods {
public static void WritePairInt64(SpecWriter w, PairInt64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt64(obj.A);
    w.WriteField("b"); w.WriteInt64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairInt64> PairInt64Codec = new(
    Encode: (w, obj) => WritePairInt64(w, obj),
    Decode: r => {
        long _A = 0L;
        long _B = 0L;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt64(); break;
                case "b": _B = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairInt64(A: _A, B: _B);
    }
);
} // PairInt64Methods

public record PairUint8(
    byte A,
    byte B
);

public static class PairUint8Methods {
public static void WritePairUint8(SpecWriter w, PairUint8 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteUint32(obj.A);
    w.WriteField("b"); w.WriteUint32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairUint8> PairUint8Codec = new(
    Encode: (w, obj) => WritePairUint8(w, obj),
    Decode: r => {
        byte _A = 0;
        byte _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (byte)r.ReadUint32(); break;
                case "b": _B = (byte)r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairUint8(A: _A, B: _B);
    }
);
} // PairUint8Methods

public record PairUint16(
    ushort A,
    ushort B
);

public static class PairUint16Methods {
public static void WritePairUint16(SpecWriter w, PairUint16 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteUint32(obj.A);
    w.WriteField("b"); w.WriteUint32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairUint16> PairUint16Codec = new(
    Encode: (w, obj) => WritePairUint16(w, obj),
    Decode: r => {
        ushort _A = 0;
        ushort _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (ushort)r.ReadUint32(); break;
                case "b": _B = (ushort)r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairUint16(A: _A, B: _B);
    }
);
} // PairUint16Methods

public record PairUint32(
    uint A,
    uint B
);

public static class PairUint32Methods {
public static void WritePairUint32(SpecWriter w, PairUint32 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteUint32(obj.A);
    w.WriteField("b"); w.WriteUint32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairUint32> PairUint32Codec = new(
    Encode: (w, obj) => WritePairUint32(w, obj),
    Decode: r => {
        uint _A = 0u;
        uint _B = 0u;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadUint32(); break;
                case "b": _B = r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairUint32(A: _A, B: _B);
    }
);
} // PairUint32Methods

public record PairUint64(
    ulong A,
    ulong B
);

public static class PairUint64Methods {
public static void WritePairUint64(SpecWriter w, PairUint64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteUint64(obj.A);
    w.WriteField("b"); w.WriteUint64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairUint64> PairUint64Codec = new(
    Encode: (w, obj) => WritePairUint64(w, obj),
    Decode: r => {
        ulong _A = 0UL;
        ulong _B = 0UL;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadUint64(); break;
                case "b": _B = r.ReadUint64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairUint64(A: _A, B: _B);
    }
);
} // PairUint64Methods

public record PairFloat32(
    float A,
    float B
);

public static class PairFloat32Methods {
public static void WritePairFloat32(SpecWriter w, PairFloat32 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteFloat32(obj.A);
    w.WriteField("b"); w.WriteFloat32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairFloat32> PairFloat32Codec = new(
    Encode: (w, obj) => WritePairFloat32(w, obj),
    Decode: r => {
        float _A = 0f;
        float _B = 0f;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadFloat32(); break;
                case "b": _B = r.ReadFloat32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairFloat32(A: _A, B: _B);
    }
);
} // PairFloat32Methods

public record PairFloat64(
    double A,
    double B
);

public static class PairFloat64Methods {
public static void WritePairFloat64(SpecWriter w, PairFloat64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteFloat64(obj.A);
    w.WriteField("b"); w.WriteFloat64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairFloat64> PairFloat64Codec = new(
    Encode: (w, obj) => WritePairFloat64(w, obj),
    Decode: r => {
        double _A = 0.0;
        double _B = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadFloat64(); break;
                case "b": _B = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairFloat64(A: _A, B: _B);
    }
);
} // PairFloat64Methods

public record PairBytes(
    byte[] A,
    byte[] B
);

public static class PairBytesMethods {
public static void WritePairBytes(SpecWriter w, PairBytes obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteBytes(obj.A);
    w.WriteField("b"); w.WriteBytes(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<PairBytes> PairBytesCodec = new(
    Encode: (w, obj) => WritePairBytes(w, obj),
    Decode: r => {
        byte[] _A = Array.Empty<byte>();
        byte[] _B = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadBytes(); break;
                case "b": _B = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new PairBytes(A: _A, B: _B);
    }
);
} // PairBytesMethods

public record DualStringInt32(
    string A,
    int B
);

public static class DualStringInt32Methods {
public static void WriteDualStringInt32(SpecWriter w, DualStringInt32 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualStringInt32> DualStringInt32Codec = new(
    Encode: (w, obj) => WriteDualStringInt32(w, obj),
    Decode: r => {
        string _A = "";
        int _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualStringInt32(A: _A, B: _B);
    }
);
} // DualStringInt32Methods

public record DualStringBoolean(
    string A,
    bool B
);

public static class DualStringBooleanMethods {
public static void WriteDualStringBoolean(SpecWriter w, DualStringBoolean obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteBool(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualStringBoolean> DualStringBooleanCodec = new(
    Encode: (w, obj) => WriteDualStringBoolean(w, obj),
    Decode: r => {
        string _A = "";
        bool _B = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualStringBoolean(A: _A, B: _B);
    }
);
} // DualStringBooleanMethods

public record DualStringFloat64(
    string A,
    double B
);

public static class DualStringFloat64Methods {
public static void WriteDualStringFloat64(SpecWriter w, DualStringFloat64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteFloat64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualStringFloat64> DualStringFloat64Codec = new(
    Encode: (w, obj) => WriteDualStringFloat64(w, obj),
    Decode: r => {
        string _A = "";
        double _B = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualStringFloat64(A: _A, B: _B);
    }
);
} // DualStringFloat64Methods

public record DualStringBytes(
    string A,
    byte[] B
);

public static class DualStringBytesMethods {
public static void WriteDualStringBytes(SpecWriter w, DualStringBytes obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteBytes(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualStringBytes> DualStringBytesCodec = new(
    Encode: (w, obj) => WriteDualStringBytes(w, obj),
    Decode: r => {
        string _A = "";
        byte[] _B = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualStringBytes(A: _A, B: _B);
    }
);
} // DualStringBytesMethods

public record DualInt32Boolean(
    int A,
    bool B
);

public static class DualInt32BooleanMethods {
public static void WriteDualInt32Boolean(SpecWriter w, DualInt32Boolean obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteBool(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt32Boolean> DualInt32BooleanCodec = new(
    Encode: (w, obj) => WriteDualInt32Boolean(w, obj),
    Decode: r => {
        int _A = 0;
        bool _B = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt32(); break;
                case "b": _B = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt32Boolean(A: _A, B: _B);
    }
);
} // DualInt32BooleanMethods

public record DualInt32Float64(
    int A,
    double B
);

public static class DualInt32Float64Methods {
public static void WriteDualInt32Float64(SpecWriter w, DualInt32Float64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteFloat64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt32Float64> DualInt32Float64Codec = new(
    Encode: (w, obj) => WriteDualInt32Float64(w, obj),
    Decode: r => {
        int _A = 0;
        double _B = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt32(); break;
                case "b": _B = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt32Float64(A: _A, B: _B);
    }
);
} // DualInt32Float64Methods

public record DualInt32Int64(
    int A,
    long B
);

public static class DualInt32Int64Methods {
public static void WriteDualInt32Int64(SpecWriter w, DualInt32Int64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteInt64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt32Int64> DualInt32Int64Codec = new(
    Encode: (w, obj) => WriteDualInt32Int64(w, obj),
    Decode: r => {
        int _A = 0;
        long _B = 0L;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt32(); break;
                case "b": _B = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt32Int64(A: _A, B: _B);
    }
);
} // DualInt32Int64Methods

public record DualInt32Uint32(
    int A,
    uint B
);

public static class DualInt32Uint32Methods {
public static void WriteDualInt32Uint32(SpecWriter w, DualInt32Uint32 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteUint32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt32Uint32> DualInt32Uint32Codec = new(
    Encode: (w, obj) => WriteDualInt32Uint32(w, obj),
    Decode: r => {
        int _A = 0;
        uint _B = 0u;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt32(); break;
                case "b": _B = r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt32Uint32(A: _A, B: _B);
    }
);
} // DualInt32Uint32Methods

public record DualInt64Uint64(
    long A,
    ulong B
);

public static class DualInt64Uint64Methods {
public static void WriteDualInt64Uint64(SpecWriter w, DualInt64Uint64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt64(obj.A);
    w.WriteField("b"); w.WriteUint64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt64Uint64> DualInt64Uint64Codec = new(
    Encode: (w, obj) => WriteDualInt64Uint64(w, obj),
    Decode: r => {
        long _A = 0L;
        ulong _B = 0UL;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt64(); break;
                case "b": _B = r.ReadUint64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt64Uint64(A: _A, B: _B);
    }
);
} // DualInt64Uint64Methods

public record DualFloat32Float64(
    float A,
    double B
);

public static class DualFloat32Float64Methods {
public static void WriteDualFloat32Float64(SpecWriter w, DualFloat32Float64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteFloat32(obj.A);
    w.WriteField("b"); w.WriteFloat64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualFloat32Float64> DualFloat32Float64Codec = new(
    Encode: (w, obj) => WriteDualFloat32Float64(w, obj),
    Decode: r => {
        float _A = 0f;
        double _B = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadFloat32(); break;
                case "b": _B = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualFloat32Float64(A: _A, B: _B);
    }
);
} // DualFloat32Float64Methods

public record DualFloat64Boolean(
    double A,
    bool B
);

public static class DualFloat64BooleanMethods {
public static void WriteDualFloat64Boolean(SpecWriter w, DualFloat64Boolean obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteFloat64(obj.A);
    w.WriteField("b"); w.WriteBool(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualFloat64Boolean> DualFloat64BooleanCodec = new(
    Encode: (w, obj) => WriteDualFloat64Boolean(w, obj),
    Decode: r => {
        double _A = 0.0;
        bool _B = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadFloat64(); break;
                case "b": _B = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualFloat64Boolean(A: _A, B: _B);
    }
);
} // DualFloat64BooleanMethods

public record DualFloat64Bytes(
    double A,
    byte[] B
);

public static class DualFloat64BytesMethods {
public static void WriteDualFloat64Bytes(SpecWriter w, DualFloat64Bytes obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteFloat64(obj.A);
    w.WriteField("b"); w.WriteBytes(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualFloat64Bytes> DualFloat64BytesCodec = new(
    Encode: (w, obj) => WriteDualFloat64Bytes(w, obj),
    Decode: r => {
        double _A = 0.0;
        byte[] _B = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadFloat64(); break;
                case "b": _B = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualFloat64Bytes(A: _A, B: _B);
    }
);
} // DualFloat64BytesMethods

public record DualUint32Uint64(
    uint A,
    ulong B
);

public static class DualUint32Uint64Methods {
public static void WriteDualUint32Uint64(SpecWriter w, DualUint32Uint64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteUint32(obj.A);
    w.WriteField("b"); w.WriteUint64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualUint32Uint64> DualUint32Uint64Codec = new(
    Encode: (w, obj) => WriteDualUint32Uint64(w, obj),
    Decode: r => {
        uint _A = 0u;
        ulong _B = 0UL;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadUint32(); break;
                case "b": _B = r.ReadUint64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualUint32Uint64(A: _A, B: _B);
    }
);
} // DualUint32Uint64Methods

public record DualBooleanBytes(
    bool A,
    byte[] B
);

public static class DualBooleanBytesMethods {
public static void WriteDualBooleanBytes(SpecWriter w, DualBooleanBytes obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteBool(obj.A);
    w.WriteField("b"); w.WriteBytes(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualBooleanBytes> DualBooleanBytesCodec = new(
    Encode: (w, obj) => WriteDualBooleanBytes(w, obj),
    Decode: r => {
        bool _A = false;
        byte[] _B = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadBool(); break;
                case "b": _B = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualBooleanBytes(A: _A, B: _B);
    }
);
} // DualBooleanBytesMethods

public record DualInt8Uint8(
    byte A,
    byte B
);

public static class DualInt8Uint8Methods {
public static void WriteDualInt8Uint8(SpecWriter w, DualInt8Uint8 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32((sbyte)obj.A);
    w.WriteField("b"); w.WriteUint32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt8Uint8> DualInt8Uint8Codec = new(
    Encode: (w, obj) => WriteDualInt8Uint8(w, obj),
    Decode: r => {
        byte _A = 0;
        byte _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (byte)r.ReadInt32(); break;
                case "b": _B = (byte)r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt8Uint8(A: _A, B: _B);
    }
);
} // DualInt8Uint8Methods

public record DualInt16Uint16(
    short A,
    ushort B
);

public static class DualInt16Uint16Methods {
public static void WriteDualInt16Uint16(SpecWriter w, DualInt16Uint16 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteUint32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt16Uint16> DualInt16Uint16Codec = new(
    Encode: (w, obj) => WriteDualInt16Uint16(w, obj),
    Decode: r => {
        short _A = 0;
        ushort _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (short)r.ReadInt32(); break;
                case "b": _B = (ushort)r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt16Uint16(A: _A, B: _B);
    }
);
} // DualInt16Uint16Methods

public record DualStringInt64(
    string A,
    long B
);

public static class DualStringInt64Methods {
public static void WriteDualStringInt64(SpecWriter w, DualStringInt64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteInt64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualStringInt64> DualStringInt64Codec = new(
    Encode: (w, obj) => WriteDualStringInt64(w, obj),
    Decode: r => {
        string _A = "";
        long _B = 0L;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualStringInt64(A: _A, B: _B);
    }
);
} // DualStringInt64Methods

public record DualStringUint64(
    string A,
    ulong B
);

public static class DualStringUint64Methods {
public static void WriteDualStringUint64(SpecWriter w, DualStringUint64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteUint64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualStringUint64> DualStringUint64Codec = new(
    Encode: (w, obj) => WriteDualStringUint64(w, obj),
    Decode: r => {
        string _A = "";
        ulong _B = 0UL;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadUint64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualStringUint64(A: _A, B: _B);
    }
);
} // DualStringUint64Methods

public record DualInt32Bytes(
    int A,
    byte[] B
);

public static class DualInt32BytesMethods {
public static void WriteDualInt32Bytes(SpecWriter w, DualInt32Bytes obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteBytes(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt32Bytes> DualInt32BytesCodec = new(
    Encode: (w, obj) => WriteDualInt32Bytes(w, obj),
    Decode: r => {
        int _A = 0;
        byte[] _B = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt32(); break;
                case "b": _B = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt32Bytes(A: _A, B: _B);
    }
);
} // DualInt32BytesMethods

public record DualFloat64Int32(
    double A,
    int B
);

public static class DualFloat64Int32Methods {
public static void WriteDualFloat64Int32(SpecWriter w, DualFloat64Int32 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteFloat64(obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualFloat64Int32> DualFloat64Int32Codec = new(
    Encode: (w, obj) => WriteDualFloat64Int32(w, obj),
    Decode: r => {
        double _A = 0.0;
        int _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadFloat64(); break;
                case "b": _B = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualFloat64Int32(A: _A, B: _B);
    }
);
} // DualFloat64Int32Methods

public record DualBooleanInt32(
    bool A,
    int B
);

public static class DualBooleanInt32Methods {
public static void WriteDualBooleanInt32(SpecWriter w, DualBooleanInt32 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteBool(obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualBooleanInt32> DualBooleanInt32Codec = new(
    Encode: (w, obj) => WriteDualBooleanInt32(w, obj),
    Decode: r => {
        bool _A = false;
        int _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadBool(); break;
                case "b": _B = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualBooleanInt32(A: _A, B: _B);
    }
);
} // DualBooleanInt32Methods

public record DualBytesInt64(
    byte[] A,
    long B
);

public static class DualBytesInt64Methods {
public static void WriteDualBytesInt64(SpecWriter w, DualBytesInt64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteBytes(obj.A);
    w.WriteField("b"); w.WriteInt64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualBytesInt64> DualBytesInt64Codec = new(
    Encode: (w, obj) => WriteDualBytesInt64(w, obj),
    Decode: r => {
        byte[] _A = Array.Empty<byte>();
        long _B = 0L;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadBytes(); break;
                case "b": _B = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualBytesInt64(A: _A, B: _B);
    }
);
} // DualBytesInt64Methods

public record DualInt8Float32(
    byte A,
    float B
);

public static class DualInt8Float32Methods {
public static void WriteDualInt8Float32(SpecWriter w, DualInt8Float32 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt32((sbyte)obj.A);
    w.WriteField("b"); w.WriteFloat32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt8Float32> DualInt8Float32Codec = new(
    Encode: (w, obj) => WriteDualInt8Float32(w, obj),
    Decode: r => {
        byte _A = 0;
        float _B = 0f;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (byte)r.ReadInt32(); break;
                case "b": _B = r.ReadFloat32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt8Float32(A: _A, B: _B);
    }
);
} // DualInt8Float32Methods

public record DualUint8Int16(
    byte A,
    short B
);

public static class DualUint8Int16Methods {
public static void WriteDualUint8Int16(SpecWriter w, DualUint8Int16 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteUint32(obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualUint8Int16> DualUint8Int16Codec = new(
    Encode: (w, obj) => WriteDualUint8Int16(w, obj),
    Decode: r => {
        byte _A = 0;
        short _B = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (byte)r.ReadUint32(); break;
                case "b": _B = (short)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualUint8Int16(A: _A, B: _B);
    }
);
} // DualUint8Int16Methods

public record DualInt64Float64(
    long A,
    double B
);

public static class DualInt64Float64Methods {
public static void WriteDualInt64Float64(SpecWriter w, DualInt64Float64 obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteInt64(obj.A);
    w.WriteField("b"); w.WriteFloat64(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualInt64Float64> DualInt64Float64Codec = new(
    Encode: (w, obj) => WriteDualInt64Float64(w, obj),
    Decode: r => {
        long _A = 0L;
        double _B = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt64(); break;
                case "b": _B = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualInt64Float64(A: _A, B: _B);
    }
);
} // DualInt64Float64Methods

public record DualUint64String(
    ulong A,
    string B
);

public static class DualUint64StringMethods {
public static void WriteDualUint64String(SpecWriter w, DualUint64String obj) {
    w.BeginObject(2);
    w.WriteField("a"); w.WriteUint64(obj.A);
    w.WriteField("b"); w.WriteString(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<DualUint64String> DualUint64StringCodec = new(
    Encode: (w, obj) => WriteDualUint64String(w, obj),
    Decode: r => {
        ulong _A = 0UL;
        string _B = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadUint64(); break;
                case "b": _B = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new DualUint64String(A: _A, B: _B);
    }
);
} // DualUint64StringMethods

public record Triple01(
    string A,
    int B,
    bool C
);

public static class Triple01Methods {
public static void WriteTriple01(SpecWriter w, Triple01 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.WriteField("c"); w.WriteBool(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple01> Triple01Codec = new(
    Encode: (w, obj) => WriteTriple01(w, obj),
    Decode: r => {
        string _A = "";
        int _B = 0;
        bool _C = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadInt32(); break;
                case "c": _C = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple01(A: _A, B: _B, C: _C);
    }
);
} // Triple01Methods

public record Triple02(
    double A,
    double B,
    double C
);

public static class Triple02Methods {
public static void WriteTriple02(SpecWriter w, Triple02 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteFloat64(obj.A);
    w.WriteField("b"); w.WriteFloat64(obj.B);
    w.WriteField("c"); w.WriteFloat64(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple02> Triple02Codec = new(
    Encode: (w, obj) => WriteTriple02(w, obj),
    Decode: r => {
        double _A = 0.0;
        double _B = 0.0;
        double _C = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadFloat64(); break;
                case "b": _B = r.ReadFloat64(); break;
                case "c": _C = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple02(A: _A, B: _B, C: _C);
    }
);
} // Triple02Methods

public record Triple03(
    int A,
    int B,
    int C
);

public static class Triple03Methods {
public static void WriteTriple03(SpecWriter w, Triple03 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.WriteField("c"); w.WriteInt32(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple03> Triple03Codec = new(
    Encode: (w, obj) => WriteTriple03(w, obj),
    Decode: r => {
        int _A = 0;
        int _B = 0;
        int _C = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt32(); break;
                case "b": _B = r.ReadInt32(); break;
                case "c": _C = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple03(A: _A, B: _B, C: _C);
    }
);
} // Triple03Methods

public record Triple04(
    string A,
    string B,
    int C
);

public static class Triple04Methods {
public static void WriteTriple04(SpecWriter w, Triple04 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteString(obj.B);
    w.WriteField("c"); w.WriteInt32(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple04> Triple04Codec = new(
    Encode: (w, obj) => WriteTriple04(w, obj),
    Decode: r => {
        string _A = "";
        string _B = "";
        int _C = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadString(); break;
                case "c": _C = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple04(A: _A, B: _B, C: _C);
    }
);
} // Triple04Methods

public record Triple05(
    long A,
    string B,
    bool C
);

public static class Triple05Methods {
public static void WriteTriple05(SpecWriter w, Triple05 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteInt64(obj.A);
    w.WriteField("b"); w.WriteString(obj.B);
    w.WriteField("c"); w.WriteBool(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple05> Triple05Codec = new(
    Encode: (w, obj) => WriteTriple05(w, obj),
    Decode: r => {
        long _A = 0L;
        string _B = "";
        bool _C = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt64(); break;
                case "b": _B = r.ReadString(); break;
                case "c": _C = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple05(A: _A, B: _B, C: _C);
    }
);
} // Triple05Methods

public record Triple06(
    uint A,
    ulong B,
    string C
);

public static class Triple06Methods {
public static void WriteTriple06(SpecWriter w, Triple06 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteUint32(obj.A);
    w.WriteField("b"); w.WriteUint64(obj.B);
    w.WriteField("c"); w.WriteString(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple06> Triple06Codec = new(
    Encode: (w, obj) => WriteTriple06(w, obj),
    Decode: r => {
        uint _A = 0u;
        ulong _B = 0UL;
        string _C = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadUint32(); break;
                case "b": _B = r.ReadUint64(); break;
                case "c": _C = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple06(A: _A, B: _B, C: _C);
    }
);
} // Triple06Methods

public record Triple07(
    byte[] A,
    string B,
    int C
);

public static class Triple07Methods {
public static void WriteTriple07(SpecWriter w, Triple07 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteBytes(obj.A);
    w.WriteField("b"); w.WriteString(obj.B);
    w.WriteField("c"); w.WriteInt32(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple07> Triple07Codec = new(
    Encode: (w, obj) => WriteTriple07(w, obj),
    Decode: r => {
        byte[] _A = Array.Empty<byte>();
        string _B = "";
        int _C = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadBytes(); break;
                case "b": _B = r.ReadString(); break;
                case "c": _C = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple07(A: _A, B: _B, C: _C);
    }
);
} // Triple07Methods

public record Triple08(
    float A,
    int B,
    bool C
);

public static class Triple08Methods {
public static void WriteTriple08(SpecWriter w, Triple08 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteFloat32(obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.WriteField("c"); w.WriteBool(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple08> Triple08Codec = new(
    Encode: (w, obj) => WriteTriple08(w, obj),
    Decode: r => {
        float _A = 0f;
        int _B = 0;
        bool _C = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadFloat32(); break;
                case "b": _B = r.ReadInt32(); break;
                case "c": _C = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple08(A: _A, B: _B, C: _C);
    }
);
} // Triple08Methods

public record Triple09(
    string A,
    long B,
    double C
);

public static class Triple09Methods {
public static void WriteTriple09(SpecWriter w, Triple09 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteInt64(obj.B);
    w.WriteField("c"); w.WriteFloat64(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple09> Triple09Codec = new(
    Encode: (w, obj) => WriteTriple09(w, obj),
    Decode: r => {
        string _A = "";
        long _B = 0L;
        double _C = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadInt64(); break;
                case "c": _C = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple09(A: _A, B: _B, C: _C);
    }
);
} // Triple09Methods

public record Triple10(
    bool A,
    bool B,
    bool C
);

public static class Triple10Methods {
public static void WriteTriple10(SpecWriter w, Triple10 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteBool(obj.A);
    w.WriteField("b"); w.WriteBool(obj.B);
    w.WriteField("c"); w.WriteBool(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple10> Triple10Codec = new(
    Encode: (w, obj) => WriteTriple10(w, obj),
    Decode: r => {
        bool _A = false;
        bool _B = false;
        bool _C = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadBool(); break;
                case "b": _B = r.ReadBool(); break;
                case "c": _C = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple10(A: _A, B: _B, C: _C);
    }
);
} // Triple10Methods

public record Triple11(
    byte A,
    short B,
    int C
);

public static class Triple11Methods {
public static void WriteTriple11(SpecWriter w, Triple11 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteInt32((sbyte)obj.A);
    w.WriteField("b"); w.WriteInt32(obj.B);
    w.WriteField("c"); w.WriteInt32(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple11> Triple11Codec = new(
    Encode: (w, obj) => WriteTriple11(w, obj),
    Decode: r => {
        byte _A = 0;
        short _B = 0;
        int _C = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (byte)r.ReadInt32(); break;
                case "b": _B = (short)r.ReadInt32(); break;
                case "c": _C = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple11(A: _A, B: _B, C: _C);
    }
);
} // Triple11Methods

public record Triple12(
    byte A,
    ushort B,
    uint C
);

public static class Triple12Methods {
public static void WriteTriple12(SpecWriter w, Triple12 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteUint32(obj.A);
    w.WriteField("b"); w.WriteUint32(obj.B);
    w.WriteField("c"); w.WriteUint32(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple12> Triple12Codec = new(
    Encode: (w, obj) => WriteTriple12(w, obj),
    Decode: r => {
        byte _A = 0;
        ushort _B = 0;
        uint _C = 0u;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = (byte)r.ReadUint32(); break;
                case "b": _B = (ushort)r.ReadUint32(); break;
                case "c": _C = r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple12(A: _A, B: _B, C: _C);
    }
);
} // Triple12Methods

public record Triple13(
    string A,
    byte[] B,
    double C
);

public static class Triple13Methods {
public static void WriteTriple13(SpecWriter w, Triple13 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteString(obj.A);
    w.WriteField("b"); w.WriteBytes(obj.B);
    w.WriteField("c"); w.WriteFloat64(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple13> Triple13Codec = new(
    Encode: (w, obj) => WriteTriple13(w, obj),
    Decode: r => {
        string _A = "";
        byte[] _B = Array.Empty<byte>();
        double _C = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadBytes(); break;
                case "c": _C = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple13(A: _A, B: _B, C: _C);
    }
);
} // Triple13Methods

public record Triple14(
    long A,
    ulong B,
    bool C
);

public static class Triple14Methods {
public static void WriteTriple14(SpecWriter w, Triple14 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteInt64(obj.A);
    w.WriteField("b"); w.WriteUint64(obj.B);
    w.WriteField("c"); w.WriteBool(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple14> Triple14Codec = new(
    Encode: (w, obj) => WriteTriple14(w, obj),
    Decode: r => {
        long _A = 0L;
        ulong _B = 0UL;
        bool _C = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt64(); break;
                case "b": _B = r.ReadUint64(); break;
                case "c": _C = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple14(A: _A, B: _B, C: _C);
    }
);
} // Triple14Methods

public record Triple15(
    double A,
    string B,
    byte[] C
);

public static class Triple15Methods {
public static void WriteTriple15(SpecWriter w, Triple15 obj) {
    w.BeginObject(3);
    w.WriteField("a"); w.WriteFloat64(obj.A);
    w.WriteField("b"); w.WriteString(obj.B);
    w.WriteField("c"); w.WriteBytes(obj.C);
    w.EndObject();
}

public static readonly SpecCodec<Triple15> Triple15Codec = new(
    Encode: (w, obj) => WriteTriple15(w, obj),
    Decode: r => {
        double _A = 0.0;
        string _B = "";
        byte[] _C = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadFloat64(); break;
                case "b": _B = r.ReadString(); break;
                case "c": _C = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Triple15(A: _A, B: _B, C: _C);
    }
);
} // Triple15Methods
