// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Mixed;

using Specodec;
using System;
using System.Collections.Generic;

public record ModelArr1(
    List<Inner> Points
);

public static class ModelArr1Methods {
public static void WriteModelArr1(SpecWriter w, ModelArr1 obj) {
    w.BeginObject(1);
    w.WriteField("points"); w.BeginArray(obj.Points.Count);
        foreach (var item in obj.Points) { w.NextElement(); InnerMethods.WriteInner(w, item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ModelArr1> ModelArr1Codec = new(
    Encode: (w, obj) => WriteModelArr1(w, obj),
    Decode: r => {
        List<Inner> _Points = new List<Inner>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "points": _Points = ((Func<List<Inner>>)(() => { var list = new List<Inner>(); r.BeginArray(); while (r.HasNextElement()) list.Add(InnerMethods.InnerCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ModelArr1(Points: _Points);
    }
);
} // ModelArr1Methods

public record ModelArr2(
    List<Coord> Coords
);

public static class ModelArr2Methods {
public static void WriteModelArr2(SpecWriter w, ModelArr2 obj) {
    w.BeginObject(1);
    w.WriteField("coords"); w.BeginArray(obj.Coords.Count);
        foreach (var item in obj.Coords) { w.NextElement(); CoordMethods.WriteCoord(w, item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ModelArr2> ModelArr2Codec = new(
    Encode: (w, obj) => WriteModelArr2(w, obj),
    Decode: r => {
        List<Coord> _Coords = new List<Coord>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "coords": _Coords = ((Func<List<Coord>>)(() => { var list = new List<Coord>(); r.BeginArray(); while (r.HasNextElement()) list.Add(CoordMethods.CoordCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ModelArr2(Coords: _Coords);
    }
);
} // ModelArr2Methods

public record ModelArr3(
    List<IdVal> Items,
    string Tag
);

public static class ModelArr3Methods {
public static void WriteModelArr3(SpecWriter w, ModelArr3 obj) {
    w.BeginObject(2);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); IdValMethods.WriteIdVal(w, item); }
        w.EndArray();
    w.WriteField("tag"); w.WriteString(obj.Tag);
    w.EndObject();
}

public static readonly SpecCodec<ModelArr3> ModelArr3Codec = new(
    Encode: (w, obj) => WriteModelArr3(w, obj),
    Decode: r => {
        List<IdVal> _Items = new List<IdVal>();
        string _Tag = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<IdVal>>)(() => { var list = new List<IdVal>(); r.BeginArray(); while (r.HasNextElement()) list.Add(IdValMethods.IdValCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                case "tag": _Tag = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ModelArr3(Items: _Items, Tag: _Tag);
    }
);
} // ModelArr3Methods

public record ModelArr4(
    List<Label> Labels,
    int Count
);

public static class ModelArr4Methods {
public static void WriteModelArr4(SpecWriter w, ModelArr4 obj) {
    w.BeginObject(2);
    w.WriteField("labels"); w.BeginArray(obj.Labels.Count);
        foreach (var item in obj.Labels) { w.NextElement(); LabelMethods.WriteLabel(w, item); }
        w.EndArray();
    w.WriteField("count"); w.WriteInt32(obj.Count);
    w.EndObject();
}

public static readonly SpecCodec<ModelArr4> ModelArr4Codec = new(
    Encode: (w, obj) => WriteModelArr4(w, obj),
    Decode: r => {
        List<Label> _Labels = new List<Label>();
        int _Count = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "labels": _Labels = ((Func<List<Label>>)(() => { var list = new List<Label>(); r.BeginArray(); while (r.HasNextElement()) list.Add(LabelMethods.LabelCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                case "count": _Count = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ModelArr4(Labels: _Labels, Count: _Count);
    }
);
} // ModelArr4Methods

public record ModelArr5(
    List<Money> Arr,
    List<Addr> Bs
);

public static class ModelArr5Methods {
public static void WriteModelArr5(SpecWriter w, ModelArr5 obj) {
    w.BeginObject(2);
    w.WriteField("arr"); w.BeginArray(obj.Arr.Count);
        foreach (var item in obj.Arr) { w.NextElement(); MoneyMethods.WriteMoney(w, item); }
        w.EndArray();
    w.WriteField("bs"); w.BeginArray(obj.Bs.Count);
        foreach (var item in obj.Bs) { w.NextElement(); AddrMethods.WriteAddr(w, item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<ModelArr5> ModelArr5Codec = new(
    Encode: (w, obj) => WriteModelArr5(w, obj),
    Decode: r => {
        List<Money> _Arr = new List<Money>();
        List<Addr> _Bs = new List<Addr>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "arr": _Arr = ((Func<List<Money>>)(() => { var list = new List<Money>(); r.BeginArray(); while (r.HasNextElement()) list.Add(MoneyMethods.MoneyCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                case "bs": _Bs = ((Func<List<Addr>>)(() => { var list = new List<Addr>(); r.BeginArray(); while (r.HasNextElement()) list.Add(AddrMethods.AddrCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new ModelArr5(Arr: _Arr, Bs: _Bs);
    }
);
} // ModelArr5Methods

public record Mix01(
    string Name,
    int Value,
    Inner Point
);

public static class Mix01Methods {
public static void WriteMix01(SpecWriter w, Mix01 obj) {
    w.BeginObject(3);
    w.WriteField("name"); w.WriteString(obj.Name);
    w.WriteField("value"); w.WriteInt32(obj.Value);
    w.WriteField("point"); InnerMethods.WriteInner(w, obj.Point);
    w.EndObject();
}

public static readonly SpecCodec<Mix01> Mix01Codec = new(
    Encode: (w, obj) => WriteMix01(w, obj),
    Decode: r => {
        string _Name = "";
        int _Value = 0;
        Inner? _Point = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "name": _Name = r.ReadString(); break;
                case "value": _Value = r.ReadInt32(); break;
                case "point": _Point = InnerMethods.InnerCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix01(Name: _Name, Value: _Value, Point: _Point!);
    }
);
} // Mix01Methods

public record Mix02(
    string Id,
    Coord Loc,
    List<string> Tags
);

public static class Mix02Methods {
public static void WriteMix02(SpecWriter w, Mix02 obj) {
    w.BeginObject(3);
    w.WriteField("id"); w.WriteString(obj.Id);
    w.WriteField("loc"); CoordMethods.WriteCoord(w, obj.Loc);
    w.WriteField("tags"); w.BeginArray(obj.Tags.Count);
        foreach (var item in obj.Tags) { w.NextElement(); w.WriteString(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<Mix02> Mix02Codec = new(
    Encode: (w, obj) => WriteMix02(w, obj),
    Decode: r => {
        string _Id = "";
        Coord? _Loc = null;
        List<string> _Tags = new List<string>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "id": _Id = r.ReadString(); break;
                case "loc": _Loc = CoordMethods.CoordCodec.Decode(r); break;
                case "tags": _Tags = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix02(Id: _Id, Loc: _Loc!, Tags: _Tags);
    }
);
} // Mix02Methods

public record Mix03(
    string Label,
    Range32 ValueRange,
    bool Active
);

public static class Mix03Methods {
public static void WriteMix03(SpecWriter w, Mix03 obj) {
    w.BeginObject(3);
    w.WriteField("label"); w.WriteString(obj.Label);
    w.WriteField("value_range"); Range32Methods.WriteRange32(w, obj.ValueRange);
    w.WriteField("active"); w.WriteBool(obj.Active);
    w.EndObject();
}

public static readonly SpecCodec<Mix03> Mix03Codec = new(
    Encode: (w, obj) => WriteMix03(w, obj),
    Decode: r => {
        string _Label = "";
        Range32? _ValueRange = null;
        bool _Active = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "value_range": _ValueRange = Range32Methods.Range32Codec.Decode(r); break;
                case "active": _Active = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix03(Label: _Label, ValueRange: _ValueRange!, Active: _Active);
    }
);
} // Mix03Methods

public record Mix04(
    string Title,
    Money Price,
    bool InStock,
    double Rating
);

public static class Mix04Methods {
public static void WriteMix04(SpecWriter w, Mix04 obj) {
    w.BeginObject(4);
    w.WriteField("title"); w.WriteString(obj.Title);
    w.WriteField("price"); MoneyMethods.WriteMoney(w, obj.Price);
    w.WriteField("inStock"); w.WriteBool(obj.InStock);
    w.WriteField("rating"); w.WriteFloat64(obj.Rating);
    w.EndObject();
}

public static readonly SpecCodec<Mix04> Mix04Codec = new(
    Encode: (w, obj) => WriteMix04(w, obj),
    Decode: r => {
        string _Title = "";
        Money? _Price = null;
        bool _InStock = false;
        double _Rating = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "title": _Title = r.ReadString(); break;
                case "price": _Price = MoneyMethods.MoneyCodec.Decode(r); break;
                case "inStock": _InStock = r.ReadBool(); break;
                case "rating": _Rating = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix04(Title: _Title, Price: _Price!, InStock: _InStock, Rating: _Rating);
    }
);
} // Mix04Methods

public record Mix05(
    Addr Addr,
    List<Coord> Coords
);

public static class Mix05Methods {
public static void WriteMix05(SpecWriter w, Mix05 obj) {
    w.BeginObject(2);
    w.WriteField("addr"); AddrMethods.WriteAddr(w, obj.Addr);
    w.WriteField("coords"); w.BeginArray(obj.Coords.Count);
        foreach (var item in obj.Coords) { w.NextElement(); CoordMethods.WriteCoord(w, item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<Mix05> Mix05Codec = new(
    Encode: (w, obj) => WriteMix05(w, obj),
    Decode: r => {
        Addr? _Addr = null;
        List<Coord> _Coords = new List<Coord>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "addr": _Addr = AddrMethods.AddrCodec.Decode(r); break;
                case "coords": _Coords = ((Func<List<Coord>>)(() => { var list = new List<Coord>(); r.BeginArray(); while (r.HasNextElement()) list.Add(CoordMethods.CoordCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix05(Addr: _Addr!, Coords: _Coords);
    }
);
} // Mix05Methods

public record Mix06(
    string Name,
    int Age,
    Addr? Address = null,
    string? Email = null
);

public static class Mix06Methods {
public static void WriteMix06(SpecWriter w, Mix06 obj) {
    var fieldCount = 2;
    if (obj.Address != null) fieldCount++;
    if (obj.Email != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("name"); w.WriteString(obj.Name);
    w.WriteField("age"); w.WriteInt32(obj.Age);
    if (obj.Address != null) { w.WriteField("address"); AddrMethods.WriteAddr(w, obj.Address); }
    if (obj.Email != null) { w.WriteField("email"); w.WriteString(obj.Email); }
    w.EndObject();
}

public static readonly SpecCodec<Mix06> Mix06Codec = new(
    Encode: (w, obj) => WriteMix06(w, obj),
    Decode: r => {
        string _Name = "";
        int _Age = 0;
        Addr? _Address = null;
        string? _Email = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "name": _Name = r.ReadString(); break;
                case "age": _Age = r.ReadInt32(); break;
                case "address": _Address = r.IsNull() ? ((Func<Addr?>)(() => { r.ReadNull(); return null; }))() : AddrMethods.AddrCodec.Decode(r); break;
                case "email": _Email = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix06(Name: _Name, Age: _Age, Address: _Address, Email: _Email);
    }
);
} // Mix06Methods

public record Mix07(
    Point3 Origin,
    Point3 Dest,
    double Distance
);

public static class Mix07Methods {
public static void WriteMix07(SpecWriter w, Mix07 obj) {
    w.BeginObject(3);
    w.WriteField("origin"); Point3Methods.WritePoint3(w, obj.Origin);
    w.WriteField("dest"); Point3Methods.WritePoint3(w, obj.Dest);
    w.WriteField("distance"); w.WriteFloat64(obj.Distance);
    w.EndObject();
}

public static readonly SpecCodec<Mix07> Mix07Codec = new(
    Encode: (w, obj) => WriteMix07(w, obj),
    Decode: r => {
        Point3? _Origin = null;
        Point3? _Dest = null;
        double _Distance = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "origin": _Origin = Point3Methods.Point3Codec.Decode(r); break;
                case "dest": _Dest = Point3Methods.Point3Codec.Decode(r); break;
                case "distance": _Distance = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix07(Origin: _Origin!, Dest: _Dest!, Distance: _Distance);
    }
);
} // Mix07Methods

public record Mix08(
    List<string> Keys,
    List<int> Values,
    Label? Meta = null
);

public static class Mix08Methods {
public static void WriteMix08(SpecWriter w, Mix08 obj) {
    var fieldCount = 2;
    if (obj.Meta != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("keys"); w.BeginArray(obj.Keys.Count);
        foreach (var item in obj.Keys) { w.NextElement(); w.WriteString(item); }
        w.EndArray();
    w.WriteField("values"); w.BeginArray(obj.Values.Count);
        foreach (var item in obj.Values) { w.NextElement(); w.WriteInt32(item); }
        w.EndArray();
    if (obj.Meta != null) { w.WriteField("meta"); LabelMethods.WriteLabel(w, obj.Meta); }
    w.EndObject();
}

public static readonly SpecCodec<Mix08> Mix08Codec = new(
    Encode: (w, obj) => WriteMix08(w, obj),
    Decode: r => {
        List<string> _Keys = new List<string>();
        List<int> _Values = new List<int>();
        Label? _Meta = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "keys": _Keys = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                case "values": _Values = ((Func<List<int>>)(() => { var list = new List<int>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadInt32()); r.EndArray(); return list; }))(); break;
                case "meta": _Meta = r.IsNull() ? ((Func<Label?>)(() => { r.ReadNull(); return null; }))() : LabelMethods.LabelCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix08(Keys: _Keys, Values: _Values, Meta: _Meta);
    }
);
} // Mix08Methods

public record Mix09(
    long Id,
    byte[] Payload,
    uint Checksum,
    IdVal? Prev = null
);

public static class Mix09Methods {
public static void WriteMix09(SpecWriter w, Mix09 obj) {
    var fieldCount = 3;
    if (obj.Prev != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("id"); w.WriteInt64(obj.Id);
    w.WriteField("payload"); w.WriteBytes(obj.Payload);
    w.WriteField("checksum"); w.WriteUint32(obj.Checksum);
    if (obj.Prev != null) { w.WriteField("prev"); IdValMethods.WriteIdVal(w, obj.Prev); }
    w.EndObject();
}

public static readonly SpecCodec<Mix09> Mix09Codec = new(
    Encode: (w, obj) => WriteMix09(w, obj),
    Decode: r => {
        long _Id = 0L;
        byte[] _Payload = Array.Empty<byte>();
        uint _Checksum = 0u;
        IdVal? _Prev = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "id": _Id = r.ReadInt64(); break;
                case "payload": _Payload = r.ReadBytes(); break;
                case "checksum": _Checksum = r.ReadUint32(); break;
                case "prev": _Prev = r.IsNull() ? ((Func<IdVal?>)(() => { r.ReadNull(); return null; }))() : IdValMethods.IdValCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix09(Id: _Id, Payload: _Payload, Checksum: _Checksum, Prev: _Prev);
    }
);
} // Mix09Methods

public record Mix10(
    List<string> Items,
    int Total,
    double Avg,
    Range32 ValueRange
);

public static class Mix10Methods {
public static void WriteMix10(SpecWriter w, Mix10 obj) {
    w.BeginObject(4);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteString(item); }
        w.EndArray();
    w.WriteField("total"); w.WriteInt32(obj.Total);
    w.WriteField("avg"); w.WriteFloat64(obj.Avg);
    w.WriteField("value_range"); Range32Methods.WriteRange32(w, obj.ValueRange);
    w.EndObject();
}

public static readonly SpecCodec<Mix10> Mix10Codec = new(
    Encode: (w, obj) => WriteMix10(w, obj),
    Decode: r => {
        List<string> _Items = new List<string>();
        int _Total = 0;
        double _Avg = 0.0;
        Range32? _ValueRange = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                case "total": _Total = r.ReadInt32(); break;
                case "avg": _Avg = r.ReadFloat64(); break;
                case "value_range": _ValueRange = Range32Methods.Range32Codec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix10(Items: _Items, Total: _Total, Avg: _Avg, ValueRange: _ValueRange!);
    }
);
} // Mix10Methods

public record Mix11(
    string Name,
    List<double> Values,
    Inner? Nested = null,
    bool? Flag = null
);

public static class Mix11Methods {
public static void WriteMix11(SpecWriter w, Mix11 obj) {
    var fieldCount = 2;
    if (obj.Nested != null) fieldCount++;
    if (obj.Flag != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("name"); w.WriteString(obj.Name);
    w.WriteField("values"); w.BeginArray(obj.Values.Count);
        foreach (var item in obj.Values) { w.NextElement(); w.WriteFloat64(item); }
        w.EndArray();
    if (obj.Nested != null) { w.WriteField("nested"); InnerMethods.WriteInner(w, obj.Nested); }
    if (obj.Flag != null) { w.WriteField("flag"); w.WriteBool(obj.Flag.Value); }
    w.EndObject();
}

public static readonly SpecCodec<Mix11> Mix11Codec = new(
    Encode: (w, obj) => WriteMix11(w, obj),
    Decode: r => {
        string _Name = "";
        List<double> _Values = new List<double>();
        Inner? _Nested = null;
        bool? _Flag = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "name": _Name = r.ReadString(); break;
                case "values": _Values = ((Func<List<double>>)(() => { var list = new List<double>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadFloat64()); r.EndArray(); return list; }))(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<Inner?>)(() => { r.ReadNull(); return null; }))() : InnerMethods.InnerCodec.Decode(r); break;
                case "flag": _Flag = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix11(Name: _Name, Values: _Values, Nested: _Nested, Flag: _Flag);
    }
);
} // Mix11Methods

public record Mix12(
    string Header,
    List<IdVal> Entries,
    string? Footer = null
);

public static class Mix12Methods {
public static void WriteMix12(SpecWriter w, Mix12 obj) {
    var fieldCount = 2;
    if (obj.Footer != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("header"); w.WriteString(obj.Header);
    w.WriteField("entries"); w.BeginArray(obj.Entries.Count);
        foreach (var item in obj.Entries) { w.NextElement(); IdValMethods.WriteIdVal(w, item); }
        w.EndArray();
    if (obj.Footer != null) { w.WriteField("footer"); w.WriteString(obj.Footer); }
    w.EndObject();
}

public static readonly SpecCodec<Mix12> Mix12Codec = new(
    Encode: (w, obj) => WriteMix12(w, obj),
    Decode: r => {
        string _Header = "";
        List<IdVal> _Entries = new List<IdVal>();
        string? _Footer = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "header": _Header = r.ReadString(); break;
                case "entries": _Entries = ((Func<List<IdVal>>)(() => { var list = new List<IdVal>(); r.BeginArray(); while (r.HasNextElement()) list.Add(IdValMethods.IdValCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                case "footer": _Footer = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix12(Header: _Header, Entries: _Entries, Footer: _Footer);
    }
);
} // Mix12Methods

public record Mix13(
    int A,
    double B,
    string C,
    bool D,
    byte[] E,
    Inner Nested
);

public static class Mix13Methods {
public static void WriteMix13(SpecWriter w, Mix13 obj) {
    w.BeginObject(6);
    w.WriteField("a"); w.WriteInt32(obj.A);
    w.WriteField("b"); w.WriteFloat64(obj.B);
    w.WriteField("c"); w.WriteString(obj.C);
    w.WriteField("d"); w.WriteBool(obj.D);
    w.WriteField("e"); w.WriteBytes(obj.E);
    w.WriteField("nested"); InnerMethods.WriteInner(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<Mix13> Mix13Codec = new(
    Encode: (w, obj) => WriteMix13(w, obj),
    Decode: r => {
        int _A = 0;
        double _B = 0.0;
        string _C = "";
        bool _D = false;
        byte[] _E = Array.Empty<byte>();
        Inner? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadInt32(); break;
                case "b": _B = r.ReadFloat64(); break;
                case "c": _C = r.ReadString(); break;
                case "d": _D = r.ReadBool(); break;
                case "e": _E = r.ReadBytes(); break;
                case "nested": _Nested = InnerMethods.InnerCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix13(A: _A, B: _B, C: _C, D: _D, E: _E, Nested: _Nested!);
    }
);
} // Mix13Methods

public record Mix14(
    List<Money> Amounts,
    long Total,
    string Currency
);

public static class Mix14Methods {
public static void WriteMix14(SpecWriter w, Mix14 obj) {
    w.BeginObject(3);
    w.WriteField("amounts"); w.BeginArray(obj.Amounts.Count);
        foreach (var item in obj.Amounts) { w.NextElement(); MoneyMethods.WriteMoney(w, item); }
        w.EndArray();
    w.WriteField("total"); w.WriteInt64(obj.Total);
    w.WriteField("currency"); w.WriteString(obj.Currency);
    w.EndObject();
}

public static readonly SpecCodec<Mix14> Mix14Codec = new(
    Encode: (w, obj) => WriteMix14(w, obj),
    Decode: r => {
        List<Money> _Amounts = new List<Money>();
        long _Total = 0L;
        string _Currency = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "amounts": _Amounts = ((Func<List<Money>>)(() => { var list = new List<Money>(); r.BeginArray(); while (r.HasNextElement()) list.Add(MoneyMethods.MoneyCodec.Decode(r)); r.EndArray(); return list; }))(); break;
                case "total": _Total = r.ReadInt64(); break;
                case "currency": _Currency = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix14(Amounts: _Amounts, Total: _Total, Currency: _Currency);
    }
);
} // Mix14Methods

public record Mix15(
    Addr SrcAddr,
    Addr DstAddr,
    double Distance,
    double Duration
);

public static class Mix15Methods {
public static void WriteMix15(SpecWriter w, Mix15 obj) {
    w.BeginObject(4);
    w.WriteField("src_addr"); AddrMethods.WriteAddr(w, obj.SrcAddr);
    w.WriteField("dst_addr"); AddrMethods.WriteAddr(w, obj.DstAddr);
    w.WriteField("distance"); w.WriteFloat64(obj.Distance);
    w.WriteField("duration"); w.WriteFloat64(obj.Duration);
    w.EndObject();
}

public static readonly SpecCodec<Mix15> Mix15Codec = new(
    Encode: (w, obj) => WriteMix15(w, obj),
    Decode: r => {
        Addr? _SrcAddr = null;
        Addr? _DstAddr = null;
        double _Distance = 0.0;
        double _Duration = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "src_addr": _SrcAddr = AddrMethods.AddrCodec.Decode(r); break;
                case "dst_addr": _DstAddr = AddrMethods.AddrCodec.Decode(r); break;
                case "distance": _Distance = r.ReadFloat64(); break;
                case "duration": _Duration = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Mix15(SrcAddr: _SrcAddr!, DstAddr: _DstAddr!, Distance: _Distance, Duration: _Duration);
    }
);
} // Mix15Methods

public record AllOpt1(
    string? A = null,
    int? B = null,
    bool? C = null
);

public static class AllOpt1Methods {
public static void WriteAllOpt1(SpecWriter w, AllOpt1 obj) {
    var fieldCount = 0;
    if (obj.A != null) fieldCount++;
    if (obj.B != null) fieldCount++;
    if (obj.C != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.A != null) { w.WriteField("a"); w.WriteString(obj.A); }
    if (obj.B != null) { w.WriteField("b"); w.WriteInt32(obj.B.Value); }
    if (obj.C != null) { w.WriteField("c"); w.WriteBool(obj.C.Value); }
    w.EndObject();
}

public static readonly SpecCodec<AllOpt1> AllOpt1Codec = new(
    Encode: (w, obj) => WriteAllOpt1(w, obj),
    Decode: r => {
        string? _A = null;
        int? _B = null;
        bool? _C = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadInt32(); break;
                case "c": _C = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new AllOpt1(A: _A, B: _B, C: _C);
    }
);
} // AllOpt1Methods

public record AllOpt2(
    double? X = null,
    byte[]? Y = null,
    long? Z = null
);

public static class AllOpt2Methods {
public static void WriteAllOpt2(SpecWriter w, AllOpt2 obj) {
    var fieldCount = 0;
    if (obj.X != null) fieldCount++;
    if (obj.Y != null) fieldCount++;
    if (obj.Z != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.X != null) { w.WriteField("x"); w.WriteFloat64(obj.X.Value); }
    if (obj.Y != null) { w.WriteField("y"); w.WriteBytes(obj.Y); }
    if (obj.Z != null) { w.WriteField("z"); w.WriteInt64(obj.Z.Value); }
    w.EndObject();
}

public static readonly SpecCodec<AllOpt2> AllOpt2Codec = new(
    Encode: (w, obj) => WriteAllOpt2(w, obj),
    Decode: r => {
        double? _X = null;
        byte[]? _Y = null;
        long? _Z = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "x": _X = r.ReadFloat64(); break;
                case "y": _Y = r.ReadBytes(); break;
                case "z": _Z = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new AllOpt2(X: _X, Y: _Y, Z: _Z);
    }
);
} // AllOpt2Methods

public record AllOpt3(
    string? Name = null,
    int? Age = null,
    double? Score = null,
    bool? Active = null
);

public static class AllOpt3Methods {
public static void WriteAllOpt3(SpecWriter w, AllOpt3 obj) {
    var fieldCount = 0;
    if (obj.Name != null) fieldCount++;
    if (obj.Age != null) fieldCount++;
    if (obj.Score != null) fieldCount++;
    if (obj.Active != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.Name != null) { w.WriteField("name"); w.WriteString(obj.Name); }
    if (obj.Age != null) { w.WriteField("age"); w.WriteInt32(obj.Age.Value); }
    if (obj.Score != null) { w.WriteField("score"); w.WriteFloat64(obj.Score.Value); }
    if (obj.Active != null) { w.WriteField("active"); w.WriteBool(obj.Active.Value); }
    w.EndObject();
}

public static readonly SpecCodec<AllOpt3> AllOpt3Codec = new(
    Encode: (w, obj) => WriteAllOpt3(w, obj),
    Decode: r => {
        string? _Name = null;
        int? _Age = null;
        double? _Score = null;
        bool? _Active = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "name": _Name = r.ReadString(); break;
                case "age": _Age = r.ReadInt32(); break;
                case "score": _Score = r.ReadFloat64(); break;
                case "active": _Active = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new AllOpt3(Name: _Name, Age: _Age, Score: _Score, Active: _Active);
    }
);
} // AllOpt3Methods

public record AllOpt4(
    uint? A = null,
    ulong? B = null,
    int? C = null,
    string? D = null,
    byte[]? E = null
);

public static class AllOpt4Methods {
public static void WriteAllOpt4(SpecWriter w, AllOpt4 obj) {
    var fieldCount = 0;
    if (obj.A != null) fieldCount++;
    if (obj.B != null) fieldCount++;
    if (obj.C != null) fieldCount++;
    if (obj.D != null) fieldCount++;
    if (obj.E != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.A != null) { w.WriteField("a"); w.WriteUint32(obj.A.Value); }
    if (obj.B != null) { w.WriteField("b"); w.WriteUint64(obj.B.Value); }
    if (obj.C != null) { w.WriteField("c"); w.WriteInt32(obj.C.Value); }
    if (obj.D != null) { w.WriteField("d"); w.WriteString(obj.D); }
    if (obj.E != null) { w.WriteField("e"); w.WriteBytes(obj.E); }
    w.EndObject();
}

public static readonly SpecCodec<AllOpt4> AllOpt4Codec = new(
    Encode: (w, obj) => WriteAllOpt4(w, obj),
    Decode: r => {
        uint? _A = null;
        ulong? _B = null;
        int? _C = null;
        string? _D = null;
        byte[]? _E = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadUint32(); break;
                case "b": _B = r.ReadUint64(); break;
                case "c": _C = r.ReadInt32(); break;
                case "d": _D = r.ReadString(); break;
                case "e": _E = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new AllOpt4(A: _A, B: _B, C: _C, D: _D, E: _E);
    }
);
} // AllOpt4Methods

public record AllOpt5(
    Inner? P = null,
    string? Q = null
);

public static class AllOpt5Methods {
public static void WriteAllOpt5(SpecWriter w, AllOpt5 obj) {
    var fieldCount = 0;
    if (obj.P != null) fieldCount++;
    if (obj.Q != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.P != null) { w.WriteField("p"); InnerMethods.WriteInner(w, obj.P); }
    if (obj.Q != null) { w.WriteField("q"); w.WriteString(obj.Q); }
    w.EndObject();
}

public static readonly SpecCodec<AllOpt5> AllOpt5Codec = new(
    Encode: (w, obj) => WriteAllOpt5(w, obj),
    Decode: r => {
        Inner? _P = null;
        string? _Q = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "p": _P = r.IsNull() ? ((Func<Inner?>)(() => { r.ReadNull(); return null; }))() : InnerMethods.InnerCodec.Decode(r); break;
                case "q": _Q = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new AllOpt5(P: _P, Q: _Q);
    }
);
} // AllOpt5Methods
