// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Scalars;

using Specodec;
using System;
using System.Collections.Generic;

public record SingleString(
    string V
);

public static class SingleStringMethods {
public static void WriteSingleString(SpecWriter w, SingleString obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteString(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleString> SingleStringCodec = new(
    Encode: (w, obj) => WriteSingleString(w, obj),
    Decode: r => {
        string _V = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleString(V: _V);
    }
);
} // SingleStringMethods

public record SingleBoolean(
    bool V
);

public static class SingleBooleanMethods {
public static void WriteSingleBoolean(SpecWriter w, SingleBoolean obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteBool(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleBoolean> SingleBooleanCodec = new(
    Encode: (w, obj) => WriteSingleBoolean(w, obj),
    Decode: r => {
        bool _V = false;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadBool(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleBoolean(V: _V);
    }
);
} // SingleBooleanMethods

public record SingleInt8(
    byte V
);

public static class SingleInt8Methods {
public static void WriteSingleInt8(SpecWriter w, SingleInt8 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteInt32((sbyte)obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleInt8> SingleInt8Codec = new(
    Encode: (w, obj) => WriteSingleInt8(w, obj),
    Decode: r => {
        byte _V = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = (byte)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleInt8(V: _V);
    }
);
} // SingleInt8Methods

public record SingleInt16(
    short V
);

public static class SingleInt16Methods {
public static void WriteSingleInt16(SpecWriter w, SingleInt16 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteInt32(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleInt16> SingleInt16Codec = new(
    Encode: (w, obj) => WriteSingleInt16(w, obj),
    Decode: r => {
        short _V = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = (short)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleInt16(V: _V);
    }
);
} // SingleInt16Methods

public record SingleInt32(
    int V
);

public static class SingleInt32Methods {
public static void WriteSingleInt32(SpecWriter w, SingleInt32 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteInt32(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleInt32> SingleInt32Codec = new(
    Encode: (w, obj) => WriteSingleInt32(w, obj),
    Decode: r => {
        int _V = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleInt32(V: _V);
    }
);
} // SingleInt32Methods

public record SingleInt64(
    long V
);

public static class SingleInt64Methods {
public static void WriteSingleInt64(SpecWriter w, SingleInt64 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteInt64(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleInt64> SingleInt64Codec = new(
    Encode: (w, obj) => WriteSingleInt64(w, obj),
    Decode: r => {
        long _V = 0L;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleInt64(V: _V);
    }
);
} // SingleInt64Methods

public record SingleUint8(
    byte V
);

public static class SingleUint8Methods {
public static void WriteSingleUint8(SpecWriter w, SingleUint8 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteUint32(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleUint8> SingleUint8Codec = new(
    Encode: (w, obj) => WriteSingleUint8(w, obj),
    Decode: r => {
        byte _V = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = (byte)r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleUint8(V: _V);
    }
);
} // SingleUint8Methods

public record SingleUint16(
    ushort V
);

public static class SingleUint16Methods {
public static void WriteSingleUint16(SpecWriter w, SingleUint16 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteUint32(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleUint16> SingleUint16Codec = new(
    Encode: (w, obj) => WriteSingleUint16(w, obj),
    Decode: r => {
        ushort _V = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = (ushort)r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleUint16(V: _V);
    }
);
} // SingleUint16Methods

public record SingleUint32(
    uint V
);

public static class SingleUint32Methods {
public static void WriteSingleUint32(SpecWriter w, SingleUint32 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteUint32(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleUint32> SingleUint32Codec = new(
    Encode: (w, obj) => WriteSingleUint32(w, obj),
    Decode: r => {
        uint _V = 0u;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleUint32(V: _V);
    }
);
} // SingleUint32Methods

public record SingleUint64(
    ulong V
);

public static class SingleUint64Methods {
public static void WriteSingleUint64(SpecWriter w, SingleUint64 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteUint64(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleUint64> SingleUint64Codec = new(
    Encode: (w, obj) => WriteSingleUint64(w, obj),
    Decode: r => {
        ulong _V = 0UL;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadUint64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleUint64(V: _V);
    }
);
} // SingleUint64Methods

public record SingleFloat32(
    float V
);

public static class SingleFloat32Methods {
public static void WriteSingleFloat32(SpecWriter w, SingleFloat32 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteFloat32(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleFloat32> SingleFloat32Codec = new(
    Encode: (w, obj) => WriteSingleFloat32(w, obj),
    Decode: r => {
        float _V = 0f;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadFloat32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleFloat32(V: _V);
    }
);
} // SingleFloat32Methods

public record SingleFloat64(
    double V
);

public static class SingleFloat64Methods {
public static void WriteSingleFloat64(SpecWriter w, SingleFloat64 obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteFloat64(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleFloat64> SingleFloat64Codec = new(
    Encode: (w, obj) => WriteSingleFloat64(w, obj),
    Decode: r => {
        double _V = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleFloat64(V: _V);
    }
);
} // SingleFloat64Methods

public record SingleBytes(
    byte[] V
);

public static class SingleBytesMethods {
public static void WriteSingleBytes(SpecWriter w, SingleBytes obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteBytes(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<SingleBytes> SingleBytesCodec = new(
    Encode: (w, obj) => WriteSingleBytes(w, obj),
    Decode: r => {
        byte[] _V = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new SingleBytes(V: _V);
    }
);
} // SingleBytesMethods
