// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes;

using Specodec;
using System;
using System.Collections.Generic;

public record Inner(
    int X,
    int Y
);

public static class InnerMethods {
public static void WriteInner(SpecWriter w, Inner obj) {
    w.BeginObject(2);
    w.WriteField("x"); w.WriteInt32(obj.X);
    w.WriteField("y"); w.WriteInt32(obj.Y);
    w.EndObject();
}

public static readonly SpecCodec<Inner> InnerCodec = new(
    Encode: (w, obj) => WriteInner(w, obj),
    Decode: r => {
        int _X = 0;
        int _Y = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "x": _X = r.ReadInt32(); break;
                case "y": _Y = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Inner(X: _X, Y: _Y);
    }
);
} // InnerMethods

public record Coord(
    double Lat,
    double Lng
);

public static class CoordMethods {
public static void WriteCoord(SpecWriter w, Coord obj) {
    w.BeginObject(2);
    w.WriteField("lat"); w.WriteFloat64(obj.Lat);
    w.WriteField("lng"); w.WriteFloat64(obj.Lng);
    w.EndObject();
}

public static readonly SpecCodec<Coord> CoordCodec = new(
    Encode: (w, obj) => WriteCoord(w, obj),
    Decode: r => {
        double _Lat = 0.0;
        double _Lng = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "lat": _Lat = r.ReadFloat64(); break;
                case "lng": _Lng = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Coord(Lat: _Lat, Lng: _Lng);
    }
);
} // CoordMethods

public record IdVal(
    string Id,
    int Value
);

public static class IdValMethods {
public static void WriteIdVal(SpecWriter w, IdVal obj) {
    w.BeginObject(2);
    w.WriteField("id"); w.WriteString(obj.Id);
    w.WriteField("value"); w.WriteInt32(obj.Value);
    w.EndObject();
}

public static readonly SpecCodec<IdVal> IdValCodec = new(
    Encode: (w, obj) => WriteIdVal(w, obj),
    Decode: r => {
        string _Id = "";
        int _Value = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "id": _Id = r.ReadString(); break;
                case "value": _Value = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new IdVal(Id: _Id, Value: _Value);
    }
);
} // IdValMethods

public record Label(
    string Key,
    string Text
);

public static class LabelMethods {
public static void WriteLabel(SpecWriter w, Label obj) {
    w.BeginObject(2);
    w.WriteField("key"); w.WriteString(obj.Key);
    w.WriteField("text"); w.WriteString(obj.Text);
    w.EndObject();
}

public static readonly SpecCodec<Label> LabelCodec = new(
    Encode: (w, obj) => WriteLabel(w, obj),
    Decode: r => {
        string _Key = "";
        string _Text = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "key": _Key = r.ReadString(); break;
                case "text": _Text = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Label(Key: _Key, Text: _Text);
    }
);
} // LabelMethods

public record Money(
    long Amount,
    string Currency
);

public static class MoneyMethods {
public static void WriteMoney(SpecWriter w, Money obj) {
    w.BeginObject(2);
    w.WriteField("amount"); w.WriteInt64(obj.Amount);
    w.WriteField("currency"); w.WriteString(obj.Currency);
    w.EndObject();
}

public static readonly SpecCodec<Money> MoneyCodec = new(
    Encode: (w, obj) => WriteMoney(w, obj),
    Decode: r => {
        long _Amount = 0L;
        string _Currency = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "amount": _Amount = r.ReadInt64(); break;
                case "currency": _Currency = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Money(Amount: _Amount, Currency: _Currency);
    }
);
} // MoneyMethods

public record Range32(
    int Min,
    int Max
);

public static class Range32Methods {
public static void WriteRange32(SpecWriter w, Range32 obj) {
    w.BeginObject(2);
    w.WriteField("min"); w.WriteInt32(obj.Min);
    w.WriteField("max"); w.WriteInt32(obj.Max);
    w.EndObject();
}

public static readonly SpecCodec<Range32> Range32Codec = new(
    Encode: (w, obj) => WriteRange32(w, obj),
    Decode: r => {
        int _Min = 0;
        int _Max = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "min": _Min = r.ReadInt32(); break;
                case "max": _Max = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Range32(Min: _Min, Max: _Max);
    }
);
} // Range32Methods

public record Addr(
    string Street,
    string City,
    string Zip
);

public static class AddrMethods {
public static void WriteAddr(SpecWriter w, Addr obj) {
    w.BeginObject(3);
    w.WriteField("street"); w.WriteString(obj.Street);
    w.WriteField("city"); w.WriteString(obj.City);
    w.WriteField("zip"); w.WriteString(obj.Zip);
    w.EndObject();
}

public static readonly SpecCodec<Addr> AddrCodec = new(
    Encode: (w, obj) => WriteAddr(w, obj),
    Decode: r => {
        string _Street = "";
        string _City = "";
        string _Zip = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "street": _Street = r.ReadString(); break;
                case "city": _City = r.ReadString(); break;
                case "zip": _Zip = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Addr(Street: _Street, City: _City, Zip: _Zip);
    }
);
} // AddrMethods

public record Point3(
    double X,
    double Y,
    double Z
);

public static class Point3Methods {
public static void WritePoint3(SpecWriter w, Point3 obj) {
    w.BeginObject(3);
    w.WriteField("x"); w.WriteFloat64(obj.X);
    w.WriteField("y"); w.WriteFloat64(obj.Y);
    w.WriteField("z"); w.WriteFloat64(obj.Z);
    w.EndObject();
}

public static readonly SpecCodec<Point3> Point3Codec = new(
    Encode: (w, obj) => WritePoint3(w, obj),
    Decode: r => {
        double _X = 0.0;
        double _Y = 0.0;
        double _Z = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "x": _X = r.ReadFloat64(); break;
                case "y": _Y = r.ReadFloat64(); break;
                case "z": _Z = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Point3(X: _X, Y: _Y, Z: _Z);
    }
);
} // Point3Methods

public record OptInner(
    string? Name = null,
    double? Score = null,
    string? Tag = null
);

public static class OptInnerMethods {
public static void WriteOptInner(SpecWriter w, OptInner obj) {
    var fieldCount = 0;
    if (obj.Name != null) fieldCount++;
    if (obj.Score != null) fieldCount++;
    if (obj.Tag != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.Name != null) { w.WriteField("name"); w.WriteString(obj.Name); }
    if (obj.Score != null) { w.WriteField("score"); w.WriteFloat64(obj.Score.Value); }
    if (obj.Tag != null) { w.WriteField("tag"); w.WriteString(obj.Tag); }
    w.EndObject();
}

public static readonly SpecCodec<OptInner> OptInnerCodec = new(
    Encode: (w, obj) => WriteOptInner(w, obj),
    Decode: r => {
        string? _Name = null;
        double? _Score = null;
        string? _Tag = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "name": _Name = r.ReadString(); break;
                case "score": _Score = r.ReadFloat64(); break;
                case "tag": _Tag = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptInner(Name: _Name, Score: _Score, Tag: _Tag);
    }
);
} // OptInnerMethods
