// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Nests;

using Specodec;
using System;
using System.Collections.Generic;

public record NestInner(
    Inner Nested
);

public static class NestInnerMethods {
public static void WriteNestInner(SpecWriter w, NestInner obj) {
    w.BeginObject(1);
    w.WriteField("nested"); InnerMethods.WriteInner(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<NestInner> NestInnerCodec = new(
    Encode: (w, obj) => WriteNestInner(w, obj),
    Decode: r => {
        Inner? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "nested": _Nested = InnerMethods.InnerCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestInner(Nested: _Nested!);
    }
);
} // NestInnerMethods

public record NestCoord(
    Coord Nested
);

public static class NestCoordMethods {
public static void WriteNestCoord(SpecWriter w, NestCoord obj) {
    w.BeginObject(1);
    w.WriteField("nested"); CoordMethods.WriteCoord(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<NestCoord> NestCoordCodec = new(
    Encode: (w, obj) => WriteNestCoord(w, obj),
    Decode: r => {
        Coord? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "nested": _Nested = CoordMethods.CoordCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestCoord(Nested: _Nested!);
    }
);
} // NestCoordMethods

public record NestIdVal(
    IdVal Nested
);

public static class NestIdValMethods {
public static void WriteNestIdVal(SpecWriter w, NestIdVal obj) {
    w.BeginObject(1);
    w.WriteField("nested"); IdValMethods.WriteIdVal(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<NestIdVal> NestIdValCodec = new(
    Encode: (w, obj) => WriteNestIdVal(w, obj),
    Decode: r => {
        IdVal? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "nested": _Nested = IdValMethods.IdValCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestIdVal(Nested: _Nested!);
    }
);
} // NestIdValMethods

public record NestLabel(
    Label Nested
);

public static class NestLabelMethods {
public static void WriteNestLabel(SpecWriter w, NestLabel obj) {
    w.BeginObject(1);
    w.WriteField("nested"); LabelMethods.WriteLabel(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<NestLabel> NestLabelCodec = new(
    Encode: (w, obj) => WriteNestLabel(w, obj),
    Decode: r => {
        Label? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "nested": _Nested = LabelMethods.LabelCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestLabel(Nested: _Nested!);
    }
);
} // NestLabelMethods

public record NestMoney(
    Money Nested
);

public static class NestMoneyMethods {
public static void WriteNestMoney(SpecWriter w, NestMoney obj) {
    w.BeginObject(1);
    w.WriteField("nested"); MoneyMethods.WriteMoney(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<NestMoney> NestMoneyCodec = new(
    Encode: (w, obj) => WriteNestMoney(w, obj),
    Decode: r => {
        Money? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "nested": _Nested = MoneyMethods.MoneyCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestMoney(Nested: _Nested!);
    }
);
} // NestMoneyMethods

public record NestRange32(
    Range32 Nested
);

public static class NestRange32Methods {
public static void WriteNestRange32(SpecWriter w, NestRange32 obj) {
    w.BeginObject(1);
    w.WriteField("nested"); Range32Methods.WriteRange32(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<NestRange32> NestRange32Codec = new(
    Encode: (w, obj) => WriteNestRange32(w, obj),
    Decode: r => {
        Range32? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "nested": _Nested = Range32Methods.Range32Codec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestRange32(Nested: _Nested!);
    }
);
} // NestRange32Methods

public record NestAddr(
    Addr Nested
);

public static class NestAddrMethods {
public static void WriteNestAddr(SpecWriter w, NestAddr obj) {
    w.BeginObject(1);
    w.WriteField("nested"); AddrMethods.WriteAddr(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<NestAddr> NestAddrCodec = new(
    Encode: (w, obj) => WriteNestAddr(w, obj),
    Decode: r => {
        Addr? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "nested": _Nested = AddrMethods.AddrCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestAddr(Nested: _Nested!);
    }
);
} // NestAddrMethods

public record NestPoint3(
    Point3 Nested
);

public static class NestPoint3Methods {
public static void WriteNestPoint3(SpecWriter w, NestPoint3 obj) {
    w.BeginObject(1);
    w.WriteField("nested"); Point3Methods.WritePoint3(w, obj.Nested);
    w.EndObject();
}

public static readonly SpecCodec<NestPoint3> NestPoint3Codec = new(
    Encode: (w, obj) => WriteNestPoint3(w, obj),
    Decode: r => {
        Point3? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "nested": _Nested = Point3Methods.Point3Codec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new NestPoint3(Nested: _Nested!);
    }
);
} // NestPoint3Methods

public record OptNestInner(
    string Label,
    Inner? Nested = null
);

public static class OptNestInnerMethods {
public static void WriteOptNestInner(SpecWriter w, OptNestInner obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("label"); w.WriteString(obj.Label);
    if (obj.Nested != null) { w.WriteField("nested"); InnerMethods.WriteInner(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<OptNestInner> OptNestInnerCodec = new(
    Encode: (w, obj) => WriteOptNestInner(w, obj),
    Decode: r => {
        string _Label = "";
        Inner? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<Inner?>)(() => { r.ReadNull(); return null; }))() : InnerMethods.InnerCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptNestInner(Label: _Label, Nested: _Nested);
    }
);
} // OptNestInnerMethods

public record OptNestCoord(
    string Label,
    Coord? Nested = null
);

public static class OptNestCoordMethods {
public static void WriteOptNestCoord(SpecWriter w, OptNestCoord obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("label"); w.WriteString(obj.Label);
    if (obj.Nested != null) { w.WriteField("nested"); CoordMethods.WriteCoord(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<OptNestCoord> OptNestCoordCodec = new(
    Encode: (w, obj) => WriteOptNestCoord(w, obj),
    Decode: r => {
        string _Label = "";
        Coord? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<Coord?>)(() => { r.ReadNull(); return null; }))() : CoordMethods.CoordCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptNestCoord(Label: _Label, Nested: _Nested);
    }
);
} // OptNestCoordMethods

public record OptNestIdVal(
    string Label,
    IdVal? Nested = null
);

public static class OptNestIdValMethods {
public static void WriteOptNestIdVal(SpecWriter w, OptNestIdVal obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("label"); w.WriteString(obj.Label);
    if (obj.Nested != null) { w.WriteField("nested"); IdValMethods.WriteIdVal(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<OptNestIdVal> OptNestIdValCodec = new(
    Encode: (w, obj) => WriteOptNestIdVal(w, obj),
    Decode: r => {
        string _Label = "";
        IdVal? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<IdVal?>)(() => { r.ReadNull(); return null; }))() : IdValMethods.IdValCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptNestIdVal(Label: _Label, Nested: _Nested);
    }
);
} // OptNestIdValMethods

public record OptNestLabel(
    string Label,
    Label? Nested = null
);

public static class OptNestLabelMethods {
public static void WriteOptNestLabel(SpecWriter w, OptNestLabel obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("label"); w.WriteString(obj.Label);
    if (obj.Nested != null) { w.WriteField("nested"); LabelMethods.WriteLabel(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<OptNestLabel> OptNestLabelCodec = new(
    Encode: (w, obj) => WriteOptNestLabel(w, obj),
    Decode: r => {
        string _Label = "";
        Label? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<Label?>)(() => { r.ReadNull(); return null; }))() : LabelMethods.LabelCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptNestLabel(Label: _Label, Nested: _Nested);
    }
);
} // OptNestLabelMethods

public record OptNestMoney(
    string Label,
    Money? Nested = null
);

public static class OptNestMoneyMethods {
public static void WriteOptNestMoney(SpecWriter w, OptNestMoney obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("label"); w.WriteString(obj.Label);
    if (obj.Nested != null) { w.WriteField("nested"); MoneyMethods.WriteMoney(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<OptNestMoney> OptNestMoneyCodec = new(
    Encode: (w, obj) => WriteOptNestMoney(w, obj),
    Decode: r => {
        string _Label = "";
        Money? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<Money?>)(() => { r.ReadNull(); return null; }))() : MoneyMethods.MoneyCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptNestMoney(Label: _Label, Nested: _Nested);
    }
);
} // OptNestMoneyMethods

public record OptNestRange32(
    string Label,
    Range32? Nested = null
);

public static class OptNestRange32Methods {
public static void WriteOptNestRange32(SpecWriter w, OptNestRange32 obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("label"); w.WriteString(obj.Label);
    if (obj.Nested != null) { w.WriteField("nested"); Range32Methods.WriteRange32(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<OptNestRange32> OptNestRange32Codec = new(
    Encode: (w, obj) => WriteOptNestRange32(w, obj),
    Decode: r => {
        string _Label = "";
        Range32? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<Range32?>)(() => { r.ReadNull(); return null; }))() : Range32Methods.Range32Codec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptNestRange32(Label: _Label, Nested: _Nested);
    }
);
} // OptNestRange32Methods

public record OptNestAddr(
    string Label,
    Addr? Nested = null
);

public static class OptNestAddrMethods {
public static void WriteOptNestAddr(SpecWriter w, OptNestAddr obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("label"); w.WriteString(obj.Label);
    if (obj.Nested != null) { w.WriteField("nested"); AddrMethods.WriteAddr(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<OptNestAddr> OptNestAddrCodec = new(
    Encode: (w, obj) => WriteOptNestAddr(w, obj),
    Decode: r => {
        string _Label = "";
        Addr? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<Addr?>)(() => { r.ReadNull(); return null; }))() : AddrMethods.AddrCodec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptNestAddr(Label: _Label, Nested: _Nested);
    }
);
} // OptNestAddrMethods

public record OptNestPoint3(
    string Label,
    Point3? Nested = null
);

public static class OptNestPoint3Methods {
public static void WriteOptNestPoint3(SpecWriter w, OptNestPoint3 obj) {
    var fieldCount = 1;
    if (obj.Nested != null) fieldCount++;
    w.BeginObject(fieldCount);
    w.WriteField("label"); w.WriteString(obj.Label);
    if (obj.Nested != null) { w.WriteField("nested"); Point3Methods.WritePoint3(w, obj.Nested); }
    w.EndObject();
}

public static readonly SpecCodec<OptNestPoint3> OptNestPoint3Codec = new(
    Encode: (w, obj) => WriteOptNestPoint3(w, obj),
    Decode: r => {
        string _Label = "";
        Point3? _Nested = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "label": _Label = r.ReadString(); break;
                case "nested": _Nested = r.IsNull() ? ((Func<Point3?>)(() => { r.ReadNull(); return null; }))() : Point3Methods.Point3Codec.Decode(r); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new OptNestPoint3(Label: _Label, Nested: _Nested);
    }
);
} // OptNestPoint3Methods
