// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Edge;

using Specodec;
using System;
using System.Collections.Generic;

public record EdgeEmpty;

public static class EdgeEmptyMethods {
public static void WriteEdgeEmpty(SpecWriter w, EdgeEmpty obj) {
    w.BeginObject(0);
    w.EndObject();
}

public static readonly SpecCodec<EdgeEmpty> EdgeEmptyCodec = new(
    Encode: (w, obj) => WriteEdgeEmpty(w, obj),
    Decode: r => {
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeEmpty();
    }
);
} // EdgeEmptyMethods

public record EdgeOneOpt(
    string? Maybe = null
);

public static class EdgeOneOptMethods {
public static void WriteEdgeOneOpt(SpecWriter w, EdgeOneOpt obj) {
    var fieldCount = 0;
    if (obj.Maybe != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.Maybe != null) { w.WriteField("maybe"); w.WriteString(obj.Maybe); }
    w.EndObject();
}

public static readonly SpecCodec<EdgeOneOpt> EdgeOneOptCodec = new(
    Encode: (w, obj) => WriteEdgeOneOpt(w, obj),
    Decode: r => {
        string? _Maybe = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "maybe": _Maybe = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeOneOpt(Maybe: _Maybe);
    }
);
} // EdgeOneOptMethods

public record EdgeBigNums(
    byte I8,
    short I16,
    int I32,
    long I64,
    byte U8,
    ushort U16,
    uint U32,
    ulong U64
);

public static class EdgeBigNumsMethods {
public static void WriteEdgeBigNums(SpecWriter w, EdgeBigNums obj) {
    w.BeginObject(8);
    w.WriteField("i8"); w.WriteInt32((sbyte)obj.I8);
    w.WriteField("i16"); w.WriteInt32(obj.I16);
    w.WriteField("i32"); w.WriteInt32(obj.I32);
    w.WriteField("i64"); w.WriteInt64(obj.I64);
    w.WriteField("u8"); w.WriteUint32(obj.U8);
    w.WriteField("u16"); w.WriteUint32(obj.U16);
    w.WriteField("u32"); w.WriteUint32(obj.U32);
    w.WriteField("u64"); w.WriteUint64(obj.U64);
    w.EndObject();
}

public static readonly SpecCodec<EdgeBigNums> EdgeBigNumsCodec = new(
    Encode: (w, obj) => WriteEdgeBigNums(w, obj),
    Decode: r => {
        byte _I8 = 0;
        short _I16 = 0;
        int _I32 = 0;
        long _I64 = 0L;
        byte _U8 = 0;
        ushort _U16 = 0;
        uint _U32 = 0u;
        ulong _U64 = 0UL;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "i8": _I8 = (byte)r.ReadInt32(); break;
                case "i16": _I16 = (short)r.ReadInt32(); break;
                case "i32": _I32 = r.ReadInt32(); break;
                case "i64": _I64 = r.ReadInt64(); break;
                case "u8": _U8 = (byte)r.ReadUint32(); break;
                case "u16": _U16 = (ushort)r.ReadUint32(); break;
                case "u32": _U32 = r.ReadUint32(); break;
                case "u64": _U64 = r.ReadUint64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeBigNums(I8: _I8, I16: _I16, I32: _I32, I64: _I64, U8: _U8, U16: _U16, U32: _U32, U64: _U64);
    }
);
} // EdgeBigNumsMethods

public record EdgeZeroVals(
    string S,
    int I,
    double F,
    bool B,
    byte[] ByField
);

public static class EdgeZeroValsMethods {
public static void WriteEdgeZeroVals(SpecWriter w, EdgeZeroVals obj) {
    w.BeginObject(5);
    w.WriteField("s"); w.WriteString(obj.S);
    w.WriteField("i"); w.WriteInt32(obj.I);
    w.WriteField("f"); w.WriteFloat64(obj.F);
    w.WriteField("b"); w.WriteBool(obj.B);
    w.WriteField("by_field"); w.WriteBytes(obj.ByField);
    w.EndObject();
}

public static readonly SpecCodec<EdgeZeroVals> EdgeZeroValsCodec = new(
    Encode: (w, obj) => WriteEdgeZeroVals(w, obj),
    Decode: r => {
        string _S = "";
        int _I = 0;
        double _F = 0.0;
        bool _B = false;
        byte[] _ByField = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "s": _S = r.ReadString(); break;
                case "i": _I = r.ReadInt32(); break;
                case "f": _F = r.ReadFloat64(); break;
                case "b": _B = r.ReadBool(); break;
                case "by_field": _ByField = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeZeroVals(S: _S, I: _I, F: _F, B: _B, ByField: _ByField);
    }
);
} // EdgeZeroValsMethods

public record EdgeNullable(
    string? A = null,
    int? B = null,
    Inner? C = null,
    List<string>? D = null
);

public static class EdgeNullableMethods {
public static void WriteEdgeNullable(SpecWriter w, EdgeNullable obj) {
    var fieldCount = 0;
    if (obj.A != null) fieldCount++;
    if (obj.B != null) fieldCount++;
    if (obj.C != null) fieldCount++;
    if (obj.D != null) fieldCount++;
    w.BeginObject(fieldCount);
    if (obj.A != null) { w.WriteField("a"); w.WriteString(obj.A); }
    if (obj.B != null) { w.WriteField("b"); w.WriteInt32(obj.B.Value); }
    if (obj.C != null) { w.WriteField("c"); InnerMethods.WriteInner(w, obj.C); }
    if (obj.D != null) { w.WriteField("d"); w.BeginArray(obj.D.Count);
        foreach (var item in obj.D) { w.NextElement(); w.WriteString(item); }
        w.EndArray(); }
    w.EndObject();
}

public static readonly SpecCodec<EdgeNullable> EdgeNullableCodec = new(
    Encode: (w, obj) => WriteEdgeNullable(w, obj),
    Decode: r => {
        string? _A = null;
        int? _B = null;
        Inner? _C = null;
        List<string>? _D = null;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a": _A = r.ReadString(); break;
                case "b": _B = r.ReadInt32(); break;
                case "c": _C = r.IsNull() ? ((Func<Inner?>)(() => { r.ReadNull(); return null; }))() : InnerMethods.InnerCodec.Decode(r); break;
                case "d": _D = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeNullable(A: _A, B: _B, C: _C, D: _D);
    }
);
} // EdgeNullableMethods

public record EdgeNegZero(
    double V
);

public static class EdgeNegZeroMethods {
public static void WriteEdgeNegZero(SpecWriter w, EdgeNegZero obj) {
    w.BeginObject(1);
    w.WriteField("v"); w.WriteFloat64(obj.V);
    w.EndObject();
}

public static readonly SpecCodec<EdgeNegZero> EdgeNegZeroCodec = new(
    Encode: (w, obj) => WriteEdgeNegZero(w, obj),
    Decode: r => {
        double _V = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "v": _V = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeNegZero(V: _V);
    }
);
} // EdgeNegZeroMethods

public record EdgeNullByte(
    string S,
    byte[] B
);

public static class EdgeNullByteMethods {
public static void WriteEdgeNullByte(SpecWriter w, EdgeNullByte obj) {
    w.BeginObject(2);
    w.WriteField("s"); w.WriteString(obj.S);
    w.WriteField("b"); w.WriteBytes(obj.B);
    w.EndObject();
}

public static readonly SpecCodec<EdgeNullByte> EdgeNullByteCodec = new(
    Encode: (w, obj) => WriteEdgeNullByte(w, obj),
    Decode: r => {
        string _S = "";
        byte[] _B = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "s": _S = r.ReadString(); break;
                case "b": _B = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeNullByte(S: _S, B: _B);
    }
);
} // EdgeNullByteMethods

public record EdgeBoundary(
    int I32Neg129,
    int I32128,
    int I32256,
    int I3265536,
    int I32Neg32769,
    uint U3265536
);

public static class EdgeBoundaryMethods {
public static void WriteEdgeBoundary(SpecWriter w, EdgeBoundary obj) {
    w.BeginObject(6);
    w.WriteField("i32_neg129"); w.WriteInt32(obj.I32Neg129);
    w.WriteField("i32_128"); w.WriteInt32(obj.I32128);
    w.WriteField("i32_256"); w.WriteInt32(obj.I32256);
    w.WriteField("i32_65536"); w.WriteInt32(obj.I3265536);
    w.WriteField("i32_neg32769"); w.WriteInt32(obj.I32Neg32769);
    w.WriteField("u32_65536"); w.WriteUint32(obj.U3265536);
    w.EndObject();
}

public static readonly SpecCodec<EdgeBoundary> EdgeBoundaryCodec = new(
    Encode: (w, obj) => WriteEdgeBoundary(w, obj),
    Decode: r => {
        int _I32Neg129 = 0;
        int _I32128 = 0;
        int _I32256 = 0;
        int _I3265536 = 0;
        int _I32Neg32769 = 0;
        uint _U3265536 = 0u;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "i32_neg129": _I32Neg129 = r.ReadInt32(); break;
                case "i32_128": _I32128 = r.ReadInt32(); break;
                case "i32_256": _I32256 = r.ReadInt32(); break;
                case "i32_65536": _I3265536 = r.ReadInt32(); break;
                case "i32_neg32769": _I32Neg32769 = r.ReadInt32(); break;
                case "u32_65536": _U3265536 = r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeBoundary(I32Neg129: _I32Neg129, I32128: _I32128, I32256: _I32256, I3265536: _I3265536, I32Neg32769: _I32Neg32769, U3265536: _U3265536);
    }
);
} // EdgeBoundaryMethods

public record EdgeStrLen(
    string S31,
    string S32,
    string S255,
    string S256
);

public static class EdgeStrLenMethods {
public static void WriteEdgeStrLen(SpecWriter w, EdgeStrLen obj) {
    w.BeginObject(4);
    w.WriteField("s31"); w.WriteString(obj.S31);
    w.WriteField("s32"); w.WriteString(obj.S32);
    w.WriteField("s255"); w.WriteString(obj.S255);
    w.WriteField("s256"); w.WriteString(obj.S256);
    w.EndObject();
}

public static readonly SpecCodec<EdgeStrLen> EdgeStrLenCodec = new(
    Encode: (w, obj) => WriteEdgeStrLen(w, obj),
    Decode: r => {
        string _S31 = "";
        string _S32 = "";
        string _S255 = "";
        string _S256 = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "s31": _S31 = r.ReadString(); break;
                case "s32": _S32 = r.ReadString(); break;
                case "s255": _S255 = r.ReadString(); break;
                case "s256": _S256 = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeStrLen(S31: _S31, S32: _S32, S255: _S255, S256: _S256);
    }
);
} // EdgeStrLenMethods

public record EdgeBytesLen(
    byte[] B31,
    byte[] B32,
    byte[] B255,
    byte[] B256
);

public static class EdgeBytesLenMethods {
public static void WriteEdgeBytesLen(SpecWriter w, EdgeBytesLen obj) {
    w.BeginObject(4);
    w.WriteField("b31"); w.WriteBytes(obj.B31);
    w.WriteField("b32"); w.WriteBytes(obj.B32);
    w.WriteField("b255"); w.WriteBytes(obj.B255);
    w.WriteField("b256"); w.WriteBytes(obj.B256);
    w.EndObject();
}

public static readonly SpecCodec<EdgeBytesLen> EdgeBytesLenCodec = new(
    Encode: (w, obj) => WriteEdgeBytesLen(w, obj),
    Decode: r => {
        byte[] _B31 = Array.Empty<byte>();
        byte[] _B32 = Array.Empty<byte>();
        byte[] _B255 = Array.Empty<byte>();
        byte[] _B256 = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "b31": _B31 = r.ReadBytes(); break;
                case "b32": _B32 = r.ReadBytes(); break;
                case "b255": _B255 = r.ReadBytes(); break;
                case "b256": _B256 = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeBytesLen(B31: _B31, B32: _B32, B255: _B255, B256: _B256);
    }
);
} // EdgeBytesLenMethods

public record EdgeArrEmpty(
    List<string> Items
);

public static class EdgeArrEmptyMethods {
public static void WriteEdgeArrEmpty(SpecWriter w, EdgeArrEmpty obj) {
    w.BeginObject(1);
    w.WriteField("items"); w.BeginArray(obj.Items.Count);
        foreach (var item in obj.Items) { w.NextElement(); w.WriteString(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<EdgeArrEmpty> EdgeArrEmptyCodec = new(
    Encode: (w, obj) => WriteEdgeArrEmpty(w, obj),
    Decode: r => {
        List<string> _Items = new List<string>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "items": _Items = ((Func<List<string>>)(() => { var list = new List<string>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadString()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeArrEmpty(Items: _Items);
    }
);
} // EdgeArrEmptyMethods

public record EdgeArrBoundary(
    List<int> A15,
    List<int> A16
);

public static class EdgeArrBoundaryMethods {
public static void WriteEdgeArrBoundary(SpecWriter w, EdgeArrBoundary obj) {
    w.BeginObject(2);
    w.WriteField("a15"); w.BeginArray(obj.A15.Count);
        foreach (var item in obj.A15) { w.NextElement(); w.WriteInt32(item); }
        w.EndArray();
    w.WriteField("a16"); w.BeginArray(obj.A16.Count);
        foreach (var item in obj.A16) { w.NextElement(); w.WriteInt32(item); }
        w.EndArray();
    w.EndObject();
}

public static readonly SpecCodec<EdgeArrBoundary> EdgeArrBoundaryCodec = new(
    Encode: (w, obj) => WriteEdgeArrBoundary(w, obj),
    Decode: r => {
        List<int> _A15 = new List<int>();
        List<int> _A16 = new List<int>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "a15": _A15 = ((Func<List<int>>)(() => { var list = new List<int>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadInt32()); r.EndArray(); return list; }))(); break;
                case "a16": _A16 = ((Func<List<int>>)(() => { var list = new List<int>(); r.BeginArray(); while (r.HasNextElement()) list.Add(r.ReadInt32()); r.EndArray(); return list; }))(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new EdgeArrBoundary(A15: _A15, A16: _A16);
    }
);
} // EdgeArrBoundaryMethods
