// Generated by @specodec/typespec-emitter-csharp. DO NOT EDIT.
namespace AllTypes.Many;

using Specodec;
using System;
using System.Collections.Generic;

public record Five01(
    string F1,
    int F2,
    bool F3,
    double F4,
    byte[] F5
);

public static class Five01Methods {
public static void WriteFive01(SpecWriter w, Five01 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteString(obj.F1);
    w.WriteField("f2"); w.WriteInt32(obj.F2);
    w.WriteField("f3"); w.WriteBool(obj.F3);
    w.WriteField("f4"); w.WriteFloat64(obj.F4);
    w.WriteField("f5"); w.WriteBytes(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five01> Five01Codec = new(
    Encode: (w, obj) => WriteFive01(w, obj),
    Decode: r => {
        string _F1 = "";
        int _F2 = 0;
        bool _F3 = false;
        double _F4 = 0.0;
        byte[] _F5 = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadString(); break;
                case "f2": _F2 = r.ReadInt32(); break;
                case "f3": _F3 = r.ReadBool(); break;
                case "f4": _F4 = r.ReadFloat64(); break;
                case "f5": _F5 = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five01(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five01Methods

public record Five02(
    int F1,
    int F2,
    int F3,
    int F4,
    int F5
);

public static class Five02Methods {
public static void WriteFive02(SpecWriter w, Five02 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteInt32(obj.F1);
    w.WriteField("f2"); w.WriteInt32(obj.F2);
    w.WriteField("f3"); w.WriteInt32(obj.F3);
    w.WriteField("f4"); w.WriteInt32(obj.F4);
    w.WriteField("f5"); w.WriteInt32(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five02> Five02Codec = new(
    Encode: (w, obj) => WriteFive02(w, obj),
    Decode: r => {
        int _F1 = 0;
        int _F2 = 0;
        int _F3 = 0;
        int _F4 = 0;
        int _F5 = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadInt32(); break;
                case "f2": _F2 = r.ReadInt32(); break;
                case "f3": _F3 = r.ReadInt32(); break;
                case "f4": _F4 = r.ReadInt32(); break;
                case "f5": _F5 = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five02(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five02Methods

public record Five03(
    string F1,
    string F2,
    string F3,
    string F4,
    string F5
);

public static class Five03Methods {
public static void WriteFive03(SpecWriter w, Five03 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteString(obj.F1);
    w.WriteField("f2"); w.WriteString(obj.F2);
    w.WriteField("f3"); w.WriteString(obj.F3);
    w.WriteField("f4"); w.WriteString(obj.F4);
    w.WriteField("f5"); w.WriteString(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five03> Five03Codec = new(
    Encode: (w, obj) => WriteFive03(w, obj),
    Decode: r => {
        string _F1 = "";
        string _F2 = "";
        string _F3 = "";
        string _F4 = "";
        string _F5 = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadString(); break;
                case "f2": _F2 = r.ReadString(); break;
                case "f3": _F3 = r.ReadString(); break;
                case "f4": _F4 = r.ReadString(); break;
                case "f5": _F5 = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five03(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five03Methods

public record Five04(
    double F1,
    int F2,
    string F3,
    bool F4,
    byte[] F5
);

public static class Five04Methods {
public static void WriteFive04(SpecWriter w, Five04 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteFloat64(obj.F1);
    w.WriteField("f2"); w.WriteInt32(obj.F2);
    w.WriteField("f3"); w.WriteString(obj.F3);
    w.WriteField("f4"); w.WriteBool(obj.F4);
    w.WriteField("f5"); w.WriteBytes(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five04> Five04Codec = new(
    Encode: (w, obj) => WriteFive04(w, obj),
    Decode: r => {
        double _F1 = 0.0;
        int _F2 = 0;
        string _F3 = "";
        bool _F4 = false;
        byte[] _F5 = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadFloat64(); break;
                case "f2": _F2 = r.ReadInt32(); break;
                case "f3": _F3 = r.ReadString(); break;
                case "f4": _F4 = r.ReadBool(); break;
                case "f5": _F5 = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five04(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five04Methods

public record Five05(
    long F1,
    ulong F2,
    string F3,
    float F4,
    int F5
);

public static class Five05Methods {
public static void WriteFive05(SpecWriter w, Five05 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteInt64(obj.F1);
    w.WriteField("f2"); w.WriteUint64(obj.F2);
    w.WriteField("f3"); w.WriteString(obj.F3);
    w.WriteField("f4"); w.WriteFloat32(obj.F4);
    w.WriteField("f5"); w.WriteInt32(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five05> Five05Codec = new(
    Encode: (w, obj) => WriteFive05(w, obj),
    Decode: r => {
        long _F1 = 0L;
        ulong _F2 = 0UL;
        string _F3 = "";
        float _F4 = 0f;
        int _F5 = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadInt64(); break;
                case "f2": _F2 = r.ReadUint64(); break;
                case "f3": _F3 = r.ReadString(); break;
                case "f4": _F4 = r.ReadFloat32(); break;
                case "f5": _F5 = r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five05(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five05Methods

public record Five06(
    bool F1,
    string F2,
    int F3,
    double F4,
    uint F5
);

public static class Five06Methods {
public static void WriteFive06(SpecWriter w, Five06 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteBool(obj.F1);
    w.WriteField("f2"); w.WriteString(obj.F2);
    w.WriteField("f3"); w.WriteInt32(obj.F3);
    w.WriteField("f4"); w.WriteFloat64(obj.F4);
    w.WriteField("f5"); w.WriteUint32(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five06> Five06Codec = new(
    Encode: (w, obj) => WriteFive06(w, obj),
    Decode: r => {
        bool _F1 = false;
        string _F2 = "";
        int _F3 = 0;
        double _F4 = 0.0;
        uint _F5 = 0u;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadBool(); break;
                case "f2": _F2 = r.ReadString(); break;
                case "f3": _F3 = r.ReadInt32(); break;
                case "f4": _F4 = r.ReadFloat64(); break;
                case "f5": _F5 = r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five06(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five06Methods

public record Five07(
    byte[] F1,
    byte[] F2,
    string F3,
    int F4,
    double F5
);

public static class Five07Methods {
public static void WriteFive07(SpecWriter w, Five07 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteBytes(obj.F1);
    w.WriteField("f2"); w.WriteBytes(obj.F2);
    w.WriteField("f3"); w.WriteString(obj.F3);
    w.WriteField("f4"); w.WriteInt32(obj.F4);
    w.WriteField("f5"); w.WriteFloat64(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five07> Five07Codec = new(
    Encode: (w, obj) => WriteFive07(w, obj),
    Decode: r => {
        byte[] _F1 = Array.Empty<byte>();
        byte[] _F2 = Array.Empty<byte>();
        string _F3 = "";
        int _F4 = 0;
        double _F5 = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadBytes(); break;
                case "f2": _F2 = r.ReadBytes(); break;
                case "f3": _F3 = r.ReadString(); break;
                case "f4": _F4 = r.ReadInt32(); break;
                case "f5": _F5 = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five07(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five07Methods

public record Five08(
    byte F1,
    ushort F2,
    uint F3,
    byte F4,
    short F5
);

public static class Five08Methods {
public static void WriteFive08(SpecWriter w, Five08 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteUint32(obj.F1);
    w.WriteField("f2"); w.WriteUint32(obj.F2);
    w.WriteField("f3"); w.WriteUint32(obj.F3);
    w.WriteField("f4"); w.WriteInt32((sbyte)obj.F4);
    w.WriteField("f5"); w.WriteInt32(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five08> Five08Codec = new(
    Encode: (w, obj) => WriteFive08(w, obj),
    Decode: r => {
        byte _F1 = 0;
        ushort _F2 = 0;
        uint _F3 = 0u;
        byte _F4 = 0;
        short _F5 = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = (byte)r.ReadUint32(); break;
                case "f2": _F2 = (ushort)r.ReadUint32(); break;
                case "f3": _F3 = r.ReadUint32(); break;
                case "f4": _F4 = (byte)r.ReadInt32(); break;
                case "f5": _F5 = (short)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five08(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five08Methods

public record Five09(
    float F1,
    double F2,
    int F3,
    long F4,
    string F5
);

public static class Five09Methods {
public static void WriteFive09(SpecWriter w, Five09 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteFloat32(obj.F1);
    w.WriteField("f2"); w.WriteFloat64(obj.F2);
    w.WriteField("f3"); w.WriteInt32(obj.F3);
    w.WriteField("f4"); w.WriteInt64(obj.F4);
    w.WriteField("f5"); w.WriteString(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five09> Five09Codec = new(
    Encode: (w, obj) => WriteFive09(w, obj),
    Decode: r => {
        float _F1 = 0f;
        double _F2 = 0.0;
        int _F3 = 0;
        long _F4 = 0L;
        string _F5 = "";
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadFloat32(); break;
                case "f2": _F2 = r.ReadFloat64(); break;
                case "f3": _F3 = r.ReadInt32(); break;
                case "f4": _F4 = r.ReadInt64(); break;
                case "f5": _F5 = r.ReadString(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five09(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five09Methods

public record Five10(
    string F1,
    bool F2,
    long F3,
    ulong F4,
    double F5
);

public static class Five10Methods {
public static void WriteFive10(SpecWriter w, Five10 obj) {
    w.BeginObject(5);
    w.WriteField("f1"); w.WriteString(obj.F1);
    w.WriteField("f2"); w.WriteBool(obj.F2);
    w.WriteField("f3"); w.WriteInt64(obj.F3);
    w.WriteField("f4"); w.WriteUint64(obj.F4);
    w.WriteField("f5"); w.WriteFloat64(obj.F5);
    w.EndObject();
}

public static readonly SpecCodec<Five10> Five10Codec = new(
    Encode: (w, obj) => WriteFive10(w, obj),
    Decode: r => {
        string _F1 = "";
        bool _F2 = false;
        long _F3 = 0L;
        ulong _F4 = 0UL;
        double _F5 = 0.0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadString(); break;
                case "f2": _F2 = r.ReadBool(); break;
                case "f3": _F3 = r.ReadInt64(); break;
                case "f4": _F4 = r.ReadUint64(); break;
                case "f5": _F5 = r.ReadFloat64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Five10(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5);
    }
);
} // Five10Methods

public record Ten01(
    string F1,
    bool F2,
    byte F3,
    short F4,
    int F5,
    long F6,
    byte F7,
    ushort F8,
    uint F9,
    ulong F10
);

public static class Ten01Methods {
public static void WriteTen01(SpecWriter w, Ten01 obj) {
    w.BeginObject(10);
    w.WriteField("f1"); w.WriteString(obj.F1);
    w.WriteField("f2"); w.WriteBool(obj.F2);
    w.WriteField("f3"); w.WriteInt32((sbyte)obj.F3);
    w.WriteField("f4"); w.WriteInt32(obj.F4);
    w.WriteField("f5"); w.WriteInt32(obj.F5);
    w.WriteField("f6"); w.WriteInt64(obj.F6);
    w.WriteField("f7"); w.WriteUint32(obj.F7);
    w.WriteField("f8"); w.WriteUint32(obj.F8);
    w.WriteField("f9"); w.WriteUint32(obj.F9);
    w.WriteField("f10"); w.WriteUint64(obj.F10);
    w.EndObject();
}

public static readonly SpecCodec<Ten01> Ten01Codec = new(
    Encode: (w, obj) => WriteTen01(w, obj),
    Decode: r => {
        string _F1 = "";
        bool _F2 = false;
        byte _F3 = 0;
        short _F4 = 0;
        int _F5 = 0;
        long _F6 = 0L;
        byte _F7 = 0;
        ushort _F8 = 0;
        uint _F9 = 0u;
        ulong _F10 = 0UL;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadString(); break;
                case "f2": _F2 = r.ReadBool(); break;
                case "f3": _F3 = (byte)r.ReadInt32(); break;
                case "f4": _F4 = (short)r.ReadInt32(); break;
                case "f5": _F5 = r.ReadInt32(); break;
                case "f6": _F6 = r.ReadInt64(); break;
                case "f7": _F7 = (byte)r.ReadUint32(); break;
                case "f8": _F8 = (ushort)r.ReadUint32(); break;
                case "f9": _F9 = r.ReadUint32(); break;
                case "f10": _F10 = r.ReadUint64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Ten01(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10);
    }
);
} // Ten01Methods

public record Ten02(
    short F1,
    int F2,
    long F3,
    byte F4,
    ushort F5,
    uint F6,
    ulong F7,
    float F8,
    double F9,
    byte[] F10
);

public static class Ten02Methods {
public static void WriteTen02(SpecWriter w, Ten02 obj) {
    w.BeginObject(10);
    w.WriteField("f1"); w.WriteInt32(obj.F1);
    w.WriteField("f2"); w.WriteInt32(obj.F2);
    w.WriteField("f3"); w.WriteInt64(obj.F3);
    w.WriteField("f4"); w.WriteUint32(obj.F4);
    w.WriteField("f5"); w.WriteUint32(obj.F5);
    w.WriteField("f6"); w.WriteUint32(obj.F6);
    w.WriteField("f7"); w.WriteUint64(obj.F7);
    w.WriteField("f8"); w.WriteFloat32(obj.F8);
    w.WriteField("f9"); w.WriteFloat64(obj.F9);
    w.WriteField("f10"); w.WriteBytes(obj.F10);
    w.EndObject();
}

public static readonly SpecCodec<Ten02> Ten02Codec = new(
    Encode: (w, obj) => WriteTen02(w, obj),
    Decode: r => {
        short _F1 = 0;
        int _F2 = 0;
        long _F3 = 0L;
        byte _F4 = 0;
        ushort _F5 = 0;
        uint _F6 = 0u;
        ulong _F7 = 0UL;
        float _F8 = 0f;
        double _F9 = 0.0;
        byte[] _F10 = Array.Empty<byte>();
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = (short)r.ReadInt32(); break;
                case "f2": _F2 = r.ReadInt32(); break;
                case "f3": _F3 = r.ReadInt64(); break;
                case "f4": _F4 = (byte)r.ReadUint32(); break;
                case "f5": _F5 = (ushort)r.ReadUint32(); break;
                case "f6": _F6 = r.ReadUint32(); break;
                case "f7": _F7 = r.ReadUint64(); break;
                case "f8": _F8 = r.ReadFloat32(); break;
                case "f9": _F9 = r.ReadFloat64(); break;
                case "f10": _F10 = r.ReadBytes(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Ten02(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10);
    }
);
} // Ten02Methods

public record Ten03(
    byte F1,
    ushort F2,
    uint F3,
    ulong F4,
    float F5,
    double F6,
    byte[] F7,
    string F8,
    bool F9,
    byte F10
);

public static class Ten03Methods {
public static void WriteTen03(SpecWriter w, Ten03 obj) {
    w.BeginObject(10);
    w.WriteField("f1"); w.WriteUint32(obj.F1);
    w.WriteField("f2"); w.WriteUint32(obj.F2);
    w.WriteField("f3"); w.WriteUint32(obj.F3);
    w.WriteField("f4"); w.WriteUint64(obj.F4);
    w.WriteField("f5"); w.WriteFloat32(obj.F5);
    w.WriteField("f6"); w.WriteFloat64(obj.F6);
    w.WriteField("f7"); w.WriteBytes(obj.F7);
    w.WriteField("f8"); w.WriteString(obj.F8);
    w.WriteField("f9"); w.WriteBool(obj.F9);
    w.WriteField("f10"); w.WriteInt32((sbyte)obj.F10);
    w.EndObject();
}

public static readonly SpecCodec<Ten03> Ten03Codec = new(
    Encode: (w, obj) => WriteTen03(w, obj),
    Decode: r => {
        byte _F1 = 0;
        ushort _F2 = 0;
        uint _F3 = 0u;
        ulong _F4 = 0UL;
        float _F5 = 0f;
        double _F6 = 0.0;
        byte[] _F7 = Array.Empty<byte>();
        string _F8 = "";
        bool _F9 = false;
        byte _F10 = 0;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = (byte)r.ReadUint32(); break;
                case "f2": _F2 = (ushort)r.ReadUint32(); break;
                case "f3": _F3 = r.ReadUint32(); break;
                case "f4": _F4 = r.ReadUint64(); break;
                case "f5": _F5 = r.ReadFloat32(); break;
                case "f6": _F6 = r.ReadFloat64(); break;
                case "f7": _F7 = r.ReadBytes(); break;
                case "f8": _F8 = r.ReadString(); break;
                case "f9": _F9 = r.ReadBool(); break;
                case "f10": _F10 = (byte)r.ReadInt32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Ten03(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10);
    }
);
} // Ten03Methods

public record Ten04(
    ulong F1,
    float F2,
    double F3,
    byte[] F4,
    string F5,
    bool F6,
    byte F7,
    short F8,
    int F9,
    long F10
);

public static class Ten04Methods {
public static void WriteTen04(SpecWriter w, Ten04 obj) {
    w.BeginObject(10);
    w.WriteField("f1"); w.WriteUint64(obj.F1);
    w.WriteField("f2"); w.WriteFloat32(obj.F2);
    w.WriteField("f3"); w.WriteFloat64(obj.F3);
    w.WriteField("f4"); w.WriteBytes(obj.F4);
    w.WriteField("f5"); w.WriteString(obj.F5);
    w.WriteField("f6"); w.WriteBool(obj.F6);
    w.WriteField("f7"); w.WriteInt32((sbyte)obj.F7);
    w.WriteField("f8"); w.WriteInt32(obj.F8);
    w.WriteField("f9"); w.WriteInt32(obj.F9);
    w.WriteField("f10"); w.WriteInt64(obj.F10);
    w.EndObject();
}

public static readonly SpecCodec<Ten04> Ten04Codec = new(
    Encode: (w, obj) => WriteTen04(w, obj),
    Decode: r => {
        ulong _F1 = 0UL;
        float _F2 = 0f;
        double _F3 = 0.0;
        byte[] _F4 = Array.Empty<byte>();
        string _F5 = "";
        bool _F6 = false;
        byte _F7 = 0;
        short _F8 = 0;
        int _F9 = 0;
        long _F10 = 0L;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadUint64(); break;
                case "f2": _F2 = r.ReadFloat32(); break;
                case "f3": _F3 = r.ReadFloat64(); break;
                case "f4": _F4 = r.ReadBytes(); break;
                case "f5": _F5 = r.ReadString(); break;
                case "f6": _F6 = r.ReadBool(); break;
                case "f7": _F7 = (byte)r.ReadInt32(); break;
                case "f8": _F8 = (short)r.ReadInt32(); break;
                case "f9": _F9 = r.ReadInt32(); break;
                case "f10": _F10 = r.ReadInt64(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Ten04(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10);
    }
);
} // Ten04Methods

public record Ten05(
    byte[] F1,
    string F2,
    bool F3,
    byte F4,
    short F5,
    int F6,
    long F7,
    byte F8,
    ushort F9,
    uint F10
);

public static class Ten05Methods {
public static void WriteTen05(SpecWriter w, Ten05 obj) {
    w.BeginObject(10);
    w.WriteField("f1"); w.WriteBytes(obj.F1);
    w.WriteField("f2"); w.WriteString(obj.F2);
    w.WriteField("f3"); w.WriteBool(obj.F3);
    w.WriteField("f4"); w.WriteInt32((sbyte)obj.F4);
    w.WriteField("f5"); w.WriteInt32(obj.F5);
    w.WriteField("f6"); w.WriteInt32(obj.F6);
    w.WriteField("f7"); w.WriteInt64(obj.F7);
    w.WriteField("f8"); w.WriteUint32(obj.F8);
    w.WriteField("f9"); w.WriteUint32(obj.F9);
    w.WriteField("f10"); w.WriteUint32(obj.F10);
    w.EndObject();
}

public static readonly SpecCodec<Ten05> Ten05Codec = new(
    Encode: (w, obj) => WriteTen05(w, obj),
    Decode: r => {
        byte[] _F1 = Array.Empty<byte>();
        string _F2 = "";
        bool _F3 = false;
        byte _F4 = 0;
        short _F5 = 0;
        int _F6 = 0;
        long _F7 = 0L;
        byte _F8 = 0;
        ushort _F9 = 0;
        uint _F10 = 0u;
        r.BeginObject();
        while (r.HasNextField()) {
            switch (r.ReadFieldName()) {
                case "f1": _F1 = r.ReadBytes(); break;
                case "f2": _F2 = r.ReadString(); break;
                case "f3": _F3 = r.ReadBool(); break;
                case "f4": _F4 = (byte)r.ReadInt32(); break;
                case "f5": _F5 = (short)r.ReadInt32(); break;
                case "f6": _F6 = r.ReadInt32(); break;
                case "f7": _F7 = r.ReadInt64(); break;
                case "f8": _F8 = (byte)r.ReadUint32(); break;
                case "f9": _F9 = (ushort)r.ReadUint32(); break;
                case "f10": _F10 = r.ReadUint32(); break;
                default: r.Skip(); break;
            }
        }
        r.EndObject();
        return new Ten05(F1: _F1, F2: _F2, F3: _F3, F4: _F4, F5: _F5, F6: _F6, F7: _F7, F8: _F8, F9: _F9, F10: _F10);
    }
);
} // Ten05Methods
